// Run explicitly against an isolated .qa application: ANDROID_HOME=... node tests/android-native.mjs
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PNG} from 'pngjs';
import {zipSync} from 'fflate';
import {chromium,expect} from '@playwright/test';
import {buildRequest,defaults} from '../src/lib/request.mjs';
import {quoteAnlas} from '../src/lib/anlas.mjs';
import {WORKBENCH_SKINS} from '../src/lib/loading-skins.mjs';
import {readStealthMetadata} from '../src/lib/metadata.mjs';


const serial=process.env.FX_ANDROID_SERIAL||'emulator-5570',app='app.luciferfx.share.qa',out=process.env.FX_ANDROID_QA_OUT||'.local/android-qa';
const exec=promisify(execFile),adbPath=path.join(process.env.ANDROID_HOME,'platform-tools',process.platform==='win32'?'adb.exe':'adb');
const adb=async(...args)=>(await exec(adbPath,['-s',serial,...args],{maxBuffer:8*1024*1024})).stdout.trim();
const pause=ms=>new Promise(r=>setTimeout(r,ms));await mkdir(out,{recursive:true});
const png=new PNG({width:320,height:480});png.data.fill(255);for(let y=0;y<480;y++)for(let x=0;x<320;x++){const i=(y*320+x)*4;png.data[i]=50+x%150;png.data[i+1]=90+y%120;png.data[i+2]=170;}
const bytes=PNG.sync.write(png),calls=[];
const provider=http.createServer(async(req,res)=>{let text='';for await(const c of req)text+=c;if(req.method==='GET'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({active:true,tier:3,data:[{id:'nai-diffusion-5-full'}]}));return;}const body=JSON.parse(text),wire=body.novelai?.body||body;calls.push({route:req.url,wire});
 if(req.url==='/ai/encode-vibe'){res.writeHead(200,{'Content-Type':'application/octet-stream'});res.end(Buffer.from('synthetic-encoding'));return;}
 if(wire.input?.includes('delayed'))await pause(2500);
 if(wire.input?.includes('fixture-failure')){res.writeHead(502,{'Content-Type':'application/json'});res.end(JSON.stringify({error:{message:'Synthetic failure fixture-only-secret'}}));return;}
 const n=wire.parameters?.n_samples||1;
 if(req.url.endsWith('-stream')){res.writeHead(200,{'Content-Type':'text/event-stream'});for(let i=0;i<n;i++)res.write('event: final\ndata: '+JSON.stringify({image:bytes.toString('base64'),samp_ix:i})+'\n\n');res.end();return;}
 if(req.url.includes('/v1/images/')){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({data:Array.from({length:n},()=>({b64_json:bytes.toString('base64')}))}));return;}
 res.writeHead(200,{'Content-Type':'application/zip'});res.end(Buffer.from(zipSync(Object.fromEntries(Array.from({length:n},(_,i)=>[i+'.png',bytes])))));
});await new Promise(r=>provider.listen(18941,'127.0.0.1',r));let browser,page;const passed=[],errors=[];
const check=(name,fn)=>Promise.resolve().then(fn).then(()=>{passed.push(name);console.log('PASS '+name);});
async function connect(){let problem;for(let attempt=0;attempt<20;attempt++){try{const pid=await adb('shell','pidof',app);await adb('forward','tcp:18943','localabstract:webview_devtools_remote_'+pid);browser=await chromium.connectOverCDP('http://127.0.0.1:18943',{noDefaults:true});page=browser.contexts()[0].pages()[0];page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>document.readyState==='complete');return;}catch(e){problem=e;await browser?.close().catch(()=>{});await pause(350);}}throw problem;}
async function raw(route,body,method=body?'POST':'GET'){return page.evaluate(async({route,body,method})=>{const r=await fetch(route,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};},{route,body,method});}
async function api(route,body,method){const r=await raw(route,body,method);assert.ok(r.status<400,route+': '+JSON.stringify(r));return r.data;}
async function finish(id){for(let i=0;i<100;i++){let j=await api('/api/generation-jobs/'+id);if(!['queued','running','stopping'].includes(j.status))return j;await pause(100);}throw Error('job timeout');}
const request=(prompt='synthetic android',extra={})=>buildRequest({...defaults(),prompt,seed:42,...extra});
async function generate(payload,extra={}){const job=await api('/api/generation-jobs',{clientRequestId:randomUUID(),payload,...extra});return finish(job.id);}
try{
 await adb('shell','pm','clear',app);await adb('shell','am','start','-n',app+'/app.luciferfx.share.MainActivity');await pause(1500);await adb('reverse','tcp:18941','tcp:18941');await connect();
 await api('/api/settings',{provider:'native',baseURL:'http://127.0.0.1:18941',key:'fixture-only-secret',beginner:false,tutorialComplete:true,autoSaveOutput:false});
 await page.evaluate(()=>{localStorage.setItem('lucifer-share-auto-update-check-v1','off');localStorage.setItem('lucifer-share-release-seen-v1','1.13.0');});
 await check('native status/version',async()=>{const s=await api('/api/status');assert.equal(s.platform,'android');assert.equal(s.version,'1.13.0-share');});
 await check('strict output preference validation',async()=>assert.equal((await raw('/api/settings',{autoSaveOutput:'false'})).status,400));
 let result,id,payload=request();
 await check('generation and durable internal cache without output',async()=>{result=await generate(payload,{preventDuplicate:true});assert.equal(result.status,'success');id=result.result.id;assert.equal(result.result.images.length,1);assert.ok(!result.result.images[0].outputPath);assert.equal(result.result.images[0].width,320);});
 await check('same ID replay does not resubmit',async()=>{let n=calls.length;await api('/api/generation-jobs',{clientRequestId:result.id,payload,preventDuplicate:true});assert.equal(calls.length,n);});
 await check('duplicate generation blocked before provider',async()=>{let n=calls.length;assert.equal((await raw('/api/generation-jobs',{clientRequestId:randomUUID(),payload,preventDuplicate:true})).data.error.code,'duplicate_generation');assert.equal(calls.length,n);});
 await check('model mismatch rejected',async()=>{const bad=structuredClone(payload);bad.novelai.body.model='nai-diffusion-4-5-full';assert.equal((await raw('/api/generation-jobs',{clientRequestId:randomUUID(),payload:bad})).status,400);});
 await check('V4.5 Full/Curated and cost parity',async()=>{await api('/api/anlas',{action:'pricingPolicy',value:'opus'});for(const model of ['nai-diffusion-4-5-full','nai-diffusion-4-5-curated']){const p=request('model fixture',{model});const q=await api('/api/anlas/quote',{payload:p}),expected=quoteAnlas(p,[],{policy:'opus'});for(const f of ['known','amount','perImage','freeImages'])assert.equal(q[f],expected[f],model+' '+f);const j=await generate(p);assert.equal(j.status,'success',JSON.stringify(j));}});
 await check('Vibe encode caches and preserves request IDs',async()=>{let n=calls.length;const req={model:'nai-diffusion-4-5-full',image:bytes.toString('base64'),information:1,requestId:randomUUID()};assert.equal((await api('/api/reference/encode',req)).status,'completed');await api('/api/reference/encode',req);await api('/api/reference/encode',{...req,requestId:randomUUID()});assert.equal(calls.length,n+1);assert.equal((await raw('/api/reference/encode',{...req,information:.5})).status,409);});
 await check('Vibe encoding is recorded once at 2 Anlas',async()=>{const ledger=await api('/api/anlas');const encodes=ledger.entries.filter(e=>e.id.startsWith('encode-'));assert.equal(encodes.length,1);assert.equal(encodes[0].estimate,2);});
 await check('serial Opus batch, streaming and OpenAI transport',async()=>{const batch=await generate(request('batch fixture',{n:3}),{opusBatch:true});assert.equal(batch.status,'success');assert.deepEqual(batch.batch.items.map(i=>i.seed),[42,43,44]);const stream=request('stream fixture');stream.novelai.endpoint='/ai/generate-image-stream';assert.equal((await generate(stream)).status,'success');await api('/api/settings',{provider:'openai',baseURL:'http://127.0.0.1:18941/v1',key:'fixture-only-secret'});assert.equal((await generate(request('openai fixture'))).status,'success');await api('/api/settings',{provider:'native',baseURL:'http://127.0.0.1:18941',key:'fixture-only-secret'});});
 await check('native gallery search, group and PATCH annotations',async()=>{const found=await api('/api/generated-library?q=synthetic%20android');assert.ok(found.items.some(x=>x.result_id===id&&x.hasFile));let a=await api('/api/generated-library/annotation',{id,index:0,favorite:true,tags:['Android QA']},'PATCH');assert.equal(a.favorite,true);assert.deepEqual(a.tags,['Android QA']);assert.equal((await api('/api/generated-library?favorite=1')).items.length,1);assert.ok((await api('/api/generated-library/groups?groupBy=tag')).groups.some(x=>x.value==='Android QA'));});
 await check('favorite protected by cleanup preview',async()=>{const p=await api('/api/generated-library/cleanup/preview',{keys:[id+':0']});assert.equal(p.count,0);assert.equal(p.protectedCount,1);});
 await check('cleanup preview invalidated by protection change',async()=>{await api('/api/generated-library/annotation',{id,index:0,favorite:false},'PATCH');let p=await api('/api/generated-library/cleanup/preview',{keys:[id+':0']});await api('/api/generated-library/annotation',{id,index:0,favorite:true},'PATCH');assert.equal((await raw('/api/generated-library/cleanup/execute',{token:p.token})).status,409);});
 await check('trash and restore preserve original indices',async()=>{await api('/api/generated-library/annotation',{id,index:0,favorite:false},'PATCH');let p=await api('/api/generated-library/cleanup/preview',{keys:[id+':0']});const trash=await api('/api/generated-library/cleanup/execute',{token:p.token});assert.equal(trash.count,1);assert.ok(!(await api('/api/generated-library')).items.some(x=>x.result_id===id));await api('/api/generated-library/cleanup/restore',{id:trash.id});assert.ok((await api('/api/generated-library')).items.some(x=>x.result_id===id&&x.image_index===0&&x.hasFile));});
 await check('manual saves protected',async()=>{await api('/api/save-result',{id,index:0});let p=await api('/api/generated-library/cleanup/preview',{keys:[id+':0']});assert.equal(p.protectedCount,1);});
 await check('private sharing removes chunks and pixel low-bit data',async()=>{const data=await page.evaluate(async id=>{const r=await fetch('/api/share-image?id='+id+'&index=0&metadata=strip');return Array.from(new Uint8Array(await r.arrayBuffer()));},id);const clean=PNG.sync.read(Buffer.from(data));assert.equal(clean.width,320);assert.equal(readStealthMetadata(clean.data,clean.width,clean.height),null);assert.ok(!Buffer.from(data).includes(Buffer.from('novelai_studio')));assert.ok(clean.data.every((v,i)=>i%4===3||v%2===0));});
 await check('history pagination',async()=>{const first=await api('/api/history?limit=1');assert.equal(first.entries.length,1);assert.ok(first.nextCursor);const next=await api('/api/history?limit=1&before='+first.nextCursor);assert.notEqual(next.entries[0].id,first.entries[0].id);});
 await check('backup preview and repeated restore do not duplicate cards',async()=>{const backup=await api('/api/backup');assert.ok(!JSON.stringify(backup).includes('fixture-only-secret'));const before=(await api('/api/library')).entries.length;await api('/api/backup/preview',{backup,mode:'restore'});await api('/api/backup',{backup,mode:'restore'});assert.equal((await api('/api/library')).entries.length,before);});
 await check('busy storage mutations blocked and failed requests not retried',async()=>{const j=await api('/api/generation-jobs',{clientRequestId:randomUUID(),payload:request('delayed fixture-failure')});assert.equal((await raw('/api/settings',{autoSaveOutput:true})).status,409);const done=await finish(j.id);assert.equal(done.status,'error');assert.ok(!JSON.stringify(done.error).includes('fixture-only-secret'));});
 await check('app restart preserves preferences, library and duplicate history',async()=>{await browser.close();await adb('shell','am','force-stop',app);await adb('shell','am','start','-n',app+'/app.luciferfx.share.MainActivity');await pause(1800);await connect();assert.equal((await api('/api/settings')).autoSaveOutput,false);assert.ok((await api('/api/generated-library')).items.some(x=>x.result_id===id));});
 await check('Android update identity and platform-specific installer',async()=>{assert.equal((await api('/api/release-info')).platform,'android');assert.equal((await api('/api/update-state')).supported,false);});
 await page.reload();await pause(1500);await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));
 await check('WebView renders and has no horizontal overflow',async()=>{await expect(page.locator('.generate')).toBeVisible();const dimensions=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(dimensions.scroll<=dimensions.width+1,JSON.stringify(dimensions));await page.screenshot({path:path.join(out,'android-workbench.png')});});
 await check('actual prompt editing and fixture generation via UI',async()=>{await page.getByLabel('正面提示词',{exact:true}).fill('phone ui fixture');await page.locator('.generate').click();await page.locator('.mobile-tabs').getByRole('button',{name:'画布',exact:true}).click();await expect(page.getByAltText('生成结果 1')).toBeVisible({timeout:20000});await page.screenshot({path:path.join(out,'android-result.png')});});
 await check('system gallery export and native share sheet',async()=>{await page.getByRole('button',{name:'保存到相册',exact:true}).click();await expect(page.getByText('已保存到系统相册 Pictures / Lucifer FX。',{exact:true})).toBeVisible();const images=await adb('shell','content','query','--uri','content://media/external/images/media','--projection','_display_name:relative_path');assert.ok(images.includes('Pictures/Lucifer FX'));await page.getByRole('button',{name:'系统分享（去参数）',exact:true}).click();await pause(700);await adb('shell','uiautomator','dump','/sdcard/fx-qa-window.xml');const xml=await adb('shell','cat','/sdcard/fx-qa-window.xml');assert.ok(xml.includes('intentresolver')||xml.includes('ChooserActivity'));await adb('shell','input','keyevent','KEYCODE_BACK');});
 for(const skin of WORKBENCH_SKINS)await check('native WebView theme '+skin.id,async()=>{await page.evaluate(id=>localStorage.setItem('lucifer-fx-appearance-v1',JSON.stringify({version:1,workbenchSkin:id,loadingSkin:'classic',motion:'off',characterDecorations:true})),skin.id);await page.reload();await expect(page.locator('.generate')).toBeVisible();const d=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(d.scroll<=d.width+1,skin.id+' '+JSON.stringify(d));await page.getByLabel('应用设置',{exact:true}).click();await page.getByRole('tab',{name:'保存位置',exact:true}).click();await expect(page.getByLabel('自动输出目录',{exact:true})).toBeVisible();const dialog=page.getByRole('dialog');assert.ok(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.screenshot({path:path.join(out,'android-'+skin.id+'.png')});await page.getByRole('button',{name:'关闭功能面板',exact:true}).click();});
 assert.deepEqual(errors,[],'WebView runtime errors');
}finally{await writeFile(path.join(out,'receipt.json'),JSON.stringify({date:new Date().toISOString(),serial,passed,errors,providerRequests:calls.length,paidRequests:0,physicalDeviceTested:false},null,2));await browser?.close().catch(()=>{});await new Promise(r=>provider.close(r));}
