import {RELEASE_NOTES} from '../src/lib/release-notes.mjs';
import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import {defaults} from '../src/lib/request.mjs';
const evidence='.local/gallery';
const SVG='<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="1920" viewBox="0 0 1280 1920"><defs><linearGradient id="s" x2="0" y2="1"><stop stop-color="#b4d8ea"/><stop offset="1" stop-color="#f5edd6"/></linearGradient></defs><path fill="url(#s)" d="M0 0h1280v1920H0z"/><circle cx="900" cy="540" r="150" fill="#fff7cf"/><path d="M0 1600 340 750 950 1780 1280 1100v820H0" fill="#789aa0"/><path d="M0 1750 650 1300 1280 1820v100H0" fill="#507d80"/></svg>';
const post={id:100,rating:'g',score:234,favorites:78,width:1280,height:1920,pageUrl:'https://danbooru.donmai.us/posts/100',thumbnail:'https://cdn.donmai.us/360x360/test.jpg',preview:'https://cdn.donmai.us/720x720/test.webp',original:'https://cdn.donmai.us/original/test.png',tags:{artist:['test_artist'],character:['test_character'],copyright:['test_series'],general:['blue_sky','landscape'],meta:['highres']},rawTags:'test_artist test_character test_series blue_sky landscape highres'};
async function setup(page,{fail=false,skin='classic',queryTimeout=false,allPages=false}={}){
 const calls=[],requests=[],errors=[];let clipboard='';
 await page.addInitScript(({s,skin,queryTimeout})=>{if(window!==window.top)return;localStorage.setItem('lucifer-share-auto-update-check-v1','off');if(queryTimeout)localStorage.setItem('lucifer-danbooru-v1',JSON.stringify({q:'landscape',sort:'favorites',rating:'all',period:'all'}));localStorage.setItem('novelai-studio-v1',JSON.stringify({version:1,state:s}));localStorage.setItem('lucifer-fx-appearance-v1',JSON.stringify({version:1,workbenchSkin:skin,loadingSkin:'classic'}));Object.defineProperty(navigator.clipboard,'writeText',{value:async text=>{window.__clipboard=text;},configurable:true});},{s:{...defaults(),prompt:'keep this prompt'},skin,queryTimeout});
 page.on('pageerror',e=>{errors.push(e.message);console.error('Gallery page error:',e.message);});page.on('request',r=>requests.push(r.url()));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text());});
 await page.route('https://cdn.donmai.us/**',r=>r.fulfill({contentType:'image/svg+xml',body:SVG}));
 await page.route('**/api/**',r=>{const p=new URL(r.request().url()).pathname;calls.push({p,method:r.request().method(),url:r.request().url()});const send=json=>r.fulfill({json});
  if(p==='/api/settings')return send({tutorialComplete:true,beginner:false});if(p==='/api/status')return send({keyConfigured:true,remoteTagsEnabled:false});if(p==='/api/models')return send({data:[{id:'nai-diffusion-5-full'}]});if(p==='/api/history'||p==='/api/library')return send({entries:[]});if(p==='/api/anlas')return send({pricingPolicy:'opus',calibrations:[]});if(p==='/api/comparisons')return send({entries:[],active:null});if(p==='/api/library/categories')return send({categories:['其他']});
  if(p==='/api/danbooru/image')return r.fulfill({contentType:'image/svg+xml',body:SVG});
  if(p==='/api/danbooru/posts'){if(fail)return r.fulfill({status:502,json:{error:{message:'Danbooru 限制了当前匿名访问，可在原站查看。'}}});const u=new URL(r.request().url()),pageNo=Number(u.searchParams.get('page')),rating=u.searchParams.get('rating');if(queryTimeout&&u.searchParams.get('sort')==='favorites'&&u.searchParams.get('period')==='all')return r.fulfill({status:504,json:{error:{code:'danbooru_query_timeout',message:'Danbooru 原站数据库查询超时。请缩小上传时间或改按最新排序。'}}});return send({posts:Array.from({length:pageNo===1||allPages?Number(u.searchParams.get('pageSize')||12):1},(_,i)=>({...post,...(allPages?{tags:{...post.tags,general:[...post.tags.general,...Array.from({length:60},(_,n)=>`tag_${n}`)]}}:{}),id:(allPages?pageNo*100:pageNo===1?100:200)+i,thumbnail:`https://cdn.donmai.us/360x360/test-${(allPages?pageNo*100:pageNo===1?100:200)+i}.jpg`,rating:rating==='all'?'g':rating,pageUrl:'https://danbooru.donmai.us/posts/'+((allPages?pageNo*100:pageNo===1?100:200)+i)})),page:pageNo,hasMore:allPages||pageNo===1,query:u.searchParams.get('q'),sourceUrl:'https://danbooru.donmai.us/posts?tags=rating%3Ag'});}
  return r.fulfill({status:418,json:{error:{message:'Unexpected request '+p}}});
 });await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.getByLabel('正面提示词',{exact:true})).toBeEditable();await expect(page.locator('.app')).toHaveAttribute('data-workbench-skin',skin);if(await page.getByLabel('关闭更新说明').isVisible())await page.getByLabel('关闭更新说明').click();await mkdir(evidence,{recursive:true});return{calls,requests,errors};
}
const open=p=>p.getByRole('button',{name:'D站图库',exact:true}).click();

for(const mobile of [false,true])test(`query timeout offers explicit narrower filters without an automatic fallback (${mobile?'mobile':'desktop'})`,async({page})=>{
 const c=await setup(page,{queryTimeout:true});if(mobile)await page.setViewportSize({width:390,height:844});await open(page);await expect(page.getByRole('alert')).toContainText('数据库查询超时');await expect(page.getByLabel('Danbooru 上传时间')).toHaveValue('all');await page.waitForTimeout(600);expect(c.calls.filter(x=>x.p==='/api/danbooru/posts')).toHaveLength(1);
 await page.screenshot({path:evidence+`/query-timeout-${mobile?'mobile':'desktop'}.png`});await page.getByRole('button',{name:'改查最近 7 天',exact:true}).click();await expect(page.getByLabel('Danbooru 上传时间')).toHaveValue('week');await expect(page.getByRole('button',{name:'查看图片 #100',exact:true})).toBeVisible();await expect(page.getByLabel('Danbooru 排序')).toHaveValue('favorites');await expect(page.getByLabel('Danbooru 内容等级')).toHaveValue('all');await expect(page.getByLabel('Danbooru 搜索标签')).toHaveValue('landscape');
 await page.getByLabel('Danbooru 上传时间').selectOption('all');await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'改按最新排序',exact:true}).click();await expect(page.getByLabel('Danbooru 排序')).toHaveValue('latest');await expect(page.getByLabel('Danbooru 上传时间')).toHaveValue('all');await expect(page.getByRole('button',{name:'查看图片 #100',exact:true})).toBeVisible();expect(c.calls.filter(x=>x.p==='/api/danbooru/posts')).toHaveLength(4);expect(c.calls.some(x=>x.method!=='GET')).toBe(false);expect(c.errors).toEqual([]);
});

test('gallery pages have 12 slots, only visible thumbnails load and revisited pages reuse metadata',async({page})=>{
 const c=await setup(page);await page.setViewportSize({width:390,height:700});await open(page);await expect(page.locator('.danbooru-tile')).toHaveCount(12);const thumbs=()=>c.requests.filter(url=>new URL(url).searchParams.get('url')?.includes('/360x360/'));
 await expect.poll(()=>thumbs().length).toBeGreaterThan(0);await page.waitForTimeout(200);const first=thumbs().length;expect(first).toBeLessThan(12);expect(c.calls.filter(x=>x.p==='/api/danbooru/posts')).toHaveLength(1);await page.getByRole('button',{name:'下一页',exact:true}).scrollIntoViewIfNeeded();await expect.poll(()=>thumbs().length).toBeGreaterThan(first);
 await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(page.locator('.danbooru-tile')).toHaveCount(1);await expect(page.getByRole('button',{name:'查看图片 #200',exact:true})).toBeVisible();expect(c.calls.filter(x=>x.p==='/api/danbooru/posts')).toHaveLength(2);await page.getByRole('button',{name:'上一页',exact:true}).click();await expect(page.locator('.danbooru-tile')).toHaveCount(12);expect(c.calls.filter(x=>x.p==='/api/danbooru/posts')).toHaveLength(2);expect(c.calls.some(x=>x.method!=='GET')).toBe(false);expect(c.errors).toEqual([]);
});

test('wide gallery fills two complete rows with one initial request and freezes limits across pagination',async({page})=>{
 const c=await setup(page);await page.setViewportSize({width:1500,height:1030});await open(page);const grid=page.locator('.danbooru-grid'),tiles=page.locator('.danbooru-tile'),lists=()=>c.calls.filter(x=>x.p==='/api/danbooru/posts');
 await expect(tiles).toHaveCount(16);const columns=await grid.evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length);expect(columns).toBe(8);const rows=await tiles.evaluateAll(items=>Object.values(items.reduce((rows,el)=>{const y=Math.round(el.getBoundingClientRect().top);rows[y]=(rows[y]||0)+1;return rows;},{})));expect(rows).toEqual([8,8]);expect(lists()).toHaveLength(1);expect(new URL(lists()[0].url).searchParams.get('pageSize')).toBe('16');await expect(page.getByAltText('Danbooru #115',{exact:true})).toBeVisible();await page.screenshot({path:evidence+'/full-rows-wide.png'});
 await page.setViewportSize({width:1024,height:900});await page.waitForTimeout(200);expect(lists()).toHaveLength(1);await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(tiles).toHaveCount(1);expect(new URL(lists()[1].url).searchParams.get('pageSize')).toBe('16');expect(new URL(lists()[1].url).searchParams.get('page')).toBe('2');
 await page.getByRole('button',{name:'搜索',exact:true}).click();await expect(tiles).toHaveCount(15);expect(await grid.evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length)).toBe(5);expect(lists()).toHaveLength(3);expect(new URL(lists()[2].url).searchParams.get('page')).toBe('1');await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();await expect(page.getByLabel('图片详情',{exact:true})).toBeVisible();expect(lists()).toHaveLength(3);expect(c.calls.some(x=>x.method!=='GET')).toBe(false);expect(c.errors).toEqual([]);
});

test('at most four visible thumbnail reads start; page changes discard old queued reads',async({page})=>{
 const c=await setup(page),held=[],failed=[];await page.setViewportSize({width:1600,height:1000});page.on('requestfailed',r=>{if(new URL(r.url()).searchParams.get('url')?.includes('/360x360/'))failed.push(r.url());});
 await page.route('**/api/danbooru/image?**',r=>{held.push(r);});
 try{await open(page);await expect(page.locator('.danbooru-tile')).toHaveCount(16);await expect.poll(()=>held.length).toBe(4);await page.waitForTimeout(200);expect(held).toHaveLength(4);await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(page.locator('.danbooru-tile')).toHaveCount(1);await expect.poll(()=>held.some(r=>new URL(r.request().url()).searchParams.get('url').includes('test-200'))).toBe(true);await expect.poll(()=>failed.length).toBe(4);expect(held).toHaveLength(5);expect(c.calls.some(x=>x.method!=='GET')).toBe(false);expect(c.errors).toEqual([]);}
 finally{for(const r of held)await r.fulfill({contentType:'image/svg+xml',body:SVG}).catch(()=>{});}
});
test('gallery loads only on open and searches, filters, sorts and paginates independently of generation',async({page})=>{
 const c=await setup(page);expect(c.requests.some(x=>/DanbooruPanel|donmai|danbooru\/posts/.test(x))).toBe(false);await open(page);await expect(page.getByLabel('Danbooru 内容等级')).toHaveValue('g');await expect(page.getByRole('button',{name:'查看图片 #100',exact:true})).toBeVisible();
 await page.getByLabel('Danbooru 搜索标签').fill('landscape');expect(c.calls.filter(x=>x.p==='/api/danbooru/posts')).toHaveLength(1);await page.getByRole('button',{name:'搜索',exact:true}).click();await page.getByLabel('Danbooru 排序').selectOption('score');await page.getByLabel('Danbooru 上传时间').selectOption('week');await page.getByLabel('Danbooru 内容等级').selectOption('s');await expect(page.getByRole('button',{name:'查看图片 #100',exact:true})).toBeVisible();
 const u=new URL(c.calls.filter(x=>x.p==='/api/danbooru/posts').at(-1).url);expect(Object.fromEntries(u.searchParams)).toMatchObject({q:'landscape',sort:'score',period:'week',rating:'s',page:'1'});
 await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(page.getByRole('button',{name:'查看图片 #200',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'下一页',exact:true})).toBeDisabled();await page.getByLabel('关闭功能面板').click();await expect(page.getByLabel('正面提示词',{exact:true})).toHaveValue('keep this prompt');expect(c.calls.every(x=>x.method==='GET')).toBe(true);expect(c.errors).toEqual([]);
});
test('detail groups, NovelAI formatting, copying raw tags and card collection retain the source',async({page})=>{
 const c=await setup(page);await open(page);await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();const detail=page.getByLabel('图片详情',{exact:true});await expect(page.getByLabel('待复制标签')).toHaveValue('artist:test artist, test character, test series, blue sky, landscape');
 await detail.getByRole('button',{name:'复制所选标签',exact:true}).click();expect(await page.evaluate(()=>window.__clipboard)).toBe('artist:test artist, test character, test series, blue sky, landscape');await page.getByRole('button',{name:'blue sky',exact:true}).click();await expect(page.getByLabel('待复制标签')).not.toHaveValue(/blue sky/);
 await page.getByLabel('NovelAI 格式',{exact:false}).uncheck();await expect(page.getByLabel('待复制标签')).toHaveValue('test_artist, test_character, test_series, landscape');await page.getByRole('button',{name:'复制全部原始 Tag',exact:true}).click();expect(await page.evaluate(()=>window.__clipboard)).toBe(post.rawTags);
 await page.getByRole('button',{name:'存为卡片',exact:true}).click();await expect(page.getByLabel('预设名称')).toHaveValue('Danbooru #100');await expect(page.getByLabel('预设来源')).toHaveValue(post.pageUrl);await expect(page.getByLabel('预设提示词')).toHaveValue('test_artist, test_character, test_series, landscape');expect(c.calls.some(x=>x.method==='POST')).toBe(false);expect(c.errors).toEqual([]);
});
test('original loads only on zoom; viewer pans, zooms, fits, supports native dragging and closes only itself',async({page})=>{
 const c=await setup(page);await open(page);await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();expect(c.requests.some(x=>decodeURIComponent(x).includes('/original/'))).toBe(false);await page.getByLabel('放大查看图片 #100').click();const viewer=page.getByRole('dialog',{name:'原图查看 #100'});await expect(viewer.getByText('原图 · 1280 × 1920',{exact:true})).toBeVisible();expect(c.requests.some(x=>new URL(x).searchParams.get('url')===post.original)).toBe(true);
 await viewer.getByRole('button',{name:'100%',exact:true}).click();await expect(page.getByLabel('图片缩放比例')).toHaveText('100%');await page.getByLabel('放大图片',{exact:true}).click();await expect(page.getByLabel('图片缩放比例')).toHaveText('125%');const stage=page.getByLabel('可缩放图片画布'),box=await stage.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.wheel(0,-100);await expect(page.getByLabel('图片缩放比例')).toHaveText('140%');
 const img=viewer.getByRole('img',{name:'Danbooru 原图 #100',exact:true});const before=await img.evaluate(e=>e.style.transform);await page.mouse.down();await page.mouse.move(box.x+box.width*.5+70,box.y+box.height*.5+50);await page.mouse.up();expect(await img.evaluate(e=>e.style.transform)).not.toBe(before);await viewer.getByRole('button',{name:'拖出图片',exact:true}).click();await expect(img).toHaveAttribute('draggable','true');const transferred=await img.evaluate(el=>{const dt=new DataTransfer();el.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt}));return [...dt.files].map(f=>({name:f.name,type:f.type,size:f.size}));});expect(transferred).toHaveLength(1);expect(transferred[0].size).toBeGreaterThan(0);await viewer.getByRole('button',{name:'适应画面',exact:true}).click();await page.screenshot({path:evidence+'/viewer-desktop.png'});
 await page.keyboard.press('Escape');await expect(viewer).toHaveCount(0);await expect(page.getByRole('dialog',{name:'D站图库',exact:true})).toBeVisible();expect(c.calls.some(x=>x.method==='POST')).toBe(false);expect(c.errors).toEqual([]);
});
test('upstream failure stays inside gallery and has an original-site fallback without retries',async({page})=>{
 const c=await setup(page,{fail:true});await open(page);await expect(page.getByRole('alert')).toContainText('匿名访问');await expect(page.getByRole('link',{name:'在原站查看',exact:true})).toHaveAttribute('href',/^https:\/\/danbooru\.donmai\.us/);await page.waitForTimeout(700);expect(c.calls.filter(x=>x.p==='/api/danbooru/posts')).toHaveLength(1);await page.getByLabel('关闭功能面板').click();await page.getByLabel('正面提示词',{exact:true}).fill('still editable');expect(c.errors).toEqual([]);
});
test('mobile gallery, selected tag copy and zoom controls remain reachable',async({page})=>{
 const c=await setup(page);await page.setViewportSize({width:390,height:844});await open(page);await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();await page.getByLabel('放大查看图片 #100').click();await expect(page.getByRole('img',{name:'Danbooru 原图 #100'})).toBeVisible();await expect(page.getByLabel('关闭大图')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await page.screenshot({path:evidence+'/viewer-mobile.png'});await page.getByLabel('关闭大图').click();await page.getByRole('button',{name:'复制所选标签',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:evidence+'/detail-mobile.png'});await page.getByLabel('返回图库列表').click();await expect(page.getByRole('button',{name:'查看图片 #100',exact:true})).toBeVisible();expect(c.errors).toEqual([]);
});
test('clipboard denial offers the exact requested raw text as a selectable fallback',async({page})=>{
 const c=await setup(page);await page.addInitScript(()=>Object.defineProperty(navigator.clipboard,'writeText',{value:async()=>{throw Error('denied');},configurable:true}));await page.reload();await open(page);await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();await page.getByRole('button',{name:'复制全部原始 Tag',exact:true}).click();await expect(page.getByLabel('待复制标签')).toHaveValue(post.rawTags);await expect(page.locator('.danbooru-copy-notice')).toContainText('Ctrl+C');expect(c.errors).toEqual([]);
});

for(const skin of ['classic','book-contract','symphonic','elixir','lemmtear'])test(`gallery and added navigation fit ${skin} at 1024 and 390`,async({page})=>{
 const c=await setup(page,{skin});await page.setViewportSize({width:1024,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(1024);
 await open(page);await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();await expect(page.getByLabel('待复制标签')).toBeVisible();await page.screenshot({path:evidence+`/${skin}-detail.png`});await page.getByLabel('关闭功能面板').click();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await expect(page.getByRole('button',{name:'D站图库',exact:true})).toBeVisible();expect(c.errors).toEqual([]);
});

test.beforeEach(async({page})=>{await page.addInitScript(version=>{try{localStorage.setItem('lucifer-share-release-seen-v1',version);localStorage.setItem('lucifer-share-setup-seen-v1','true');}catch{}},RELEASE_NOTES.version);});

for(const mobile of [false,true])test('failed gallery images reload only on explicit action ('+(mobile?'mobile':'desktop')+')',async({page})=>{
 const c=await setup(page);if(mobile)await page.setViewportSize({width:390,height:844});let failed=true,reads=0,originalReads=0;
 await page.route('**/api/danbooru/image?**',r=>{reads++;if(new URL(r.request().url()).searchParams.get('url').includes('/original/'))originalReads++;return failed?r.fulfill({status:502,json:{error:{message:'Danbooru 图片读取超时。'}}}):r.fulfill({contentType:'image/svg+xml',body:SVG});});
 await open(page);await expect(page.locator('.danbooru-grid').getByText('图片暂不可用').first()).toBeVisible();await page.waitForTimeout(150);const before=reads;await page.waitForTimeout(150);expect(reads).toBe(before);
 failed=false;await page.getByRole('button',{name:'重新加载图片',exact:true}).click();await expect(page.getByAltText('Danbooru #100',{exact:true})).toBeVisible();expect(c.calls.filter(x=>x.p==='/api/danbooru/posts')).toHaveLength(1);
 await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();failed=true;await page.getByLabel('放大查看图片 #100').click();const viewer=page.getByRole('dialog',{name:'原图查看 #100'});await expect(viewer.getByRole('alert')).toContainText('读取超时');await page.waitForTimeout(150);expect(originalReads).toBe(1);
 await page.screenshot({path:evidence+'/network-recovery-'+(mobile?'mobile':'desktop')+'.png'});failed=false;await viewer.getByRole('button',{name:'重新加载原图',exact:true}).click();await expect(viewer.getByRole('img',{name:'Danbooru 原图 #100'})).toBeVisible();expect(originalReads).toBe(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(mobile?390:1440);expect(c.errors).toEqual([]);expect(c.calls.some(x=>x.method!=='GET')).toBe(false);
});

test('atlas resource failures identify only the public service and remain explicitly refreshable',async({page})=>{
 const c=await setup(page);let resourceReads=0;
 await page.route('**/api/atlas/frame?**',r=>r.fulfill({contentType:'text/html',body:'<html><body>Atlas fixture<script>parent.postMessage({type:"lucifer-atlas-ready"},"*");setTimeout(()=>parent.postMessage({type:"lucifer-atlas-resource-request",id:"fixture",url:"https://assets.quicktagcloud.com/data/test.json"},"*"),100);</script></body></html>'}));
 await page.route('**/api/atlas/resource?**',r=>{resourceReads++;return r.fulfill({status:502,json:{error:{message:'法典图鉴域名解析失败。请检查网络后手动重试。'}}});});
 await page.getByRole('button',{name:'法典图鉴',exact:true}).click();await expect(page.getByRole('alert')).toContainText('法典图鉴域名解析失败');await expect(page.getByLabel('刷新法典图鉴')).toBeEnabled();await page.waitForTimeout(150);expect(resourceReads).toBe(1);await expect(page.getByTitle('法典图鉴原站')).toHaveAttribute('sandbox','allow-scripts allow-popups allow-popups-to-escape-sandbox allow-downloads');expect(c.errors).toEqual([]);
});

test('custom page numbers reject ambiguous input and preserve the frozen page size',async({page})=>{
 const c=await setup(page,{allPages:true});await page.setViewportSize({width:1500,height:900});await open(page);await expect(page.locator('.danbooru-tile')).toHaveCount(16);
 const lists=()=>c.calls.filter(item=>item.p==='/api/danbooru/posts'),input=page.getByRole('textbox',{name:'跳转页码'});const originalSize=new URL(lists()[0].url).searchParams.get('pageSize');
 for(const value of ['0','1001','10000','1.5','-1','abc','','1e2']){await input.fill(value);await input.press('Enter');await expect(page.getByRole('alert')).toHaveText('请输入 1–1000 之间的整数页码。');expect(lists()).toHaveLength(1);}
 await page.setViewportSize({width:1024,height:700});await input.fill('7');await input.press('Enter');await expect(page.getByRole('button',{name:'查看图片 #700',exact:true})).toBeVisible();expect(new URL(lists().at(-1).url).searchParams.get('pageSize')).toBe(originalSize);await expect(input).toHaveValue('7');
 await input.fill('1000');await page.getByRole('button',{name:'跳转',exact:true}).click();await expect(page.getByRole('button',{name:'查看图片 #100000',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'下一页',exact:true})).toBeDisabled();expect(lists()).toHaveLength(3);expect(c.calls.some(item=>item.method!=='GET')).toBe(false);expect(c.errors).toEqual([]);
});

for(const mobile of [false,true])test('gallery session preserves page, selection, scroll and completed image reads ('+(mobile?'mobile':'desktop')+')',async({page})=>{
 const c=await setup(page,{allPages:true});await page.setViewportSize(mobile?{width:390,height:844}:{width:1024,height:700});await open(page);
 await page.getByLabel('Danbooru 搜索标签').fill('landscape');await page.getByRole('button',{name:'搜索',exact:true}).click();await page.getByLabel('Danbooru 排序').selectOption('score');await page.getByLabel('Danbooru 上传时间').selectOption('week');
 await page.getByLabel('跳转页码').fill('7');await page.getByLabel('跳转页码').press('Enter');await expect(page.getByLabel('图库分页')).toContainText('第 7 页');await page.getByLabel('跳转页码').scrollIntoViewIfNeeded();expect(await page.getByLabel('图库分页').evaluate(node=>node.scrollWidth<=node.clientWidth)).toBe(true);await page.screenshot({path:evidence+'/page-jump-'+(mobile?'mobile':'desktop')+'.png'});await page.getByRole('button',{name:'查看图片 #700',exact:true}).click();await expect(page.getByAltText('预览 #700',{exact:true})).toBeVisible();await page.getByRole('button',{name:'blue sky',exact:true}).click();await page.getByLabel('筛选当前图片标签').fill('tag');
 const dialog=page.getByRole('dialog',{name:'D站图库',exact:true});const scroll=await dialog.evaluate(el=>{window.__galleryDialog=el;window.__gallerySelection=el.querySelector('.danbooru-detail');const nodes=[el,...el.querySelectorAll('[data-danbooru-scroll]')];nodes.forEach(node=>node.scrollTop=120);return nodes.map(node=>node.scrollTop);});
 await page.waitForTimeout(200);const listsBefore=c.calls.filter(item=>item.p==='/api/danbooru/posts').length,imagesBefore=c.requests.filter(url=>url.includes('/api/danbooru/image?'));
 await page.keyboard.press('Escape');await expect(page.locator('.danbooru-dialog')).not.toHaveAttribute('open','');await expect(page.locator('.danbooru-dialog')).toBeHidden();await page.waitForTimeout(200);expect(c.requests.filter(url=>url.includes('/api/danbooru/image?'))).toEqual(imagesBefore);
 await page.evaluate(()=>{const current=Date.now;Date.now=()=>current()+121000;});await open(page);await expect(dialog).toBeVisible();await expect(page.getByLabel('待复制标签')).not.toHaveValue(/blue sky/);await expect(page.getByLabel('Danbooru 搜索标签')).toHaveValue('landscape');await expect(page.getByLabel('Danbooru 排序')).toHaveValue('score');await expect(page.getByLabel('Danbooru 上传时间')).toHaveValue('week');await expect(page.getByLabel('跳转页码')).toHaveValue('7');await expect(page.getByLabel('筛选当前图片标签')).toHaveValue('tag');
 expect(await dialog.evaluate(el=>el===window.__galleryDialog&&el.querySelector('.danbooru-detail')===window.__gallerySelection)).toBe(true);expect(await dialog.evaluate(el=>[el,...el.querySelectorAll('[data-danbooru-scroll]')].map(node=>node.scrollTop))).toEqual(scroll);
 await page.waitForTimeout(200);expect(c.calls.filter(item=>item.p==='/api/danbooru/posts')).toHaveLength(listsBefore);expect(c.requests.filter(url=>url.includes('/api/danbooru/image?'))).toEqual(imagesBefore);await page.screenshot({path:evidence+'/session-preserved-'+(mobile?'mobile':'desktop')+'.png'});
 await page.getByLabel('刷新D站图库').click();await expect.poll(()=>c.calls.filter(item=>item.p==='/api/danbooru/posts').length).toBe(listsBefore+1);const refreshed=new URL(c.calls.filter(item=>item.p==='/api/danbooru/posts').at(-1).url);expect(refreshed.searchParams.get('refresh')).toBe('1');expect(refreshed.searchParams.get('page')).toBe('7');await expect(page.getByLabel('筛选当前图片标签')).toHaveValue('tag');expect(c.errors).toEqual([]);
});

test('closing a gallery cancels active and queued thumbnail reads and never crawls while hidden',async({page})=>{
 const c=await setup(page),held=[],aborted=[];await page.setViewportSize({width:1600,height:1000});page.on('requestfailed',request=>{if(request.url().includes('/api/danbooru/image?'))aborted.push(request.url());});
 await page.route('**/api/danbooru/image?**',route=>{held.push(route);});
 try{await open(page);await expect.poll(()=>held.length).toBe(4);await page.keyboard.press('Escape');await expect.poll(()=>aborted.length).toBe(4);await page.waitForTimeout(200);expect(held).toHaveLength(4);await open(page);await expect.poll(()=>held.length).toBe(8);await page.waitForTimeout(150);expect(held).toHaveLength(8);expect(c.calls.filter(item=>item.p==='/api/danbooru/posts')).toHaveLength(1);expect(c.errors).toEqual([]);}
 finally{for(const route of held)await route.fulfill({contentType:'image/svg+xml',body:SVG}).catch(()=>{});}
});

for(const mobile of [false,true])test(`selected detail survives list paging, empty pages, errors and refresh (${mobile?'mobile':'desktop'})`,async({page})=>{
 const c=await setup(page,{allPages:true,skin:'lemmtear'});if(mobile)await page.setViewportSize({width:390,height:844});
 const reads=[];await page.route('**/api/danbooru/posts?**',r=>{const u=new URL(r.request().url()),n=Number(u.searchParams.get('page'));reads.push(n);if(n===4)return r.fulfill({status:502,json:{error:{message:'分页测试：原站暂不可用'}}});return r.fulfill({json:{posts:n===3||u.searchParams.has('refresh')?[]:[{...post,id:n*100,pageUrl:'https://danbooru.donmai.us/posts/'+n*100}],page:n,hasMore:n<5}});});
 await open(page);await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();const detail=page.getByRole('complementary',{name:'图片详情'}),nav=page.getByRole('navigation',{name:mobile?'详情内图库分页':'图库分页',exact:true});
 await detail.getByRole('button',{name:'blue sky',exact:true}).click();await page.getByLabel('筛选当前图片标签').fill('land');const tags=await page.getByLabel('待复制标签').inputValue();await expect(detail.getByRole('img',{name:'预览 #100'})).toBeVisible();const src=await detail.getByRole('img',{name:'预览 #100'}).getAttribute('src');await detail.evaluate(el=>window.__retainedDetail=el);
 const retained=async()=>{await expect(detail).toBeVisible();await expect(detail.getByRole('img',{name:'预览 #100'})).toHaveAttribute('src',src);await expect(page.getByLabel('待复制标签')).toHaveValue(tags);await expect(page.getByLabel('筛选当前图片标签')).toHaveValue('land');expect(await detail.evaluate(el=>el===window.__retainedDetail)).toBe(true);};
 await nav.getByRole('button',{name:'下一页',exact:true}).click();await expect(nav).toContainText('第 2 页');await expect(nav.getByRole('button',{name:'下一页',exact:true})).toBeEnabled();await retained();
 await nav.getByRole('button',{name:'下一页',exact:true}).click();await expect(nav).toContainText('第 3 页');await expect(nav.getByRole('button',{name:'下一页',exact:true})).toBeEnabled();await retained();
 await nav.getByRole('button',{name:'下一页',exact:true}).click();await expect(nav).toContainText('第 4 页');await expect(mobile?nav:page.getByLabel('Danbooru 图片列表')).toContainText('分页测试：原站暂不可用');await retained();
 await nav.getByRole('button',{name:'上一页',exact:true}).click();await nav.getByRole('button',{name:'上一页',exact:true}).click();await expect(nav).toContainText('第 2 页');await retained();expect(reads.filter(n=>n===2)).toHaveLength(1);
 await page.getByLabel('刷新D站图库').click();await expect.poll(()=>reads.filter(n=>n===2).length).toBe(2);await expect(nav.getByRole('button',{name:'上一页',exact:true})).toBeEnabled();await retained();
 await page.getByRole('button',{name:'复制所选标签',exact:true}).click();expect(await page.evaluate(()=>window.__clipboard)).toBe(tags);
 await detail.evaluate(el=>{el.scrollTop=0;el.scrollIntoView({block:'start'});});
 await mkdir('.local/gallery-detail-20260928/ui',{recursive:true});await page.screenshot({path:`.local/gallery-detail-20260928/ui/retained-${mobile?'mobile':'desktop'}.png`});
 await page.getByLabel('返回图库列表').click();await expect(detail).toHaveCount(0);await expect(page.getByLabel('Danbooru 图片列表')).toBeVisible();
 await page.getByRole('button',{name:'上一页',exact:true}).click();await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();await expect(page.getByLabel('筛选当前图片标签')).toHaveValue('');expect(c.errors).toEqual([]);expect(c.calls.some(x=>x.method!=='GET')).toBe(false);
});

test('page jump preserves selected details; an explicit return cannot be undone by a late response',async({page})=>{
 const c=await setup(page,{allPages:true});await open(page);await page.getByRole('button',{name:'查看图片 #100',exact:true}).click();
 await page.getByLabel('跳转页码').fill('8');await page.getByRole('button',{name:'跳转',exact:true}).click();await expect(page.getByRole('button',{name:'查看图片 #800',exact:true})).toBeVisible();await expect(page.getByRole('complementary',{name:'图片详情'})).toContainText('#100');
 await page.getByRole('button',{name:'查看图片 #800',exact:true}).click();await expect(page.getByRole('complementary',{name:'图片详情'})).toContainText('#800');
 let held;await page.route('**/api/danbooru/posts?**',r=>{held=r;});await page.getByRole('button',{name:'下一页',exact:true}).click();await expect.poll(()=>!!held).toBe(true);await expect(page.getByRole('complementary',{name:'图片详情'})).toContainText('#800');await page.getByLabel('返回图库列表').click();await held.fulfill({json:{posts:[{...post,id:900}],page:9,hasMore:true}});await expect(page.getByRole('button',{name:'查看图片 #900',exact:true})).toBeVisible();await expect(page.getByRole('complementary',{name:'图片详情'})).toHaveCount(0);expect(c.errors).toEqual([]);
});
