import {test,expect} from '@playwright/test';import {defaults} from '../src/lib/request.mjs';import {WORKBENCH_SKINS,APPEARANCE_KEY} from '../src/lib/loading-skins.mjs';import pkg from '../package.json' with {type:'json'};import {mkdir} from 'node:fs/promises';
const PNG='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aV1cAAAAASUVORK5CYII=';
async function setup(page,skin='classic',model='nai-diffusion-5-full'){
 const payloads=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({skin,key,version,state})=>{localStorage.setItem('novelai-studio-v1',JSON.stringify({version:1,state}));localStorage.setItem(key,JSON.stringify({version:1,workbenchSkin:skin,loadingSkin:'classic',motion:'off',characterDecorations:false}));localStorage.setItem('lucifer-share-setup-seen-v1','true');localStorage.setItem('lucifer-share-release-seen-v1',version);localStorage.setItem('lucifer-share-auto-update-check-v1','off');},{skin,key:APPEARANCE_KEY,version:pkg.version,state:{...defaults(model),prompt:'a quiet garden',seed:42}});
 await page.route('**/api/**',r=>{const p=new URL(r.request().url()).pathname;const send=json=>r.fulfill({json});if(p==='/api/status')return send({keyConfigured:true});if(p==='/api/settings')return send({tutorialComplete:true,beginner:false});if(p==='/api/models')return send({data:[{id:model}]});if(p==='/api/anlas')return send({pricingPolicy:'opus',calibrations:[],entries:[]});if(p==='/api/request'&&r.request().method()==='POST'){payloads.push(r.request().postDataJSON().payload);return send({id:'fixture-dimension',images:[{url:PNG}],createdAt:new Date().toISOString()});}return send({entries:[],available:false,active:null});});
 await page.goto('/');const dismiss=page.getByLabel('关闭更新说明',{exact:true});if(await dismiss.isVisible())await dismiss.click();await expect(page.getByLabel('宽度',{exact:true})).toBeVisible();return {payloads,errors};
}
for(const skin of WORKBENCH_SKINS.map(s=>s.id))test(`dimension typing, swap and focused shortcut use snapped values (${skin})`,async({page})=>{
 const c=await setup(page,skin),width=page.getByLabel('宽度',{exact:true}),height=page.getByLabel('高度',{exact:true});await width.fill('');await width.pressSequentially('1000');await expect(width).toHaveValue('1000');expect(c.payloads).toEqual([]);await width.press('Enter');await expect(width).toHaveValue('1024');
 await height.fill('1200');await expect(height).toHaveValue('1200');await height.press('Tab');await expect(height).toHaveValue('1216');await page.getByTitle('交换宽高',{exact:true}).click();await expect(width).toHaveValue('1216');await expect(height).toHaveValue('1024');
 await width.fill('1000');await expect(width).toHaveValue('1000');await width.press('Control+Enter');await expect.poll(()=>c.payloads.length).toBe(1);expect(c.payloads[0].novelai.body.parameters.width).toBe(1024);expect(c.payloads[0].novelai.body.parameters.height).toBe(1024);await expect(width).toHaveValue('1024');expect(c.errors).toEqual([]);
});
for(const model of ['nai-diffusion-5-full','nai-diffusion-4-5-full','nai-diffusion-4-5-curated'])test(`dimensions handle boundaries, empty input, presets and unchanged other numbers (${model})`,async({page})=>{
 const c=await setup(page,'classic',model),width=page.getByLabel('宽度',{exact:true}),height=page.getByLabel('高度',{exact:true});
 for(const [input,value] of [['1055','1024'],['1056','1088'],['0','64'],['-10','64'],['5000','4096'],['1023.5','1024']]){await width.fill(input);await width.press('Tab');await expect(width).toHaveValue(value);}
 await width.fill('');await expect(width).toHaveValue('');await width.press('Tab');await expect(width).toHaveValue('1024');
 await page.getByLabel('尺寸预设',{exact:true}).selectOption('832x1216');await expect(width).toHaveValue('832');await expect(height).toHaveValue('1216');
 await page.getByLabel('生成数量',{exact:true}).fill('3');await page.getByLabel('生成数量',{exact:true}).press('Tab');await expect(page.getByLabel('生成数量',{exact:true})).toHaveValue('3');expect(c.payloads).toEqual([]);expect(c.errors).toEqual([]);
});
test('mobile dimension entry preserves raw typing and restores a bounded aligned value',async({page})=>{
 const c=await setup(page);await page.setViewportSize({width:390,height:844});await page.locator('.mobile-tabs').getByRole('button',{name:'参数',exact:true}).click();const width=page.getByLabel('宽度',{exact:true});await width.fill('1000');await expect(width).toHaveValue('1000');await width.press('Tab');await expect(width).toHaveValue('1024');await width.scrollIntoViewIfNeeded();const w=await width.boundingBox(),swap=await page.getByTitle('交换宽高',{exact:true}).boundingBox();expect(Math.abs(w.y+w.height/2-swap.y-swap.height/2)).toBeLessThan(8);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await mkdir('.local/dimension-snap-20260928/ui',{recursive:true});await page.screenshot({path:'.local/dimension-snap-20260928/ui/mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'.local/dimension-snap-20260928/ui/desktop.png'});expect(c.errors).toEqual([]);expect(c.payloads).toEqual([]);
});

test('click Generate while editing sends snapped width and height',async({page})=>{
 const c=await setup(page),width=page.getByLabel('宽度',{exact:true}),height=page.getByLabel('高度',{exact:true});await width.fill('1000');await height.fill('1200');await expect(height).toHaveValue('1200');await page.locator('.generate').click();await expect.poll(()=>c.payloads.length).toBe(1);expect(c.payloads[0].novelai.body.parameters.width).toBe(1024);expect(c.payloads[0].novelai.body.parameters.height).toBe(1216);await expect(height).toHaveValue('1216');expect(c.errors).toEqual([]);
});
