import {test,expect} from '@playwright/test';import {mkdir} from 'node:fs/promises';import path from 'node:path';
import {defaults} from '../src/lib/request.mjs';import {WORKBENCH_SKINS,APPEARANCE_KEY} from '../src/lib/loading-skins.mjs';import pkg from '../package.json' with {type:'json'};
import {studioFixture} from './fixtures/studio.mjs';
const evidence=process.env.FX_COST_EVIDENCE_DIR||'.local/generate-cost-20260929/ui';
async function setup(page,{skin='classic',policy='opus',state={},comparison={}}={}){
 let cleanup;const f=await studioFixture({after:fn=>cleanup=fn},{distDir:process.env.FX_TEST_DIST_DIR||path.resolve('.local/generate-cost-20260929/dist')});await f.request('/api/anlas',{action:'pricingPolicy',value:policy});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(({skin,key,version,state,comparison})=>{localStorage.setItem('lucifer-share-auto-update-check-v1','off');localStorage.setItem('lucifer-share-release-seen-v1',version);localStorage.setItem('lucifer-share-setup-seen-v1','true');localStorage.setItem('novelai-studio-v1',JSON.stringify({version:1,state}));localStorage.setItem('lucifer-comparisons-v1',JSON.stringify(comparison));localStorage.setItem(key,JSON.stringify({version:1,workbenchSkin:skin,loadingSkin:'classic',characterDecorations:true}));},{skin,key:APPEARANCE_KEY,version:pkg.version,state:{...defaults(),prompt:'fixture garden',seed:42,width:1024,height:1024,steps:28,...state},comparison});
 await page.goto(f.base);await expect(page.getByLabel('正面提示词',{exact:true})).toBeEditable();await expect(page.locator('.generation-cost-badge')).toBeVisible();await mkdir(evidence,{recursive:true});return {f,errors,cleanup};
}
async function badgeFits(page){const button=await page.locator('.generate').boundingBox(),cost=await page.locator('.generation-cost-badge').boundingBox(),label=await page.locator('.generate-label').boundingBox();expect(cost.x).toBeGreaterThanOrEqual(button.x);expect(cost.x+cost.width).toBeLessThanOrEqual(button.x+button.width+1);expect(cost.y).toBeGreaterThanOrEqual(button.y);expect(cost.y+cost.height).toBeLessThanOrEqual(button.y+button.height+1);expect(label.x+label.width).toBeLessThanOrEqual(cost.x+1);}
for(const skin of WORKBENCH_SKINS.map(s=>s.id))test(`button shows zero and paid size cost without a dimension panel (${skin})`,async({page})=>{
 const c=await setup(page,{skin});try{const cost=page.locator('.generation-cost-badge');await expect(cost).toHaveText('0');await expect(page.locator('.dimension-cost-hint')).toHaveCount(0);await expect(page.locator('.generate')).toHaveAccessibleDescription(/预计消耗 0 Anlas/);await badgeFits(page);
  await page.getByLabel('宽度',{exact:true}).fill('1536');await expect(cost).toHaveText('45');await badgeFits(page);await page.screenshot({path:evidence+`/${skin}-paid.png`});
  await page.getByLabel('宽度',{exact:true}).fill('1024');await expect(cost).toHaveText('0');await page.setViewportSize({width:390,height:844});await page.locator('.mobile-tabs').getByRole('button',{name:'提示词',exact:true}).click();await page.locator('.generate').scrollIntoViewIfNeeded();await expect(cost).toHaveText('0');await badgeFits(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:evidence+`/${skin}-mobile.png`});expect(c.errors).toEqual([]);
 }finally{await c.cleanup();}
});
test('normal multiple images and serial Opus mode show the full click cost',async({page})=>{
 const c=await setup(page);try{const cost=page.locator('.generation-cost-badge');await page.getByLabel('生成数量',{exact:true}).fill('3');await expect(cost).toHaveText('60');await page.getByRole('checkbox',{name:'Opus 0 Anlas 模式',exact:false}).check();await expect(cost).toHaveText('0');await page.getByLabel('宽度',{exact:true}).fill('1536');await expect(cost).toHaveText('—');expect(c.errors).toEqual([]);}finally{await c.cleanup();}
});
test('paid policy and unknown V4.5 amounts cannot be rendered as zero',async({page})=>{
 const c=await setup(page,{policy:'paid'});try{const cost=page.locator('.generation-cost-badge');await expect(cost).toHaveText('30');await page.getByRole('combobox',{name:'图像模型',exact:true}).selectOption('nai-diffusion-4-5-full');await expect(cost).toHaveText('—');await expect(cost).toHaveAttribute('title',/不代表 0/);expect(c.errors).toEqual([]);}finally{await c.cleanup();}
});
for(const model of ['nai-diffusion-5-full','nai-diffusion-4-5-full'])test(`comparison badge follows real single-image variants and rounds (${model})`,async({page})=>{
 const c=await setup(page,{state:{...defaults(model),prompt:'test garden',seed:42,width:1024,height:1024,steps:28,n:3,overrides:{n_samples:4},extraJSON:'{"n_samples":2}'},comparison:{mode:'ABC',overrides:{B:{},C:{}}}});try{const cost=page.locator('.generation-cost-badge');await page.getByRole('checkbox',{name:'开启 A/B/C 对照',exact:false}).check();await page.getByLabel('对照轮数',{exact:true}).fill('2');await expect(cost).toHaveText('0');await page.getByLabel('宽度',{exact:true}).fill('1536');await expect(cost).toHaveText(model==='nai-diffusion-5-full'?'270':'—');expect(c.errors).toEqual([]);}finally{await c.cleanup();}
});
test('a running task shows pending cost instead of relabeling it with newly edited parameters',async({page})=>{
 const c=await setup(page);let held;try{await page.route('**/api/generation-jobs',route=>{held=route;});await page.locator('.generate').click();await expect.poll(()=>!!held).toBe(true);await expect(page.locator('.generation-cost-badge')).toHaveText('…');await page.getByLabel('宽度',{exact:true}).fill('1536');await expect(page.locator('.generation-cost-badge')).toHaveText('…');await held.fulfill({status:409,json:{error:{message:'fixture rejected without an upstream request'}}});held=null;await expect(page.locator('.generation-cost-badge')).toHaveText('45');expect(c.errors).toEqual([]);}finally{if(held)await held.abort();await c.cleanup();}
});
