import {test,expect} from '@playwright/test';
import {PNG} from 'pngjs';
import {defaults} from '../src/lib/request.mjs';
const png=new PNG({width:832,height:1216});for(let i=0;i<png.data.length;i+=4){png.data[i]=55;png.data[i+1]=100;png.data[i+2]=125;png.data[i+3]=255;}const image='data:image/png;base64,'+PNG.sync.write(png).toString('base64');
const entry=i=>({id:'viewer-'+i,status:'success',createdAt:new Date(1791100000000-i*60000).toISOString(),prompt:'Preview '+i,durationMs:10700,images:[{url:image+'#'+i,width:832,height:1216}]});
async function setup(page,skin='classic',mobile=false){
 const writes=[],errors=[];let fail=false;
 await page.addInitScript(({state,skin})=>{localStorage.setItem('novelai-studio-v1',JSON.stringify({version:1,state}));localStorage.setItem('lucifer-inspector-tab-v1','history');localStorage.setItem('lucifer-tag-suggestions-v1','off');localStorage.setItem('lucifer-share-release-seen-v1','1.13.0');localStorage.setItem('lucifer-share-setup-seen-v1','true');localStorage.setItem('lucifer-fx-appearance-v1',JSON.stringify({version:1,workbenchSkin:skin,loadingSkin:'classic',motion:'off',characterIcons:true}));},{state:{...defaults(),prompt:'A landscape preview'},skin});
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',r=>{const req=r.request(),u=new URL(req.url()),p=u.pathname;const send=v=>r.fulfill({json:v});if(req.method()!=='GET')writes.push(p);if(p==='/api/status')return send({keyConfigured:true});if(p==='/api/settings')return send({tutorialComplete:true,beginner:false});if(p==='/api/models')return send({data:[{id:'nai-diffusion-5-full'}]});if(p==='/api/history')return fail?r.fulfill({status:503,json:{error:{message:'fixture unavailable'}}}):send({entries:u.searchParams.has('before')?[entry(30)]:Array.from({length:30},(_,i)=>entry(i)),nextCursor:u.searchParams.has('before')?null:'older'});return send({entries:[],categories:[],active:null,pricingPolicy:'opus',calibrations:[],phase:'idle'});});
 await page.goto('/');await expect(page.locator('.history-item')).toHaveCount(30);if(mobile)await page.locator('.mobile-tabs').getByRole('button',{name:'历史',exact:true}).click();await page.locator('.history-item').first().click();await expect(page.getByAltText('生成结果 1')).toBeVisible();return{errors,writes,fail:()=>fail=true};
}
const scale=page=>page.getByLabel('图片缩放比例');
for(const skin of ['classic','book-contract','precure-scrapbook','exstia-magica'])test('focus preserves editor and panels; duration uses header: '+skin,async({page})=>{
 await page.setViewportSize({width:1366,height:768});const f=await setup(page,skin);const before=await page.locator('.canvas').boundingBox();await page.getByLabel('正面提示词',{exact:true}).fill('Preserve this editor draft');const editor=await page.getByLabel('正面提示词',{exact:true}).elementHandle();const left=await page.locator('.left-panel').boundingBox();
 await expect(page.locator('.canvas-toolbar .generation-duration')).toHaveText('生成 10.7s');await expect(page.locator('.result-actions small')).toHaveCount(0);
 await page.getByRole('button',{name:'专注看图',exact:true}).click();await expect(page.locator('.left-panel')).toBeHidden();await expect(page.locator('.right-panel')).toBeHidden();const focused=await page.locator('.canvas').boundingBox();expect(focused.width).toBeGreaterThan(before.width+400);expect(focused.height).toBeGreaterThan(before.height);
 await page.keyboard.press('Escape');await expect(page.locator('.left-panel')).toBeVisible();expect(await editor.evaluate(e=>e.isConnected)).toBe(true);await expect(page.getByLabel('正面提示词',{exact:true})).toHaveValue('Preserve this editor draft');expect((await page.locator('.left-panel').boundingBox()).width).toBeCloseTo(left.width,0);expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);
});
test('natural size, pan, wheel anchor, doubleclick fit and new image reset',async({page})=>{
 await setup(page);await page.getByRole('button',{name:'1:1',exact:true}).click();await expect(scale(page)).toHaveText('100%');const img=page.getByAltText('生成结果 1');expect((await img.boundingBox()).height).toBe(1216);const viewport=await page.getByRole('region',{name:'图片查看器',exact:true}).boundingBox(),cx=viewport.x+viewport.width/2,cy=viewport.y+viewport.height/2;const before=await img.boundingBox();await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx,cy+100);await page.mouse.up();expect((await img.boundingBox()).y-before.y).toBeCloseTo(100,0);
 await page.getByRole('button',{name:'放大',exact:true}).click();const pre=await img.boundingBox(),anchor={x:cx+40,y:cy-25};await page.mouse.move(anchor.x,anchor.y);await page.mouse.wheel(0,-100);await expect(scale(page)).not.toHaveText('125%');const after=await img.boundingBox();expect((anchor.x-pre.x)/pre.width).toBeCloseTo((anchor.x-after.x)/after.width,2);expect((anchor.y-pre.y)/pre.height).toBeCloseTo((anchor.y-after.y)/after.height,2);
 await page.getByRole('region',{name:'图片查看器',exact:true}).dblclick();expect((await img.boundingBox()).height).toBeLessThan(viewport.height);await page.getByRole('button',{name:'1:1',exact:true}).click();await page.locator('.history-item').nth(1).click();await expect(scale(page)).not.toHaveText('100%');
});
test('history paging, scroll retention and failures preserve selection',async({page})=>{
 const f=await setup(page),strip=page.locator('.history-strip');await strip.evaluate(e=>e.scrollTop=400);const top=await strip.evaluate(e=>e.scrollTop);await page.getByRole('tab',{name:'参数',exact:true}).click();await page.getByRole('tab',{name:'历史',exact:true}).click();expect(await strip.evaluate(e=>e.scrollTop)).toBe(top);await page.getByRole('button',{name:'加载更早记录',exact:true}).click();await expect(page.locator('.history-item')).toHaveCount(31);f.fail();await page.getByRole('button',{name:'刷新历史记录',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'fixture unavailable'})).toBeVisible();await expect(page.getByAltText('生成结果 1')).toBeVisible();await expect(page.locator('.history-item.selected')).toHaveCount(1);expect(f.writes).toEqual([]);
});
test('mobile opens result from history and can leave focus without overflow',async({page})=>{
 await page.setViewportSize({width:390,height:844});const f=await setup(page,'classic',true);await expect(page.getByAltText('生成结果 1')).toBeVisible();await page.getByRole('button',{name:'专注看图',exact:true}).click();await expect(page.getByRole('button',{name:'退出专注 · Esc'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await page.getByRole('button',{name:'退出专注 · Esc'}).click();await expect(page.locator('.mobile-tabs')).toBeVisible();expect(f.errors).toEqual([]);
});
