import {test,expect} from '@playwright/test';
import {PNG} from 'pngjs';
import {defaults} from '../src/lib/request.mjs';
import {RELEASE_NOTES} from '../src/lib/release-notes.mjs';
const png=new PNG({width:832,height:1216});for(let i=0;i<png.data.length;i+=4){png.data[i]=55;png.data[i+1]=100;png.data[i+2]=125;png.data[i+3]=255;}const image='data:image/png;base64,'+PNG.sync.write(png).toString('base64');
for(const skin of ['classic','book-contract','precure-scrapbook','exstia-magica'])test('native image context menu and drag survive right-side history: '+skin,async({page})=>{
 const errors=[],writes=[];await page.addInitScript(({state,skin,version})=>{localStorage.setItem('novelai-studio-v1',JSON.stringify({version:1,state}));localStorage.setItem('lucifer-inspector-tab-v1','history');localStorage.setItem('lucifer-tag-suggestions-v1','off');localStorage.setItem('lucifer-share-release-seen-v1',version);localStorage.setItem('lucifer-share-setup-seen-v1','true');localStorage.setItem('lucifer-fx-appearance-v1',JSON.stringify({version:1,workbenchSkin:skin,loadingSkin:'classic',motion:'off',characterIcons:true}));},{state:{...defaults(),prompt:'Preview garden'},skin,version:RELEASE_NOTES.version});
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',r=>{const p=new URL(r.request().url()).pathname,send=v=>r.fulfill({json:v});if(r.request().method()!=='GET')writes.push(p);if(p==='/api/status')return send({keyConfigured:true});if(p==='/api/settings')return send({tutorialComplete:true,beginner:false});if(p==='/api/models')return send({data:[{id:'nai-diffusion-5-full'}]});if(p==='/api/history')return send({entries:[{id:'native-fixture',status:'success',createdAt:new Date().toISOString(),prompt:'garden',images:[{url:image}]}]});return send({entries:[],categories:[],active:null,pricingPolicy:'opus',calibrations:[],phase:'idle'});});
 await page.goto('/');await page.locator('.history-item').click();const img=page.getByAltText('生成结果 1');await expect(img).toBeVisible();await expect(page.getByRole('button',{name:'专注看图',exact:true})).toHaveCount(1);await expect(page.locator('.image-gesture-note')).toHaveCount(0);expect(await img.evaluate(e=>e.draggable)).toBe(true);expect(await img.evaluate(e=>getComputedStyle(e).pointerEvents)).not.toBe('none');
 await page.evaluate(()=>{document.addEventListener('contextmenu',e=>queueMicrotask(()=>window.nativeMenu={tag:e.target.tagName,prevented:e.defaultPrevented}));document.addEventListener('dragstart',e=>queueMicrotask(()=>window.nativeDrag={tag:e.target.tagName,prevented:e.defaultPrevented,types:Array.from(e.dataTransfer.types)}));});await img.click({button:'right'});expect(await page.evaluate(()=>window.nativeMenu)).toEqual({tag:'IMG',prevented:false});await page.keyboard.press('Escape');await img.dragTo(page.getByLabel('正面提示词',{exact:true}));const d=await page.evaluate(()=>window.nativeDrag);expect(d.tag).toBe('IMG');expect(d.prevented).toBe(false);expect(d.types.length).toBeGreaterThan(0);await expect(page.locator('.right-panel .history-sidebar')).toBeVisible();await expect(page.locator('.canvas-column .history-panel')).toHaveCount(0);expect(writes).toEqual([]);expect(errors).toEqual([]);
});
