import {test,expect} from '@playwright/test';import pkg from '../package.json' with {type:'json'};import {mkdir} from 'node:fs/promises';
for(const mobile of [false,true])test(`output save switch persists with explicit cache notice (${mobile?'mobile':'desktop'})`,async({page})=>{
 const share=pkg.name.endsWith('-share'),errors=[],writes=[];let config={platform:'windows',tutorialComplete:true,beginner:false,provider:'official',autoSaveOutput:true,outputDirectory:'C:\\FX\\output',saveDirectory:'C:\\FX\\saved'};page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(version=>{localStorage.setItem('lucifer-share-release-seen-v1',version);localStorage.setItem('lucifer-share-setup-seen-v1','true');localStorage.setItem('lucifer-share-auto-update-check-v1','off');},pkg.version);
 await page.route('**/api/**',route=>{const r=route.request(),p=new URL(r.url()).pathname,send=json=>route.fulfill({json});if(r.method()!=='GET')writes.push({path:p,body:r.postDataJSON()});if(p==='/api/status')return send({...config,keyConfigured:true});if(p==='/api/settings'||p==='/api/storage'){if(r.method()==='POST')config={...config,...r.postDataJSON()};return send(config);}if(p==='/api/models')return send({data:[{id:'nai-diffusion-5-full'}]});if(p==='/api/anlas')return send({pricingPolicy:'opus',calibrations:[],entries:[]});return send({entries:[],active:null,available:false,models:[],sessions:[],packs:[]});});
 if(mobile)await page.setViewportSize({width:390,height:844});await page.goto('/');const dismiss=page.getByLabel('关闭更新说明',{exact:true});if(await dismiss.isVisible())await dismiss.click();
 const open=async()=>{await page.getByRole('button',{name:share?'应用设置':'保存位置设置',exact:true}).click();if(share)await page.getByRole('tab',{name:'保存位置',exact:true}).click();};await open();const toggle=page.getByRole('checkbox',{name:'自动保存生成图片到 output',exact:true});await expect(toggle).toBeChecked();await expect(page.getByText(/图片仍保留在应用内部历史缓存中/)).toBeVisible();await toggle.uncheck();await page.getByRole('button',{name:'检查目录并保存',exact:true}).click();await expect.poll(()=>config.autoSaveOutput).toBe(false);expect(writes.at(-1).body.autoSaveOutput).toBe(false);
 await page.getByLabel('关闭功能面板',{exact:true}).click();await expect(page.locator('.statusbar')).toContainText('自动输出已关闭');await open();await expect(toggle).not.toBeChecked();await toggle.scrollIntoViewIfNeeded();const dialog=page.getByRole('dialog').filter({hasText:'图片保存位置'});expect(await dialog.evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);await mkdir('.local/output-toggle-20260928/ui',{recursive:true});await page.screenshot({path:`.local/output-toggle-20260928/ui/${mobile?'mobile':'desktop'}.png`});await page.getByLabel('关闭功能面板',{exact:true}).click();await page.reload();await open();await expect(toggle).not.toBeChecked();await toggle.check();await page.getByRole('button',{name:'检查目录并保存',exact:true}).click();await expect.poll(()=>config.autoSaveOutput).toBe(true);expect(writes.every(w=>['/api/settings','/api/storage'].includes(w.path))).toBe(true);expect(errors).toEqual([]);
});
