import {test,expect} from '@playwright/test';import{defaults}from'../src/lib/request.mjs';import{APPEARANCE_KEY,WORKBENCH_SKINS}from'../src/lib/loading-skins.mjs';import pkg from'../package.json'with{type:'json'};import{mkdir}from'node:fs/promises';
const roles=[{id:'alice',enabled:true,prompt:'Alice in a garden',negative:'hat',x:.5,y:.5},{id:'bob',enabled:true,prompt:'Bob in a garden',negative:'coat',x:.5,y:.5}];
async function setup(page,skin='classic',mode='merged'){
 const errors=[],payloads=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(({skin,mode,state,version})=>{if(!localStorage.getItem('novelai-studio-v1'))localStorage.setItem('novelai-studio-v1',JSON.stringify({version:1,state}));if(!localStorage.getItem('lucifer-prompt-layout-v1'))localStorage.setItem('lucifer-prompt-layout-v1',JSON.stringify({version:1,mode}));localStorage.setItem('lucifer-fx-appearance-v1',JSON.stringify({version:1,workbenchSkin:skin,loadingSkin:'classic',motion:'off'}));localStorage.setItem('lucifer-tag-suggestions-v1','off');localStorage.setItem('lucifer-share-release-seen-v1',version);localStorage.setItem('lucifer-share-auto-update-check-v1','off');localStorage.setItem('lucifer-share-setup-seen-v1','true');},{skin,mode,version:pkg.version,state:{...defaults(),prompt:'quiet garden',negative:'blur',seed:42,characters:roles}});
 await page.route('**/api/**',r=>{const p=new URL(r.request().url()).pathname;let json=p==='/api/status'?{keyConfigured:true}:p==='/api/settings'?{tutorialComplete:true,beginner:false}:{entries:[],models:[],active:null,available:false};if(p==='/api/request'&&r.request().method()==='POST'){payloads.push(r.request().postDataJSON().payload);json={id:'fixture-fold',images:[],createdAt:new Date().toISOString()};}return r.fulfill({json});});await page.goto('/');const dismiss=page.getByLabel('关闭更新说明');if(await dismiss.isVisible())await dismiss.click();await expect(page.getByLabel('正面提示词',{exact:true})).toBeVisible();return{errors,payloads};
}
for(const mobile of [false,true])test(`negative fields fold independently without losing text, cards, undo or payload (${mobile?'mobile':'desktop'})`,async({page})=>{
 const ctx=await setup(page,'precure-days');if(mobile)await page.setViewportSize({width:390,height:844});const main=page.getByLabel('负面提示词',{exact:true}),alice=page.getByLabel('角色 1 负面提示词',{exact:true});await main.fill('blur');await main.press('End');await main.press('X');await main.evaluate(el=>el.setSelectionRange(1,3));await page.evaluate(()=>{window.foldNodes=[document.getElementById('negative'),...document.querySelectorAll('textarea[data-prompt-field]')];});
 await page.getByRole('button',{name:'主负面 Undesired Content',exact:true}).click();await expect(main).toBeHidden();await expect(page.getByRole('region',{name:'本次负面卡片',exact:true})).toBeHidden();await expect(page.getByLabel('正面提示词',{exact:true})).toBeVisible();await page.getByRole('button',{name:'角色 1 负面折叠',exact:true}).click();await expect(alice).toBeHidden();await expect(page.getByRole('region',{name:'角色 1 负面卡片',exact:true})).toBeHidden();await expect(page.getByLabel('角色 1 正面提示词',{exact:true})).toBeVisible();await expect(page.getByLabel('角色 2 负面提示词',{exact:true})).toBeVisible();await expect(page.getByLabel('启用角色 1',{exact:true})).toBeChecked();
 await page.getByRole('button',{name:'主负面 Undesired Content',exact:true}).click();expect(await main.evaluate(el=>[el.selectionStart,el.selectionEnd])).toEqual([1,3]);await main.focus();await main.press('Control+z');await expect(main).toHaveValue('blur');await page.getByRole('button',{name:'主负面 Undesired Content',exact:true}).click();expect(await page.evaluate(()=>window.foldNodes.every(el=>el.isConnected))).toBe(true);
 await page.locator('.generate').click();await expect.poll(()=>ctx.payloads.length).toBe(1);const p=ctx.payloads[0].novelai.body.parameters;expect(p.negative_prompt).toContain('blur');expect(p.v4_negative_prompt.caption.char_captions.map(c=>c.char_caption)).toEqual(['hat','coat']);
 await page.reload();await expect(main).toBeHidden();await expect(alice).toBeHidden();await expect(page.getByRole('button',{name:'主负面 Undesired Content',exact:true})).toHaveAttribute('aria-expanded','false');await page.getByTitle('移除角色 1',{exact:true}).click();await expect(page.getByLabel('角色 1 负面提示词',{exact:true})).toHaveValue('coat');await expect(page.getByLabel('角色 1 负面提示词',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'图像工具 / API',exact:true}).click();await page.getByRole('button',{name:'工作区布局',exact:true}).click();await page.getByRole('radio',{name:/经典标签布局/}).check();await page.getByRole('button',{name:'创作',exact:true}).click();await page.getByRole('tab',{name:'负面 Undesired Content',exact:true}).click();await expect(main).toBeVisible();await expect(main).toHaveValue('blur');expect(ctx.errors).toEqual([]);
});
for(const skin of WORKBENCH_SKINS.map(s=>s.id))for(const mode of ['classic','merged'])test(`stable desktop dock and common main height: ${skin} / ${mode}`,async({page})=>{
 await page.setViewportSize({width:1440,height:900});const ctx=await setup(page,skin,mode),main=page.getByLabel('正面提示词',{exact:true});expect(await main.evaluate(el=>el.getBoundingClientRect().height)).toBe(220);const button=page.locator('.generate');await expect(button).toBeInViewport();const before=await button.boundingBox();
 if(mode==='classic')await page.getByRole('tab',{name:/^角色/}).click();const input=page.getByLabel('角色 1 正面提示词',{exact:true});await input.focus();await page.evaluate(()=>{window.realEditor=document.querySelector('textarea[data-prompt-field^="character:"]');window.heightResets=0;window.liveHeightObserver=new MutationObserver(records=>{for(const record of records)if(/height:\s*0px/.test(record.oldValue||''))window.heightResets++;});window.liveHeightObserver.observe(window.realEditor,{attributes:true,attributeFilter:['style'],attributeOldValue:true});});
 const long=Array.from({length:45},(_,i)=>`flower ${i}, quiet garden, blue sky`).join('\n');for(const text of [long,'short',long,'short']){await input.fill(text);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await expect(button).toBeInViewport();expect(Math.abs((await button.boundingBox()).y-before.y)).toBeLessThan(1);}
 expect(await page.evaluate(()=>window.heightResets)).toBe(0);await page.evaluate(()=>window.liveHeightObserver.disconnect());expect(await input.evaluate(el=>el.getBoundingClientRect().height)).toBeLessThan(180);
 await page.setViewportSize({width:1440,height:768});await expect(button).toBeInViewport();const short=await button.boundingBox();await input.fill(long);await expect(button).toBeInViewport();expect(Math.abs((await button.boundingBox()).y-short.y)).toBeLessThan(1);
 if(skin==='precure-days'&&mode==='merged'){await page.getByRole('button',{name:'角色 1 负面折叠',exact:true}).click();await mkdir('.local/prompt-stability-20260928/ui',{recursive:true});await page.screenshot({path:'.local/prompt-stability-20260928/ui/fixed-dock-short.png'});}
 expect(ctx.errors).toEqual([]);expect(ctx.payloads).toEqual([]);
});
