import {RELEASE_NOTES} from '../src/lib/release-notes.mjs';
import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
test('first launch configuration and tutorial do not require a key or generate anything',async({page})=>{
 await page.request.post('/api/settings',{data:{tutorialComplete:false,beginner:true}});
 const writes=[];page.on('request',r=>{if(r.method()==='POST')writes.push(new URL(r.url()).pathname);});await page.goto('/');await expect(page.getByRole('dialog')).toContainText('连接你自己的 NovelAI 服务');await expect(page.getByLabel('API Token / Key',{exact:true})).toHaveValue('');await page.getByRole('tab',{name:'新手教程',exact:true}).click();await expect(page.getByText('从第一张图开始',{exact:true})).toBeVisible();await page.getByRole('button',{name:'我知道了，进入工作台',exact:true}).click();await expect(page.locator('.generate')).toBeDisabled();expect(writes.every(p=>p==='/api/settings')).toBe(true);await expect(page.getByText('召唤 Grok',{exact:true})).toHaveCount(0);await expect(page.getByText('ComfyUI 放大',{exact:true})).toHaveCount(0);
});
test('glossary and personal edits do not rewrite prompt weights; external translation is explicit',async({page,context})=>{
 await context.grantPermissions(['clipboard-write','clipboard-read']);await page.addInitScript(()=>localStorage.setItem('lucifer-share-setup-seen-v1','true'));await page.goto('/');const prompt=page.getByLabel('正面提示词',{exact:true});await prompt.fill('1.2::long hair::, blue eyes, artist:example');await page.getByLabel('中文释义与翻译',{exact:true}).click();await expect(page.getByRole('dialog')).toContainText('长发');await expect(page.getByRole('dialog')).toContainText('蓝眼睛');await page.getByLabel('词条英文',{exact:true}).fill('artist:example');await page.getByLabel('词条中文',{exact:true}).fill('个人示例画师');await page.getByRole('button',{name:'保存释义',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('个人示例画师');await page.getByRole('dialog').getByRole('button',{name:'关闭功能面板',exact:true}).click();await expect(prompt).toHaveValue('1.2::long hair::, blue eyes, artist:example');
});
test('five themes and narrow windows keep public navigation and settings usable',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('lucifer-share-setup-seen-v1','true'));await mkdir('.local/screens',{recursive:true});
 for(const skin of ['classic','book-contract','symphonic','elixir','lemmtear']){await page.goto('/');await page.evaluate(skin=>localStorage.setItem('lucifer-fx-appearance-v1',JSON.stringify({version:1,workbenchSkin:skin,loadingSkin:'classic',motion:'reduced',characterDecorations:true})),skin);await page.reload();for(const width of [1440,1024,390]){await page.setViewportSize({width,height:width===390?844:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);await page.getByLabel('应用设置',{exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('tab',{name:'保存位置',exact:true}).click();await expect(page.getByLabel('自动输出目录',{exact:true})).toBeVisible();expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:`.local/screens/${skin}-${width}.png`});await page.getByRole('dialog').getByRole('button',{name:'关闭功能面板',exact:true}).click();}}expect(errors).toEqual([]);
});

// These established flows exercise the workbench after the version notice is read.
test.beforeEach(async({page})=>{await page.addInitScript(version=>{try{localStorage.setItem('lucifer-share-release-seen-v1',version);}catch{}},RELEASE_NOTES.version);});
