import {PNG as PNGCodec} from 'pngjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,readdir} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {zipSync} from 'fflate';
import {createStudioServer} from '../server/index.mjs';
import {createConfiguration,mapProviderRequest,createWindowsVault} from '../server/configuration.mjs';
import {defaults,buildRequest} from '../src/lib/request.mjs';
import {summarizeUsage} from '../src/lib/opus-usage.mjs';
import {stripImageMetadata} from '../server/image-privacy.mjs';
import {withStudioMetadata} from '../server/png-metadata.mjs';
const PNG=PNGCodec.sync.write({width:1,height:1,data:Buffer.from([120,180,220,255])});
const fixtureVault={seal:async key=>Buffer.from(key).toString('base64'),open:async value=>Buffer.from(value,'base64').toString()};
async function folder(t,{deferCleanup=false}={}){const dir=await mkdtemp(path.join(os.tmpdir(),'fx-share-'));if(!deferCleanup)t.after(()=>rm(dir,{recursive:true,force:true}));return dir;}
async function context(t){const dir=await folder(t,{deferCleanup:true}),calls=[];const server=createStudioServer({root:dir,dataDir:path.join(dir,'userdata'),vault:fixtureVault,fetchImpl:async(url,init)=>{calls.push({url:String(url),method:init.method,payload:init.body?JSON.parse(init.body):null});if(init.method==='GET')return Response.json(String(url).endsWith('/v1/models')?{data:[{id:'nai-diffusion-5-full'}]}:{active:true,tier:3,usage:{percent:67,isNegative:false,timeUntilNextPercent:6000}});return new Response(zipSync({'image_0.png':PNG}),{headers:{'Content-Type':'application/zip'}});}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});});const base='http://127.0.0.1:'+server.address().port;return {dir,calls,base,get:async(route)=>{const r=await fetch(base+route);return {status:r.status,data:await r.json()};},post:async(route,body)=>{const r=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};}};}
async function done(ctx,id){for(let i=0;i<300;i++){const {data}=await ctx.get('/api/generation-jobs/'+id);if(!['queued','running','stopping'].includes(data.status))return data;await new Promise(r=>setTimeout(r,10));}throw Error('Local fixture job did not finish');}
test('fresh share starts without credentials, personal paths or upstream calls and does not expose removed routes',async t=>{const c=await context(t),s=await c.get('/api/status');assert.equal(s.data.keyConfigured,false);assert.equal(s.data.shareEdition,true);assert.ok(s.data.outputDirectory.startsWith(c.dir));assert.equal(c.calls.length,0);await c.get('/api/models');assert.equal(c.calls.length,0);assert.equal((await c.get('/api/assistant/status')).status,404);assert.equal((await c.get('/api/comfy/status')).status,404);});
test('official and gateway profiles map full native bodies without credential leakage or destination reuse',async t=>{const dir=await folder(t),cfg=createConfiguration({root:dir,directory:dir,vault:fixtureVault});const key='fixture-only-not-real';const config=await cfg.update({provider:'official',key});assert.equal(config.secret,undefined);assert.equal(config.keyConfigured,true);assert.equal((await cfg.export()).key,undefined);assert.equal(await cfg.key(),key);await cfg.update({provider:'openai',baseURL:'https://gateway.example/v1'});await assert.rejects(cfg.key());const p=buildRequest({...defaults(),prompt:'lake',seed:1});assert.deepEqual(mapProviderRequest({provider:'official'},'/v1/images/generations',p).body,p.novelai.body);assert.equal(mapProviderRequest({provider:'openai',baseURL:'https://gateway.example/v1'},'/v1/images/generations',p).url.href,'https://gateway.example/v1/images/generations');await assert.rejects(cfg.update({provider:'native',baseURL:'https://a.example?key=unsafe'}));});
test('connection check is GET-only and official quota readback is separated from local estimates',async t=>{const c=await context(t);await c.post('/api/settings',{provider:'official',key:'fixture-only'});const check=await c.post('/api/connection/check',{});assert.equal(check.status,200,JSON.stringify(check.data));assert.equal(c.calls.length,1);assert.equal(c.calls[0].method,'GET');assert.equal(c.calls[0].url,'https://image.novelai.net/user/subscription');const quota=await c.get('/api/opus?timeZone=Asia%2FShanghai');assert.equal(quota.data.account.usage.percent,67);assert.equal(quota.data.summary.dailyRecoveryPercent,14.4);assert.equal(quota.data.summary.accountWide,false);});
test('changing storage preserves old image access and share export strips metadata without changing image data',async t=>{const c=await context(t);await c.post('/api/settings',{key:'fixture-only'});const id=randomUUID(),payload=buildRequest({...defaults(),prompt:'lake',seed:42});const start=await c.post('/api/generation-jobs',{clientRequestId:id,payload});assert.equal(start.status,202,JSON.stringify(start.data));const job=await done(c,id);assert.equal(job.status,'success',JSON.stringify(job));const image=job.result.images[0];await c.post('/api/settings',{outputDirectory:path.join(c.dir,'new-output'),saveDirectory:path.join(c.dir,'new-saved')});const read=await fetch(c.base+image.url);assert.equal(read.status,200);const clean=await fetch(c.base+'/api/share-image?id='+job.result.id+'&index=0&metadata=strip');assert.equal(clean.status,200);const bytes=Buffer.from(await clean.arrayBuffer());assert.ok(!bytes.includes(Buffer.from('novelai_studio')));assert.ok(bytes.includes(PNG.subarray(41,60)));const save=await c.post('/api/save-result',{id:job.result.id,index:0});assert.equal(save.status,200,JSON.stringify(save.data));assert.equal(path.dirname(save.data.image.savedPath),path.join(c.dir,'new-saved'));});
test('today totals use the selected timezone, do not duplicate receipts and preserve uncertain consumption',()=>{const entries=[{id:'a',createdAt:'2026-09-21T17:00:00Z',status:'success',opusPercent:.5},{id:'a',createdAt:'2026-09-21T17:00:00Z',status:'success',opusPercent:.5},{id:'b',createdAt:'2026-09-21T18:00:00Z',status:'error',billingUnknown:true}];const cn=summarizeUsage(entries,{now:new Date('2026-09-22T01:00:00Z'),timeZone:'Asia/Shanghai',usage:{timeUntilNextPercent:6000}});assert.equal(cn.estimatedPercent,.5);assert.equal(cn.uncertainRequests,1);assert.equal(cn.knownRequests,1);const us=summarizeUsage(entries,{now:new Date('2026-09-22T05:00:00Z'),timeZone:'America/New_York'});assert.equal(us.estimatedPercent,0);assert.equal(us.dailyRecoveryRatio,null);});
test('Windows DPAPI roundtrip stores ciphertext tied to the current account',{skip:process.platform!=='win32'},async()=>{const vault=createWindowsVault(),secret='fixture-secret-no-account';const sealed=await vault.seal(secret);assert.notEqual(sealed,Buffer.from(secret).toString('base64'));assert.equal(await vault.open(sealed),secret);});
