import {Copy,RotateCcw} from 'lucide-react';
import {variantDiff,COMPARISON_FIELDS} from '../lib/comparison.mjs';
export function ComparisonControls({comparison:c,base}){
 const diff=variantDiff(base,c.config,c.variant);
 return <section className="comparison-controls"><label className="toggle comparison-enable"><input type="checkbox" checked={c.config.enabled} onChange={e=>c.enable(e.target.checked)}/><span>开启 A/B/C 对照<small>同轮共用种子 · 串行生成</small></span></label>{c.config.enabled&&<><div className="compare-config"><select aria-label="对照模式" value={c.config.mode} disabled={c.busy} onChange={e=>{c.setConfig(x=>({...x,mode:e.target.value}));if(e.target.value==='AB'&&c.variant==='C')c.setVariant('A');}}><option>AB</option><option>ABC</option></select><label>轮数<input aria-label="对照轮数" type="number" min="1" max="20" value={c.config.rounds} disabled={c.busy} onChange={e=>c.setConfig(x=>({...x,rounds:Number(e.target.value)}))}/></label><label className="toggle"><input type="checkbox" checked={c.config.locked} disabled={c.busy} onChange={e=>c.setConfig(x=>({...x,locked:e.target.checked}))}/>锁定 seed</label></div><label className="toggle opus-mode"><input type="checkbox" checked={!!c.config.noAnlas} disabled={c.busy} onChange={e=>c.setConfig(x=>({...x,noAnlas:e.target.checked}))}/>0 Anlas 模式（Opus）</label>{c.config.noAnlas&&<p className="hint">每请求 1 张，≤ 28 步、≤ 1,048,576 像素。超限时整组不提交；仍使用 V5 免费额度，上游账户 / 剩余额度未核验。</p>}<div className="variant-tabs">{(c.config.mode==='AB'?['A','B']:['A','B','C']).map(v=><button key={v} className={c.variant===v?'selected':''} onClick={()=>c.setVariant(v)}>{v}{v!=='A'&&<small>{variantDiff(base,c.config,v).length} 处差异</small>}</button>)}</div><p className="hint">正在编辑 {c.variant}：{c.variant==='A'?'基准方案':'未修改字段继承 A'}。尺寸、输入图和种子共用。</p>{c.variant!=='A'&&<div className="comparison-actions"><button onClick={()=>c.setConfig(x=>({...x,overrides:{...x.overrides,[c.variant]:{}}}))}><RotateCcw size={12}/>恢复继承 A</button>{c.variant==='C'&&<button onClick={()=>c.setConfig(x=>({...x,overrides:{...x.overrides,C:structuredClone(x.overrides.B)}}))}><Copy size={12}/>复制 B</button>}</div>}{diff.length>0&&<details><summary>{diff.length} 个差异字段</summary>{diff.map(d=><div className="diff-row" key={d.key}><code>{d.key}</code><small>{String(typeof d.after==='object'?JSON.stringify(d.after):d.after).slice(0,160)}</small><button aria-label={`恢复继承 ${d.key}`} onClick={()=>c.setConfig(x=>{const overrides={...x.overrides[c.variant]};delete overrides[d.key];return {...x,overrides:{...x.overrides,[c.variant]:overrides}};})}>还原</button></div>)}</details>}{c.busy&&<button className="wide" onClick={c.stop}>停止后续任务</button>}</>}</section>;
}
export function ComparisonBoard({comparison:c,onSelect,onSave}){
 const r=c.record;const [round,setRound]=useLocalRound(r?.id);const [zoom,setZoom]=useLocalZoom(r?.id);
 if(!r)return null;const jobs=r.jobs.filter(j=>j.round===Math.min(round,r.rounds));
 return <section className="comparison-board"><header><div><strong>A/B/C 对照</strong><small>{r.status} · {r.jobs.filter(j=>j.status==='success').length}/{r.jobs.length} 完成</small></div><select aria-label="对照记录" value={r.id} onChange={e=>c.load(e.target.value)}>{[r,...c.records.filter(x=>x.id!==r.id)].map(x=><option key={x.id} value={x.id}>{new Date(x.createdAt).toLocaleString('zh-CN')} · {x.mode}</option>)}</select></header><div className="compare-board-tools"><label>轮次<select aria-label="结果轮次" value={Math.min(round,r.rounds)} onChange={e=>setRound(Number(e.target.value))}>{Array.from({length:r.rounds},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label><label>同步缩放<input aria-label="对照同步缩放" type="range" min="1" max="3" step=".25" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><button onClick={()=>setZoom(1)}>适合</button></div><div className="compare-grid" style={{gridTemplateColumns:`repeat(${jobs.length},minmax(0,1fr))`}}>{jobs.map(j=><article key={j.variant}><div className="section-label"><strong>{j.variant}</strong><span>{j.status}</span></div><div className="compare-image">{j.result?.images?.[0]?<img style={{transform:`scale(${zoom})`}} src={j.result.images[0].url} alt={`方案 ${j.variant} 第 ${j.round} 轮`}/>:<span>{j.error?.message||'等待结果'}</span>}</div><small>Seed {j.seed} · {j.diff.length} 处差异</small><div className="compare-item-actions"><button disabled={!j.result} onClick={()=>onSelect(j.result)}>查看单图</button><button disabled={!j.result} onClick={()=>c.adopt(j)}>采用 {j.variant}</button><button disabled={!j.result?.images?.length} onClick={()=>onSave(j.result,0)}>保存</button></div><details><summary>参数差异</summary><pre>{JSON.stringify(j.diff,null,2)}</pre></details></article>)}</div></section>;
}
import {useEffect,useState} from 'react';
function useLocalRound(id){const [r,set]=useState(1);useEffect(()=>set(1),[id]);return [r,set];}
function useLocalZoom(id){const [r,set]=useState(1);useEffect(()=>set(1),[id]);return [r,set];}
