import {saveBlob,shareBlob,isAndroid} from '../lib/platform.mjs';
import {useEffect,useRef,useState} from 'react';
import {X,Plus,Minus,Maximize2,ExternalLink,Hand,Move,Download} from 'lucide-react';
import {danbooruImageUrl} from '../lib/danbooru.mjs';
import useDanbooruImage from '../hooks/useDanbooruImage';

export default function DanbooruImageViewer({post,onClose,active=true}){
 const dialog=useRef(null),stage=useRef(null),drag=useRef(null),[size,setSize]=useState(null),[zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0}),[exportMode,setExportMode]=useState(false),[failed,setFailed]=useState(false);
 const src=post.original||post.preview||post.thumbnail;
 const [revision,setRevision]=useState(0),file=useRef(null),imageRead=useDanbooruImage(src,{active,revision}),imageSrc=imageRead.image,error=imageRead.error;
 useEffect(()=>{setFailed(imageRead.failed);if(imageRead.blob){const blob=imageRead.blob,ext=blob.type==='image/jpeg'?'jpg':blob.type.split('/')[1]||'png';file.current=new File([blob],`Danbooru-${post.id}.${ext}`,{type:blob.type});}else{file.current=null;setSize(null);}},[imageRead,post.id]);
 useEffect(()=>{const el=dialog.current;if(!active){el.close();return;}const previous=document.activeElement;if(!el.open)el.showModal();return()=>{el.close();previous?.focus?.({preventScroll:true});};},[active]);
 useEffect(()=>{if(!size||!active)return;const el=stage.current,wheel=e=>{e.preventDefault();setZoom(z=>Math.min(8,Math.max(.02,z*(e.deltaY<0?1.12:1/1.12))));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[size,active]);
 function fit(s=size){if(!s||!stage.current||!active)return;const r=stage.current.getBoundingClientRect();setZoom(Math.min(1,(r.width-28)/s.width,(r.height-28)/s.height));setOffset({x:0,y:0});}
 useEffect(()=>{if(!size||!active)return;const observer=new ResizeObserver(()=>{if(stage.current?.clientWidth>0)fit();});observer.observe(stage.current);return()=>observer.disconnect();},[size,active]);
 function changeZoom(value){setZoom(Math.min(8,Math.max(.02,value)));}
 function moveStart(e){if(exportMode||!size||e.button!==0)return;e.preventDefault();drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,start:offset};e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e){const d=drag.current;if(!d||d.id!==e.pointerId)return;setOffset({x:d.start.x+e.clientX-d.x,y:d.start.y+e.clientY-d.y});}
 function stop(e){if(drag.current?.id===e.pointerId)drag.current=null;}
 return <dialog ref={dialog} className="danbooru-viewer" aria-label={`原图查看 #${post.id}`} onCancel={e=>{e.preventDefault();e.stopPropagation();onClose();}}>
  <header><strong>#{post.id}<small>{post.original?'原图':'可用预览'}{size?` · ${size.width} × ${size.height}`:''}</small></strong><div className="danbooru-zoom-controls"><button aria-label="缩小图片" disabled={!size} onClick={()=>changeZoom(zoom/1.25)}><Minus size={16}/></button><output aria-label="图片缩放比例">{Math.round(zoom*100)}%</output><button aria-label="放大图片" disabled={!size} onClick={()=>changeZoom(zoom*1.25)}><Plus size={16}/></button><button disabled={!size} onClick={()=>{setZoom(1);setOffset({x:0,y:0});}}>100%</button><button disabled={!size} onClick={()=>fit()}><Maximize2 size={15}/>适应画面</button>{!isAndroid()&&<button aria-pressed={exportMode} onClick={()=>{drag.current=null;setExportMode(v=>!v);}}>{exportMode?<Hand size={15}/>:<Move size={15}/>}拖出图片</button>}<a href={src?danbooruImageUrl(src):post.pageUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/>打开原图</a>{imageSrc&&<a href={imageSrc} download={file.current?.name||`Danbooru-${post.id}.png`} onClick={e=>{if(isAndroid()){e.preventDefault();saveBlob(file.current,file.current.name).catch(error=>window.alert(error.message));}}}><Download size={15}/>下载原图</a>}{isAndroid()&&imageSrc&&<button onClick={()=>shareBlob(file.current,file.current.name).catch(error=>window.alert(error.message))}>分享原图</button>}<button aria-label="关闭大图" onClick={onClose}><X size={20}/></button></div></header>
  <div ref={stage} className={`danbooru-image-stage${exportMode?' export-mode':''}`} tabIndex={0} aria-label="可缩放图片画布" onPointerDown={moveStart} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={()=>{drag.current=null;}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();setOffset(o=>({x:o.x+(e.key==='ArrowLeft'?40:e.key==='ArrowRight'?-40:0),y:o.y+(e.key==='ArrowUp'?40:e.key==='ArrowDown'?-40:0)}));}else if(e.key==='+'||e.key==='='){e.preventDefault();changeZoom(zoom*1.25);}else if(e.key==='-'){e.preventDefault();changeZoom(zoom/1.25);}}}>
   {!size&&!failed&&<p role="status">正在读取大图…</p>}{failed?<div role="alert"><p>{error||'原图暂时无法加载，可在原帖查看。'}</p><button disabled={!src} onClick={()=>setRevision(v=>v+1)}>重新加载原图</button> <a href={post.pageUrl} target="_blank" rel="noreferrer">在原帖查看</a></div>:imageSrc&&<img src={imageSrc} alt={`Danbooru 原图 #${post.id}`} referrerPolicy="no-referrer" draggable={exportMode} onDragStart={e=>{if(exportMode&&file.current){e.dataTransfer.clearData();e.dataTransfer.items.add(file.current);e.dataTransfer.effectAllowed='copy';}}} onError={()=>setFailed(true)} onLoad={e=>{const s={width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight};setSize(s);fit(s);}} style={size?{width:size.width*zoom,height:size.height*zoom,transform:`translate(calc(-50% + ${offset.x}px),calc(-50% + ${offset.y}px))`}:{visibility:'hidden'}}/>}
  </div>
  <footer>{isAndroid()?'使用上方按钮缩放 · 拖动画面移动 · 下载或分享原图':exportMode?'现在可拖动图片到其他窗口；接收方不支持时，可右键保存。':'滚轮缩放 · 拖动画面移动 · 方向键微移 · Esc 返回图库'}{post.original?'':' · 此帖子暂未提供可用原图，显示预览版本。'}</footer>
 </dialog>;
}
