import {useEffect,useRef,useState} from 'react';
import {Plus,Search,Save,Trash2,Download,Upload,ExternalLink,ClipboardPaste,RotateCcw,Layers,NotebookPen,Bookmark} from 'lucide-react';
import {api,downloadData} from '../lib/api.mjs';
import {exportPreset} from '../lib/request.mjs';
import {CARD_CATEGORIES,categoryFor} from '../lib/prompt-cards.mjs';
import CoverImageInput from './CoverImageInput';
import {Select} from './Fields';
const ATLAS='https://novelai.quicktagcloud.com/?c=artist_nai5_personal';
const kinds=[['snippet','提示词片段'],['style','画风片段（旧）'],['starter','Prompt 起手（旧）'],['negative','负面提示词片段'],['character','多角色设置'],['favorite','来源收藏片段'],['preset','完整预设 · Prompt + 参数'],['parameters','仅参数（旧）'],['draft','完整草稿 · 含图片']];
const sectionFor=kind=>kind==='draft'?'drafts':['preset','parameters'].includes(kind)?'presets':'cards';
export default function LibraryPanel({initialTab='cards',editorState,draftState,comparisonConfig,seed,onApply,onError,onSaved,onChanged}){
 const [tab,setTab]=useState(seed?sectionFor(seed.kind):initialTab==='library'?'cards':initialTab),[focusEditor,setFocusEditor]=useState(!!seed),[entries,setEntries]=useState([]),[categories,setCategories]=useState(CARD_CATEGORIES),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[editing,setEditing]=useState(seed||null),[notice,setNotice]=useState(''),[deleted,setDeleted]=useState(null),[loading,setLoading]=useState(false),[today,setToday]=useState(false),[sourceOnly,setSourceOnly]=useState(false),[categoryName,setCategoryName]=useState(''),[addingCategory,setAddingCategory]=useState(false);
 const importer=useRef(null),request=useRef(0),nameInput=useRef(null);
 useEffect(()=>{if(focusEditor)requestAnimationFrame(()=>{nameInput.current?.focus({preventScroll:true});nameInput.current?.select();});},[focusEditor]);
 async function load(){const id=++request.current;try{setLoading(true);const [data,c]=await Promise.all([api('/api/library?'+new URLSearchParams({q:query,...today?{today:'1'}:{}})),api('/api/library/categories')]);if(id!==request.current)return;setEntries(data.entries);setCategories(c.categories);}catch(e){if(id===request.current)onError(e.message);}finally{if(id===request.current)setLoading(false);}}
 useEffect(()=>{if(tab==='atlas')return;const timer=setTimeout(load,120);return()=>{clearTimeout(timer);request.current++;};},[tab,query,today]);
 const visible=entries.filter(e=>sectionFor(e.kind)===tab&&(!category||categoryFor(e)===category)&&(!sourceOnly||e.sourceUrl||e.kind==='favorite'));
 function snapshot(type){return type==='draft'?{state:structuredClone(draftState||editorState),comparison:{...comparisonConfig,enabled:false}}:type==='preset'||type==='parameters'?{state:exportPreset(editorState).state}:type==='character'?{characters:structuredClone(editorState.characters),coords:editorState.coords}:null;}
 function create(type=tab==='presets'?'preset':tab==='drafts'?'draft':'snippet'){
  try{const payload=snapshot(type);setFocusEditor(true);setEditing({kind:type,title:'',category:category||'其他',notes:'',text:payload?.state?.prompt??(type==='negative'?editorState.negative:editorState.prompt),sourceUrl:type==='favorite'?ATLAS:'',cover:'',payload});}catch(e){onError(e.message);}
 }
 async function save(){try{const result=await api('/api/library',{method:'POST',body:editing});setEditing(result);onSaved?.(result);setTab(sectionFor(result.kind));setNotice('已保存到本机资料库。');await load();}catch(e){onError(e.message);}}
 async function open(entry){try{setEditing(await api('/api/library/'+entry.id));setFocusEditor(true);}catch(e){onError(e.message);}}
 async function archive(entry){try{await api('/api/library/'+entry.id,{method:'DELETE'});setDeleted(entry.id);if(editing?.id===entry.id){setEditing(null);setFocusEditor(false);}onChanged?.();await load();}catch(e){onError(e.message);}}
 async function importFile(file){if(!file)return;try{if(file.size>128*1024*1024)throw Error('导入文件过大');const value=JSON.parse(await file.text());if(value.format==='novelai-studio'&&value.state){setEditing({kind:'preset',title:file.name.replace(/\.json$/i,''),category:'其他',notes:'从配方文件导入',text:value.state.prompt||'',cover:'',sourceUrl:'',payload:{state:exportPreset(value.state).state}});setTab('presets');setFocusEditor(true);setNotice('已读取完整预设，请检查名称后保存。');}else{const d=await api('/api/library/import',{method:'POST',body:value});setNotice(`已导入 ${d.entries.length} 条记录，原有记录保留。`);onChanged?.();await load();}}catch(e){onError(e.message);}}
 const patch=(k,v)=>setEditing(e=>({...e,[k]:v}));
 const full=editing&&['preset','parameters','draft'].includes(editing.kind);
 function changeText(text){setEditing(e=>({...e,text,...full&&e.payload?.state?{payload:{...e.payload,state:{...e.payload.state,prompt:text,promptCards:[]}}}:{}}));}
 return <div className={`library-workspace card-library${focusEditor?' editor-only':''}`}>
  {initialTab!=='drafts'&&!focusEditor&&<nav className="feature-tabs">{[['cards','提示词卡片'],['presets','完整预设']].map(([key,label])=><button key={key} className={tab===key?'selected':''} onClick={()=>{setTab(key);setCategory('');setEditing(null);setSourceOnly(false);}}>{label}</button>)}</nav>}
  {focusEditor&&<button className="editor-back text-button" onClick={()=>{setFocusEditor(false);setEditing(null);}}><RotateCcw size={13}/>{tab==='drafts'?'返回草稿列表':'返回卡片 / 预设'}</button>}
   <div className="collection-heading"><div><h3>{tab==='cards'?'用片段组合灵感':tab==='presets'?'保存一整套创作设置':'暂存正在进行的创作'}</h3><p>{tab==='cards'?'一张卡片，一组画风、角色或场景词。插入后可继续改写。':tab==='presets'?'正面、负面、角色及所有生成参数一起保存；输入图片与蒙版由草稿保留。':'包含输入图、蒙版、A 基准与 B/C 差异。恢复后不会自动生图。'}</p></div><button className="primary" onClick={()=>create()}><Plus size={14}/>{tab==='presets'?'保存当前为完整预设':tab==='drafts'?'保存当前草稿':'新建卡片'}</button></div>
   <div className="library-toolbar"><div className="inline-input"><Search size={15}/><input aria-label="搜索预设" placeholder="搜索名称、提示词或备注…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{tab==='cards'&&<label className="toggle"><input type="checkbox" checked={sourceOnly} onChange={e=>setSourceOnly(e.target.checked)}/>仅来源收藏</label>}<label className="toggle"><input type="checkbox" checked={today} onChange={e=>setToday(e.target.checked)}/>今日保存</label><button title="导出整个资料库" onClick={async()=>{try{await downloadData(await api('/api/library/export'),'Lucifer-FX-资料库.json');}catch(e){onError(e.message);}}}><Download size={15}/></button><button title="导入资料库或完整配方" onClick={()=>importer.current.click()}><Upload size={15}/></button><input ref={importer} hidden type="file" accept="application/json" onChange={e=>{importFile(e.target.files?.[0]);e.target.value='';}}/></div>
   <div className="card-categories" aria-label="资料分类"><button className={!category?'selected':''} onClick={()=>setCategory('')}>全部</button>{categories.map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}<button title="添加分类" onClick={()=>setAddingCategory(v=>!v)}><Plus size={13}/>分类</button></div>
   {addingCategory&&<form className="new-category" onSubmit={async e=>{e.preventDefault();try{const d=await api('/api/library/categories',{method:'POST',body:{name:categoryName}});setCategories(d.categories);setCategory(categoryName.trim());setCategoryName('');setAddingCategory(false);}catch(error){onError(error.message);}}}><input aria-label="新分类名称" placeholder="例如：镜头、光影、建筑…" maxLength={40} value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><button disabled={!categoryName.trim()}>添加分类</button></form>}
   {notice&&<p className="inline-success" role="status">{notice}</p>}{deleted&&<button className="text-button" onClick={async()=>{try{await api('/api/library/'+deleted+'/restore',{method:'POST',body:{}});setDeleted(null);load();}catch(e){onError(e.message);}}}><RotateCcw size={13}/>撤销删除</button>}
   <div className={editing?'library-columns':'library-columns no-editor'}><div className="library-cards">
    {loading&&<p className="hint">正在读取本地记录…</p>}{!loading&&!visible.length&&<p className="empty-library">{tab==='cards'?'选中 Prompt 中的一段文字，点击“选区存为卡片”，也可以在这里新建。':'在工作台调好提示词和参数，再点右上角保存；也可以导入配方。'}</p>}
    {visible.map(entry=><article className={editing?.id===entry.id?'library-card selected-card':'library-card'} key={entry.id}>
     <button className="library-card-open" onClick={()=>open(entry)}>{entry.cover?<img src={entry.cover} alt={entry.title} loading="lazy"/>:<div className="card-paper-mark">{entry.kind==='draft'?<NotebookPen size={24}/>:entry.kind==='preset'?<Layers size={24}/>:<Bookmark size={24}/>}</div>}<span className="card-category-caption">{categoryFor(entry)}{entry.sourceUrl?' · 来源收藏':''}</span><strong className="handwritten-card-name">{entry.title}</strong><p>{entry.text?.slice(0,160)||entry.notes?.slice(0,100)||'完整编辑状态'}</p>{['draft','preset','parameters'].includes(entry.kind)&&<small>{entry.kind==='preset'?'Prompt + 全部参数':entry.kind==='draft'?'工作状态 + 图片':'旧版参数预设'}</small>}</button>
     <div className="library-card-actions"><button onClick={async()=>{try{onApply(await api('/api/library/'+entry.id),'insert');}catch(e){onError(e.message);}}}>{entry.kind==='draft'?'恢复草稿':entry.kind==='preset'?'应用完整预设':entry.kind==='parameters'?'应用参数':entry.kind==='character'?'应用角色':'添加到 Prompt'}</button><button aria-label={`编辑 ${entry.title}`} onClick={()=>open(entry)}>编辑</button><button aria-label={`删除 ${entry.title}`} onClick={()=>archive(entry)}><Trash2 size={13}/></button></div>
    </article>)}
   </div>
   {editing&&<aside className="preset-editor"><header><h3>{editing.kind==='preset'?'完整预设':editing.kind==='draft'?'草稿':'编辑卡片'}</h3><button onClick={()=>{setEditing(null);setFocusEditor(false);}}>收起</button></header>
    <div className="card-editor-identity"><CoverImageInput label="卡片封面" value={editing.cover} onChange={cover=>patch('cover',cover)}/><div><label>名称<input ref={nameInput} aria-label="预设名称" value={editing.title} onChange={e=>patch('title',e.target.value)} placeholder="给它一个容易记住的名字"/></label>
    <label>分类<select aria-label="预设分类" value={editing.category||'其他'} onChange={e=>patch('category',e.target.value)}>{[...new Set([...categories,editing.category||'其他'])].map(c=><option key={c}>{c}</option>)}</select></label>
    <Select label="内容类型" value={editing.kind} options={kinds.filter(([value])=>initialTab==='drafts'?value==='draft':value!=='draft').map(([value,label])=>({value,label}))} onChange={kind=>{try{const payload=snapshot(kind);setEditing(e=>({...e,kind,payload,text:payload?.state?.prompt??(kind==='negative'?editorState.negative:e.text)}));}catch(e){onError(e.message);}}}/>
    </div></div><label>{full?'正面 Prompt':'提示词片段'}<textarea aria-label="预设提示词" rows={7} value={editing.text} onChange={e=>changeText(e.target.value)}/></label>
    {!full&&<button className="text-button" onClick={async()=>{try{changeText(await navigator.clipboard.readText());}catch{onError('请用 Ctrl+V 粘贴；浏览器未授予剪贴板读取权限。');}}}><ClipboardPaste size={13}/>从剪贴板粘贴</button>}
    {full&&editing.payload?.state&&<><label>负面 Prompt<textarea aria-label="预设负面" rows={3} value={editing.payload.state.negative||''} onChange={e=>setEditing(x=>({...x,payload:{...x.payload,state:{...x.payload.state,negative:e.target.value,negativeCards:[]}}}))}/></label><details><summary>已保存的参数与角色</summary><pre>{JSON.stringify({...editing.payload.state,source:editing.payload.state.source?'[已包含输入图]':undefined,mask:editing.payload.state.mask?'[已包含蒙版]':undefined,prompt:undefined,negative:undefined},null,2)}</pre></details><button className="text-button" onClick={()=>{try{const payload=snapshot(editing.kind);setEditing(e=>({...e,text:payload?.state?.prompt??editorState.prompt,payload}));}catch(e){onError(e.message);}}}>用当前工作台更新快照</button></>}
    <label>备注<textarea aria-label="预设备注" rows={2} value={editing.notes} onChange={e=>patch('notes',e.target.value)}/></label><label>来源链接<input aria-label="预设来源" value={editing.sourceUrl} onChange={e=>patch('sourceUrl',e.target.value)}/></label>
    <div className="preset-editor-actions"><button className="primary" onClick={save}><Save size={14}/>{full?'保存预设 / 草稿':'保存卡片'}</button><button onClick={()=>onApply(editing,'insert')}>{editing.kind==='preset'?'应用完整预设':editing.kind==='draft'?'恢复草稿':editing.kind==='parameters'?'应用参数':editing.kind==='character'?'应用角色':[...(editorState.promptCards||[]),...(editorState.negativeCards||[])].some(c=>c.presetId===editing.id)?'再插入一份':'插入到 Prompt'}</button>{!full&&editing.kind!=='character'&&<button onClick={()=>onApply(editing,'replace')}>替换选区</button>}</div>
   </aside>}
   </div>
 </div>;
}
