import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api.mjs';
import {isAndroid} from '../lib/platform.mjs';
const size=bytes=>`${(bytes/1024/1024).toFixed(1)} MiB`;
export default function LibraryCleanupControls({filters,groupBy,groupValue,onGroup,selected,onSelect,onRefresh,onError,revision=0}){
 const [groups,setGroups]=useState([]),[maxImages,setMaxImages]=useState('0'),[trash,setTrash]=useState([]),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const dialog=useRef(null),sequence=useRef(0);
 const report=e=>onError?.(e.message||String(e));
 async function refresh(){const [settings,result]=await Promise.all([api('/api/generated-library/cleanup/settings'),api('/api/generated-library/cleanup/trash')]);setMaxImages(String(settings.maxImages));setTrash(result.entries||[]);if(settings.lastError)setNotice(settings.lastError);}
 useEffect(()=>{refresh().catch(report);},[revision]);
 useEffect(()=>{let alive=true;api('/api/generated-library/groups?'+new URLSearchParams({...filters,groupBy,groupValue:''})).then(result=>{if(alive)setGroups(result.groups||[]);}).catch(report);return()=>{alive=false;};},[filters,groupBy,revision]);
 useEffect(()=>{if(preview)dialog.current?.showModal();else dialog.current?.close();},[preview]);
 async function work(fn){if(busy)return;setBusy(true);try{await fn();}catch(e){report(e);}finally{setBusy(false);}}
 async function chooseGroup(){await work(async()=>{const result=await api('/api/generated-library/select',{method:'POST',body:{...filters,groupBy,groupValue}});onSelect(result.items||[]);setNotice(`已选中${groupValue?'本类别':'当前筛选条件下'}全部 ${result.items.length} 张（包含尚未加载的图片）。`);});}
 async function inspect(){const token=++sequence.current;await work(async()=>{const result=await api('/api/generated-library/cleanup/preview',{method:'POST',body:{keys:selected}});if(token===sequence.current)setPreview(result);});}
 async function remove(){await work(async()=>{const result=await api('/api/generated-library/cleanup/execute',{method:'POST',body:{token:preview.token}});setPreview(null);onSelect([]);onRefresh();await refresh();setNotice(`已将 ${result.count} 张移入本机回收站；${result.protectedCount} 张受保护。7 天内可恢复，清空后释放空间。`);});}
 return <div className="library-cleanup-controls">
  <div className="library-group-controls"><label>归类<select aria-label="图库归类" value={groupBy} onChange={e=>onGroup(e.target.value,'')}><option value="date">日期（UTC）</option><option value="model">模型</option><option value="tag">手工标签</option></select></label><label>类别<select aria-label="图库类别" value={groupValue} onChange={e=>onGroup(groupBy,e.target.value)}><option value="">全部类别</option>{groups.map(g=><option key={g.value} value={g.value}>{g.label||g.value} · {g.count} 张</option>)}</select></label><button disabled={busy} onClick={chooseGroup}>全选{groupValue?'本类别':'筛选结果'}</button><button disabled={busy||!selected.length} onClick={inspect}>批量删除…</button></div>
  <details><summary>图库容量与回收站</summary>{isAndroid()&&<p>Android 只清理应用内部缓存和内部自动输出。系统目录中的外部文件额外保护，需在系统文件管理器中处理；部分删除一组图片时，共享的原始响应记录保留。</p>}<p>自动清理默认关闭。超过上限时先清理最旧图片；收藏及手动保存图片始终保护，受保护图片过多时可能超限。</p><form onSubmit={e=>{e.preventDefault();void work(async()=>{const n=Number(maxImages);if(!Number.isInteger(n)||n<0||n>1000000||!maxImages.trim())throw Error('请输入 0–1000000 的整数。');if(n>0&&!window.confirm(`启用图库上限 ${n} 张？空闲时会自动把最旧的未保护图片移入回收站，7 天后永久清理。`))return;await api('/api/generated-library/cleanup/settings',{method:'POST',body:{maxImages:n}});setNotice(n?`已设置最多 ${n} 张，将在应用空闲时整理。`:'自动清理已关闭；已在回收站的文件仍按 7 天期限清理。');});}}><label>最大图片数量<input aria-label="图库最大图片数量" type="number" min="0" max="1000000" step="1" value={maxImages} onChange={e=>setMaxImages(e.target.value)}/></label><small>0 = 不自动清理</small><button disabled={busy}>保存清理设置</button></form><p>删除范围：内部历史缓存与自动 output。回收站保留 7 天，期间仍占磁盘；可恢复，也可立即清空。部分删除一组多图时，共用响应文件保留至该组全部删除。</p>
   {trash.map(item=><div className="library-trash-row" key={item.id}><span>{item.createdAt.slice(0,19).replace('T',' ')} · {item.count} 张 · {size(item.bytes)}{item.status!=='trashed'?' · 上次整理未完成':''}</span><button disabled={busy} onClick={()=>work(async()=>{await api('/api/generated-library/cleanup/restore',{method:'POST',body:{id:item.id}});await refresh();onRefresh();setNotice('图片已恢复。');})}>恢复这批</button></div>)}
   {!!trash.length&&<button disabled={busy} onClick={()=>work(async()=>{if(!window.confirm('永久清空回收站中已完成删除的图片？此操作无法恢复。'))return;await api('/api/generated-library/cleanup/purge',{method:'POST',body:{confirm:true}});await refresh();setNotice('回收站已清空。未完成的清理记录保留供恢复。');})}>立即清空回收站</button>}
  </details>{notice&&<p role="status">{notice}</p>}
  <dialog ref={dialog} className="library-delete-dialog" onCancel={e=>{if(busy)e.preventDefault();else setPreview(null);}}><h3>确认清理图库</h3>{preview&&<><p>可清理 {preview.count} 张；保护 {preview.protectedCount} 张。</p><p>关联文件 {preview.files} 个，共 {size(preview.bytes)}。将清理内部缓存与自动 output；收藏和手动保存不受影响。</p><p>先移到本机回收站，7 天后永久清理。期间可恢复；立即清空才会释放空间。</p><div><button disabled={busy} onClick={()=>setPreview(null)}>取消</button><button disabled={busy||!preview.count} onClick={remove}>{busy?'正在处理…':'确认移入回收站'}</button></div></>}</dialog>
 </div>;
}
