import {FolderOpen} from 'lucide-react';
import {localFileAction,openLocalFolder} from '../lib/local-files.mjs';
import {useState} from 'react';
import {api,downloadData} from '../lib/api.mjs';
function diagnostic(error){if(error.code==='shutdown_forbidden'||error.code==='generation_busy')return error.message;if([401,403].includes(error.status))return '凭据验证失败：请核对 Token / Key 与所选接口。'+error.message;if([404,405].includes(error.status))return '接口不兼容：此地址未提供所需的只读接口，请检查协议和路径。'+error.message;if([402,429].includes(error.status))return '额度或请求频率受限：'+error.message;if(error.code==='gateway_connect_error'||error.status>=500)return '网络或服务暂不可用：'+error.message;return error.message;}
const prefKeys=['lucifer-fx-appearance-v1','lucifer-panel-layout-v1','lucifer-tag-suggestions-v1','lucifer-zh-glossary-v1','lucifer-history-collapsed-v1'];
export default function ShareSettings({value,onSaved,onClose,initialTab='connection'}){
 const [tab,setTab]=useState(initialTab),[form,setForm]=useState({...value,key:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[backup,setBackup]=useState(null),[backupName,setBackupName]=useState(''),[backupMode,setBackupMode]=useState('restore'),[backupPreview,setBackupPreview]=useState(null);
 const field=(key,value)=>setForm(s=>({...s,[key]:value}));
 async function run(action){if(busy)return;setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(diagnostic(e));}finally{setBusy(false);}}
 async function save(){const data=await api('/api/settings',{method:'POST',body:form});setForm({...data,key:''});onSaved(data);setMessage('设置已保存。密钥不会进入备份或导出文件。');return data;}
 async function directory(key){setMessage('正在打开 Windows 文件夹选择器…');const r=await localFileAction('/api/settings/directory',{kind:key,initialPath:form[key]});if(r.path){field(key,r.path);setMessage('已选择目录；点击“检查目录并保存”后生效。');}else if(r.cancelled)setMessage('已取消选择，原目录未改变。');}
 return <div className="share-settings"><div className="share-tabs" role="tablist" aria-label="应用设置">{[['connection','连接'],['storage','保存位置'],['backup','备份迁移'],['tutorial','新手教程']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='connection'&&<><h3>连接你自己的 NovelAI 服务</h3><p>分享包不含任何 API Key。填写后先进行只读检测；检测不会生成图片。</p><label>接口类型<select aria-label="接口类型" value={form.provider} onChange={e=>setForm(s=>({...s,provider:e.target.value,key:'',baseURL:e.target.value==='official'?'https://image.novelai.net':''}))}><option value="official">NovelAI 官方 Token</option><option value="native">兼容网关 · NovelAI 原生</option><option value="openai">兼容网关 · OpenAI Images + novelai 扩展</option></select></label>
 {form.provider!=='official'&&<label>API 地址<input aria-label="API 地址" value={form.baseURL} placeholder="https://你的服务地址" onChange={e=>field('baseURL',e.target.value)}/></label>}
 <label>API Token / Key<input aria-label="API Token / Key" type="password" autoComplete="off" value={form.key} onChange={e=>field('key',e.target.value)} placeholder={form.keyConfigured?'已保存；留空保持当前密钥':'只保存在此设备的安全存储'}/></label>
 {form.provider==='official'?<p><a href="https://docs.novelai.net/en/text/usersettings/account/" target="_blank" rel="noreferrer">如何获取官方 Persistent API Token ↗</a>。重新生成 Token 会使旧 Token 失效，请留意其他正在使用它的软件。</p>:<p>网关需要支持完整 NovelAI 参数；普通 OpenAI 图片 API 不一定兼容。网关计费与 NovelAI Anlas 分开。</p>}
 <div className="row-buttons"><button disabled={busy} onClick={()=>run(save)}>保存连接</button><button disabled={busy} onClick={()=>run(async()=>{await save();const result=await api('/api/connection/check',{method:'POST',body:{}});onSaved(await api('/api/settings'));setMessage(result.message||'只读连接检查通过。');})}>保存并检测连接</button><button disabled={busy||!form.keyConfigured} onClick={()=>run(async()=>{const data=await api('/api/settings',{method:'POST',body:{clearKey:true}});setForm({...data,key:''});onSaved(data);setMessage('此设备保存的密钥已清除。');})}>清除密钥</button></div></>}
 {tab==='storage'&&<><h3>图片保存位置</h3><p>自动输出与主动收藏分开保存。更改位置只影响新图片，不搬迁或删除旧作品。</p>{[['outputDirectory','自动输出目录'],['saveDirectory','精选保存目录']].map(([key,label])=><label key={key}>{label}<div className="share-directory"><input aria-label={label} value={form[key]||''} onChange={e=>field(key,e.target.value)} readOnly={value.platform==='android'}/><button disabled={busy} onClick={()=>run(()=>directory(key))}>{busy?'等待目录选择…':'选择文件夹'}</button><button className="folder-shortcut" aria-label={`打开${label}`} title={form[key]!==value[key]?'请先保存修改后的目录':`打开${label}`} disabled={busy||form[key]!==value[key]} onClick={()=>run(()=>openLocalFolder(key==='outputDirectory'?'output':'saved'))}><FolderOpen size={17}/></button></div></label>)}<p>{value.platform==='android'?'默认使用应用数据目录。选择外部文件夹时由 Android 授权；卸载前请备份或导出作品。':'默认位于分享包 userdata 文件夹。升级程序时请保留 userdata。'}</p><button disabled={busy} onClick={()=>run(save)}>检查目录并保存</button>{value.platform==='windows'&&<><h3>退出本安装的服务</h3><p>请先等生成和对照任务结束；关闭网页不会停止后台服务。退出后即可保留 userdata 并更新程序文件。</p><button disabled={busy} onClick={()=>run(async()=>{const status=await api('/api/status');if(!status.shareEdition||!status.installId)throw Error('当前不是由本安装启动器管理的服务。');const result=await api('/api/shutdown',{method:'POST',body:{},headers:{'Content-Type':'application/json','X-FX-Action':'shutdown','X-FX-Install-Id':status.installId}});setMessage(result.message);})}>退出服务</button></>}</>}
 {tab==='backup'&&<><h3>带走你的创作工具</h3><p>备份包含卡片、完整预设、连接类型和界面偏好，不包含 API Key、生成图片、历史或账本。复制整个 userdata 文件夹时，通常只需恢复界面偏好。</p><button disabled={busy} onClick={()=>run(async()=>{const exported=await api('/api/backup');exported.preferences=Object.fromEntries(prefKeys.map(k=>[k,localStorage.getItem(k)]).filter(([,v])=>v!==null));await downloadData(exported,'Lucifer-FX-工具备份.json');setMessage('已导出不含密钥的备份。');})}>导出工具备份</button><label className="share-import">选择工具备份<input type="file" accept=".json,application/json" aria-label="选择工具备份" onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{setBackup(null);setBackupName('');setBackupPreview(null);if(file.size>64*1024*1024)throw Error('备份超过 64 MiB');const parsed=JSON.parse(await file.text());if(parsed.format!=='lucifer-fx-share-backup'||parsed.version!==1)throw Error('不是兼容的分享版备份。');setBackup(parsed);setBackupName(file.name);setMessage(`已选择 ${file.name}，请先预览。`);});e.target.value='';}}/></label>{backup&&<><p>当前备份：{backupName}</p><label>恢复方式<select aria-label="恢复方式" value={backupMode} onChange={e=>{setBackupMode(e.target.value);setBackupPreview(null);}}><option value="restore">恢复资料与连接类型；同 ID 冲突保留本地</option><option value="merge">合并资料；冲突内容另存且不改连接</option><option value="preferences">仅恢复界面偏好；不改资料与连接</option></select></label><button disabled={busy} onClick={()=>run(async()=>{setBackupPreview(await api('/api/backup/preview',{method:'POST',body:{backup,mode:backupMode}}));})}>预览导入</button>{backupPreview&&<><p role="status">预览：新增 {backupPreview.added}，跳过 {backupPreview.skipped}，冲突保留 {backupPreview.conflicts}；{backupPreview.connectionWillChange?'将恢复连接类型（不含密钥）':'连接不变'}，界面偏好 {backupPreview.preferencesAvailable} 项。</p><button disabled={busy} onClick={()=>run(async()=>{const result=await api('/api/backup',{method:'POST',body:{backup,mode:backupMode}});for(const key of prefKeys)if(typeof backup.preferences?.[key]==='string')localStorage.setItem(key,backup.preferences[key]);setBackupPreview(null);setMessage(`${result.message} 实际新增 ${result.added}，跳过 ${result.skipped}，冲突 ${result.conflicts}。刷新页面后载入界面偏好。`);})}>执行所选恢复</button></>}</>}</>}
 {tab==='tutorial'&&<><h3>从第一张图开始</h3><ol className="share-tutorial"><li><strong>填写连接</strong><p>选择官方或兼容网关，填入自己的凭据，点击只读检测。</p></li><li><strong>写画面</strong><p>先用少量英文标签，例如 <code>landscape, cherry blossoms, blue sky</code>。中文释义可帮助理解标签。</p></li><li><strong>检查费用</strong><p>先选 1 张、普通尺寸、23 步。Opus 的 0 Anlas 有账户和额度前提，第三方网关可能另收费。</p></li><li><strong>主动点击生成</strong><p>教程不会自动生成。等待时可浏览旧图；不明确的失败不会自动重试。</p></li><li><strong>找到图片</strong><p>自动结果进入 output；点击“保存到精选目录”另存精选。也可导出不带提示词元数据的副本。</p></li></ol><details><summary>三个常用参数是什么意思？</summary><p><b>Steps</b>：处理步数，越多通常越慢，也可能更贵。<br/><b>Guidance</b>：模型遵循文字的强度，过高未必更好。<br/><b>Seed</b>：随机种子；-1 每次变化，固定数值配合同一组参数便于比较。</p></details><label className="toggle"><input type="checkbox" checked={form.beginner} onChange={e=>field('beginner',e.target.checked)}/>默认使用新手模式，高级参数可随时展开</label><button disabled={busy} onClick={()=>run(async()=>{const data=await api('/api/settings',{method:'POST',body:{beginner:form.beginner,tutorialComplete:true}});onSaved(data);onClose();})}>我知道了，进入工作台</button></>}
 {error&&<p role="alert" className="share-error">{error}</p>}{message&&<p role="status" className="share-message">{message}</p>}{busy&&<p role="status">正在处理…</p>}
 </div>;
}
