import {build as buildFrontend} from 'vite';
import {mkdir,readFile,writeFile,readdir,cp,stat,rename} from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {execFile}from'node:child_process';import{promisify}from'node:util';import {build}from'esbuild';import {unzipSync,zipSync}from'fflate';
const appVersion=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8')).version;
const exec=promisify(execFile),root=process.cwd(),version='v24.21.0',file=`node-${version}-win-x64.zip`,tools=path.join(root,'.tools'),release=path.join(root,'release');await mkdir(tools,{recursive:true});await mkdir(release,{recursive:true});await mkdir(path.join(root,'.local'),{recursive:true});
const archive=path.join(tools,file),hashList=await(await fetch(`https://nodejs.org/dist/${version}/SHASUMS256.txt`)).text(),expected=hashList.split('\n').find(line=>line.endsWith('  '+file))?.split(/\s+/)[0];if(!expected)throw Error('No official runtime hash');let bytes;try{bytes=await readFile(archive);}catch{const r=await fetch(`https://nodejs.org/dist/${version}/${file}`);if(!r.ok)throw Error('Runtime download failed');bytes=Buffer.from(await r.arrayBuffer());await writeFile(archive,bytes);}if(createHash('sha256').update(bytes).digest('hex')!==expected)throw Error('Official runtime hash mismatch');
const stamp=new Date().toISOString().replace(/[:.]/g,'-'),stage=path.join(root,'build','windows-'+stamp),app=path.join(stage,'app');await mkdir(path.join(app,'server'),{recursive:true});await mkdir(path.join(stage,'runtime'),{recursive:true});
const unpacked=unzipSync(bytes),prefix=`node-${version}-win-x64/`;for(const name of ['node.exe','LICENSE']){if(!unpacked[prefix+name])throw Error('Runtime archive lacks '+name);await writeFile(path.join(stage,'runtime',name),unpacked[prefix+name]);}
await build({entryPoints:['server/index.mjs'],outfile:path.join(app,'server','index.mjs'),bundle:true,platform:'node',format:'esm',target:'node24',packages:'bundle',sourcemap:false,legalComments:'eof',banner:{js:"import {createRequire as __fxCreateRequire} from 'node:module';const require=__fxCreateRequire(import.meta.url);"}});
await mkdir(path.join(app,'scripts'),{recursive:true});
await build({entryPoints:['scripts/apply-update.mjs'],outfile:path.join(app,'scripts','apply-update.mjs'),bundle:true,platform:'node',format:'esm',target:'node24',sourcemap:false});
await build({entryPoints:['scripts/fx-mcp.mjs'],outfile:path.join(app,'scripts','fx-mcp.mjs'),bundle:true,platform:'node',format:'esm',target:'node24',sourcemap:false});
await build({entryPoints:['scripts/fx.mjs'],outfile:path.join(app,'scripts','fx.mjs'),bundle:true,platform:'node',format:'esm',target:'node24',sourcemap:false});
await cp(path.join(root,'scripts','fx-share.cmd'),path.join(stage,'fx.cmd'));
await cp(path.join(root,'scripts','recover-update.cmd'),path.join(stage,'恢复更新.cmd'));
await buildFrontend({build:{outDir:path.join(app,'dist'),emptyOutDir:false}});await mkdir(path.join(app,'public','curated'),{recursive:true});await cp(path.join(root,'public','curated','library.json'),path.join(app,'public','curated','library.json'));
await cp(path.join(root,'docs','WINDOWS-QUICKSTART.md'),path.join(stage,'使用说明.md'));await mkdir(path.join(stage,'docs'),{recursive:true});for(const name of ['ART-NOTICE.md'])await cp(path.join(root,'docs',name),path.join(stage,'docs',name));const csc=path.join(process.env.SystemRoot||'C:/Windows','Microsoft.NET','Framework64','v4.0.30319','csc.exe');const launcher=path.join(stage,'LuciferFX.exe');await exec(csc,['/nologo','/codepage:65001','/optimize+','/debug-','/target:winexe','/reference:System.Windows.Forms.dll','/reference:System.Web.Extensions.dll','/win32icon:'+path.join(root,'public','icons','launcher.ico'),'/out:'+launcher,path.join(root,'scripts','Launcher.cs')],{cwd:root,windowsHide:true});await rename(launcher,path.join(stage,'启动 Lucifer FX.exe'));
await mkdir(path.join(app,'dist','native'),{recursive:true});await exec(csc,['/nologo','/codepage:65001','/optimize+','/debug-','/target:winexe','/reference:System.Windows.Forms.dll','/reference:System.Drawing.dll','/reference:System.Web.Extensions.dll','/out:'+path.join(app,'dist','native','DesktopBridge.exe'),path.join(root,'server','DesktopBridge.cs')],{cwd:root,windowsHide:true});

const licenses=[];for(const name of ['fflate','undici','pngjs','react','react-dom','scheduler','tslib','lucide-react','@capacitor/core']){const base=path.join(root,'node_modules',name);let found=false;for(const f of ['LICENSE','LICENSE.txt','LICENSE.md','LICENSE.txt'])try{const license=await readFile(path.join(base,f),'utf8');licenses.push(`\n===== ${name} =====\n`+license);found=true;break;}catch{}if(!found)throw Error('Missing dependency license: '+name);}
const projectLicense=await readFile(path.join(root,'LICENSE'),'utf8');
await writeFile(path.join(stage,'THIRD-PARTY-LICENSES.txt'),'===== Lucifer NovelAI FX Share source code (artwork excluded) =====\n'+projectLicense+'\n'+licenses.join('\n'));
const manifest=[];async function inventory(dir){for(const e of await readdir(dir,{withFileTypes:true})){const target=path.join(dir,e.name);if(e.isDirectory())await inventory(target);else{const data=await readFile(target);manifest.push({path:path.relative(stage,target).replaceAll('\\','/'),bytes:data.length,sha256:createHash('sha256').update(data).digest('hex')});}}}await inventory(stage);await writeFile(path.join(stage,'manifest.json'),JSON.stringify({product:'Lucifer NovelAI FX Share',version:appVersion,node:version,runtimeArchiveSHA256:expected,files:manifest},null,2));
const zip=path.join(release,`Lucifer-NovelAI-FX-Share-${appVersion}-Windows-x64.zip`);try{await stat(zip);await cp(zip,path.join(tools,'windows-previous-'+stamp+'.zip'));}catch{}
const contents={};for(const entry of manifest)contents[entry.path]=await readFile(path.join(stage,entry.path));contents['manifest.json']=await readFile(path.join(stage,'manifest.json'));await writeFile(zip,zipSync(contents,{level:6}));const digest=createHash('sha256').update(await readFile(zip)).digest('hex');await writeFile(path.join(root,'.local','windows-package.json'),JSON.stringify({stage,zip,sha256:digest,files:manifest.length,node:version},null,2));console.log(JSON.stringify({zip,sha256:digest,files:manifest.length,node:version}));
