package app.luciferfx.share;
import org.json.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;import static app.luciferfx.share.FxStorage.object;
final class FxGallery {
 static final Map<String,JSONObject> cache=new LinkedHashMap<>();static long last=0;
 static String safe(String value){try{URI u=new URI(value);return "https".equals(u.getScheme())&&u.getUserInfo()==null&&u.getPort()==-1&&Arrays.asList("cdn.donmai.us","danbooru.donmai.us").contains(u.getHost())?value:null;}catch(Exception e){return null;}}
 static String variant(JSONObject p,String name){JSONObject asset=p.optJSONObject("media_asset");JSONArray a=asset==null?null:asset.optJSONArray("variants");if(a!=null)for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v!=null&&name.equals(v.optString("type")))return safe(v.optString("url"));}return null;}
 static String first(String... values){for(String v:values)if(v!=null&&!v.isEmpty())return v;return null;}
 static JSONObject normalize(JSONObject p)throws Exception{long id=p.optLong("id");String rating=p.optString("rating");if(id<1||p.optBoolean("is_deleted")||p.optBoolean("is_banned")||!Arrays.asList("g","s","q","e").contains(rating))return null;JSONObject tags=new JSONObject();for(String group:new String[]{"artist","character","copyright","general","meta"}){LinkedHashSet<String> words=new LinkedHashSet<>(Arrays.asList(p.optString("tag_string_"+group).split("\\s+")));words.remove("");List<String> limited=new ArrayList<>(words);tags.put(group,new JSONArray(limited.subList(0,Math.min(1500,limited.size()))));}String original=Arrays.asList("jpg","jpeg","png","webp","gif","avif").contains(p.optString("file_ext"))?first(variant(p,"original"),safe(p.optString("file_url"))):null;return object("id",id,"rating",rating,"score",p.optInt("score"),"favorites",p.optInt("fav_count"),"width",p.optInt("image_width"),"height",p.optInt("image_height"),"createdAt",p.opt("created_at"),"pageUrl","https://danbooru.donmai.us/posts/"+id,"thumbnail",first(variant(p,"360x360"),safe(p.optString("preview_file_url"))),"preview",first(variant(p,"720x720"),variant(p,"sample"),safe(p.optString("large_file_url")),safe(p.optString("preview_file_url"))),"original",original,"tags",tags,"rawTags",p.optString("tag_string"));}
 static JSONObject posts(FxHttp http,Map<String,String> q)throws Exception{
  String text=FxRuntime.query(q,"q","").trim(),rating=FxRuntime.query(q,"rating","g"),sort=FxRuntime.query(q,"sort","latest"),period=FxRuntime.query(q,"period","all");int limit=Math.max(12,Math.min(48,Integer.parseInt(FxRuntime.query(q,"pageSize","24"))));int page=Integer.parseInt(FxRuntime.query(q,"page","1"));if(text.length()>240||text.matches("(?s).*[\\r\\n\\x00-\\x1f].*")||text.matches("(?i).*(?:^|\\s)[~-]?(?:rating|order|date|age|limit):.*")||!Arrays.asList("g","s","q","e","all").contains(rating)||!Arrays.asList("latest","score","favorites").contains(sort)||!Arrays.asList("all","today","week","month").contains(period)||page<1||page>1000)throw new FxRuntime.ApiError(400,"invalid_query","图库筛选参数无效");String order=sort.equals("latest")?"id_desc":sort.equals("score")?"score":"favcount";String tags=(text+" "+(rating.equals("all")?"":"rating:"+rating)+(sort.equals("latest")?"":" order:"+order)).trim();if(!period.equals("all"))tags+=" date:>="+LocalDate.now(ZoneOffset.UTC).minusDays(period.equals("week")?7:period.equals("month")?30:0);String query="tags="+URLEncoder.encode(tags,"UTF-8")+"&limit="+limit+"&page="+page;long now=System.currentTimeMillis();synchronized(cache){JSONObject saved=cache.get(query);if(saved!=null&&now-saved.optLong("_at")<120000){JSONObject copy=FxStorage.cloneJson(saved);copy.remove("_at");copy.put("cached",true);return copy;}if(now-last<500)throw new FxRuntime.ApiError(429,"danbooru_rate_limit","操作稍快，请稍后再搜索");last=now;}
  JSONArray rows=new JSONArray(new String(http.publicGet("https://danbooru.donmai.us/posts.json?"+query,false),StandardCharsets.UTF_8)),posts=new JSONArray();for(int i=0;i<Math.min(limit,rows.length());i++){JSONObject p=normalize(rows.getJSONObject(i));if(p!=null&&(rating.equals("all")||rating.equals(p.optString("rating"))))posts.put(p);}JSONObject result=object("posts",posts,"page",page,"hasMore",rows.length()>=limit,"query",tags,"sourceUrl","https://danbooru.donmai.us/posts?"+query,"cached",false);synchronized(cache){JSONObject saved=FxStorage.cloneJson(result);saved.put("_at",now);cache.put(query,saved);while(cache.size()>32)cache.remove(cache.keySet().iterator().next());}return result;
 }
}
