package app.luciferfx.share;

import android.content.Intent;import android.util.Base64;import okhttp3.*;import org.json.*;
import java.io.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.util.*;import java.util.concurrent.*;import java.util.zip.*;
import static app.luciferfx.share.FxStorage.object;

final class FxGeneration {
 final FxRuntime runtime;final FxStorage store;final Object lock=new Object();final ExecutorService executor=Executors.newSingleThreadExecutor();volatile JSONObject active;volatile boolean comparison=false;volatile Call currentCall;
 FxGeneration(FxRuntime runtime)throws Exception{this.runtime=runtime;store=runtime.store;for(String folder:new String[]{"generation-jobs","comparisons"}){JSONArray records=store.list(folder);for(int i=0;i<records.length();i++){JSONObject record=records.getJSONObject(i);if(live(record.optString("status"))){record.put("status","interrupted");record.put("phase","unknown");record.put("error",object("code","interrupted","message","应用进程已结束；未确认任务不会自动重试。","billingUnknown",true));JSONArray jobs=record.optJSONArray("jobs");if(jobs==null&&record.optJSONObject("batch")!=null)jobs=record.getJSONObject("batch").getJSONArray("items");if(jobs!=null)for(int j=0;j<jobs.length();j++){JSONObject item=jobs.getJSONObject(j);if(item.optString("status").equals("running"))item.put("status","unknown");else if(item.optString("status").equals("queued"))item.put("status","not_submitted");}store.write(folder+"/"+record.getString("id")+".json",record);}if("interrupted".equals(record.optString("status"))){JSONArray pending=record.optJSONArray("jobs");if(pending==null&&record.optJSONObject("batch")!=null)pending=record.getJSONObject("batch").getJSONArray("items");if(pending==null){runtime.recordUsage(object("id","interrupted-"+record.getString("id"),"createdAt",record.optString("updatedAt",record.getString("createdAt")),"status","unknown","error",object("billingUnknown",true)),new JSONObject());}else for(int j=0;j<pending.length();j++){JSONObject item=pending.getJSONObject(j);if("unknown".equals(item.optString("status")))runtime.recordUsage(object("id","interrupted-"+record.getString("id")+"-"+j,"createdAt",record.optString("updatedAt",record.getString("createdAt")),"status","unknown","error",object("billingUnknown",true)),new JSONObject());}}}}}
 static boolean live(String s){return Arrays.asList("queued","running","stopping").contains(s);}
 boolean busy(){return active!=null;}
 JSONObject activeJob()throws Exception{synchronized(lock){return active!=null&&!comparison?object("id",active.getString("id"),"status",active.getString("status")):null;}}
 JSONObject activeComparison()throws Exception{synchronized(lock){return active!=null&&comparison?object("id",active.getString("id"),"status",active.getString("status")):null;}}
 static String hash(String text)throws Exception{byte[] b=MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8));StringBuilder out=new StringBuilder();for(byte v:b)out.append(String.format("%02x",v));return out.toString();}
 static JSONObject params(JSONObject payload)throws Exception{return payload.getJSONObject("novelai").getJSONObject("body").getJSONObject("parameters");}
 void validate(JSONObject payload,boolean opus)throws Exception{
  JSONObject n=payload.getJSONObject("novelai"),body=n.getJSONObject("body");String endpoint=n.getString("endpoint");if(!Arrays.asList("/ai/generate-image","/ai/generate-image-stream","/ai/upscale","/ai/augment-image").contains(endpoint))throw new FxRuntime.ApiError(400,"invalid_endpoint","未支持此图片操作");
  if(!endpoint.startsWith("/ai/generate-image")){if(opus)throw new FxRuntime.ApiError(400,"invalid_opus","逐张模式只支持普通文生图");return;}
  FxModelPolicy.validate(payload);JSONObject p=body.getJSONObject("parameters");for(String number:new String[]{"width","height","steps","n_samples","seed"}){Object raw=p.opt(number);if(!(raw instanceof Number)||!Double.isFinite(((Number)raw).doubleValue())||((Number)raw).doubleValue()!=Math.floor(((Number)raw).doubleValue()))throw new FxRuntime.ApiError(400,"invalid_parameters","整数参数格式无效");}int w=p.getInt("width"),h=p.getInt("height"),count=p.optInt("n_samples",1);if(w<64||h<64||w>4096||h>4096||w%64!=0||h%64!=0||count<1||count>8||p.getDouble("steps")<1||p.getDouble("scale")<0)throw new FxRuntime.ApiError(400,"invalid_parameters","图像参数无效");long seed=p.getLong("seed");if(seed<0||seed>4294967295L)throw new FxRuntime.ApiError(400,"invalid_seed","随机种子尚未解析");
  if(opus){if(!"generate".equals(body.optString("action"))||!Arrays.asList("nai-diffusion-5-full","nai-diffusion-4-5-full","nai-diffusion-4-5-curated").contains(body.optString("model"))||count!=1||(long)w*h>1048576||p.optDouble("steps")>28||!p.optString("image").isEmpty()||!p.optString("mask").isEmpty()||!p.optString("reference_image").isEmpty()||(p.optJSONArray("reference_image_multiple")!=null&&p.getJSONArray("reference_image_multiple").length()>0)||(p.optJSONArray("director_reference_images")!=null&&p.getJSONArray("director_reference_images").length()>0)||p.optBoolean("sm")||p.optBoolean("sm_dyn")||p.optBoolean("upscale"))throw new FxRuntime.ApiError(400,"invalid_opus","不符合 Opus 免费参数条件");JSONObject schema=new JSONObject(new String(store.asset("native/schema.json"),StandardCharsets.UTF_8)).getJSONObject("imageParameters");Iterator<String> it=p.keys();while(it.hasNext())if(!schema.has(it.next()))throw new FxRuntime.ApiError(400,"unknown_parameter","逐张模式不接受未核验的扩展参数");}
 }
 void policy(boolean opus)throws Exception{if(opus&&!"opus".equals(runtime.ledger().optString("pricingPolicy")))throw new FxRuntime.ApiError(400,"opus_unavailable","当前计数规则为付费 / 额度用尽，请先核实 Opus 额度。");}
 JSONObject publicJob(JSONObject record,boolean full)throws Exception{JSONObject copy=FxStorage.cloneJson(record);copy.remove("payloads");copy.remove("fingerprint");copy.put("elapsedMs",Math.max(0,(copy.has("finishedAt")?java.time.Instant.parse(copy.getString("finishedAt")).toEpochMilli():System.currentTimeMillis())-java.time.Instant.parse(copy.getString("createdAt")).toEpochMilli()));if(!full&&copy.optJSONArray("jobs")!=null){JSONArray jobs=copy.getJSONArray("jobs");for(int i=0;i<jobs.length();i++){jobs.getJSONObject(i).remove("payload");jobs.getJSONObject(i).remove("state");}}return copy;}
 void persist(JSONObject record,boolean compare)throws Exception{JSONObject snapshot=FxStorage.cloneJson(record);snapshot.remove("preview");store.write((compare?"comparisons/":"generation-jobs/")+record.getString("id")+".json",snapshot);}
 JSONObject get(String id)throws Exception{FxRuntime.uuid(id);synchronized(lock){JSONObject r=active!=null&&!comparison&&id.equals(active.optString("id"))?active:store.read("generation-jobs/"+id+".json",null);if(r==null)throw new FxRuntime.ApiError(404,"not_found","任务不存在，请先核对历史，不会自动重发。");return publicJob(r,false);}}
 JSONObject start(JSONObject request)throws Exception{synchronized(lock){String id=request.getString("clientRequestId");FxRuntime.uuid(id);JSONObject payload=FxStorage.cloneJson(request.getJSONObject("payload"));boolean opus=request.optBoolean("opusBatch");String fingerprint=hash(payload.toString()+"|"+opus);JSONObject previous=store.read("generation-jobs/"+id+".json",null);if(previous!=null){if(!fingerprint.equals(previous.optString("fingerprint")))throw new FxRuntime.ApiError(409,"idempotency_conflict","同一任务 ID 不能使用不同参数");return publicJob(previous,false);}if(busy())throw new FxRuntime.ApiError(409,"generation_busy","已有图片任务，请等待完成");validate(payload,false);policy(opus);if(request.optBoolean("preventDuplicate"))runtime.compat.assertNotDuplicate(payload);JSONArray payloads=new JSONArray(),items=new JSONArray();JSONObject p=payload.getJSONObject("novelai").getJSONObject("body").optJSONObject("parameters");int count=opus?p.optInt("n_samples"):1;if(opus&&!"nai-diffusion-5-full".equals(payload.getJSONObject("novelai").getJSONObject("body").optString("model")))throw new FxRuntime.ApiError(400,"invalid_opus","逐张模式目前只支持 V5 Full");if(opus&&(count<2||count>8))throw new FxRuntime.ApiError(400,"invalid_count","逐张模式需要 2–8 张");for(int i=0;i<count;i++){JSONObject child=FxStorage.cloneJson(payload);if(opus){JSONObject cp=params(child);cp.put("n_samples",1);cp.put("seed",(p.getLong("seed")+i)&0xffffffffL);if(cp.has("extra_noise_seed"))cp.put("extra_noise_seed",(cp.getLong("extra_noise_seed")+i)&0xffffffffL);child.put("n",1);validate(child,true);}payloads.put(child);items.put(object("index",i,"seed",p==null?0:params(child).optLong("seed"),"status","queued"));}JSONObject record=object("version",1,"kind","generation-job","id",id,"fingerprint",fingerprint,"status","queued","phase","queued","createdAt",FxRuntime.now(),"updatedAt",FxRuntime.now(),"timeoutMs",600000,"width",p==null?1024:p.optInt("width",1024),"height",p==null?1024:p.optInt("height",1024),"receivedBytes",0,"payloads",payloads);if(opus)record.put("batch",object("mode","opus-single","count",count,"items",items));persist(record,false);active=record;comparison=false;dispatch(record,false);return publicJob(record,false);}}
 JSONObject stop(String id)throws Exception{synchronized(lock){JSONObject result=get(id);if(active!=null&&id.equals(active.optString("id"))){active.put("stopRequested",true);active.put("status","stopping");if(!active.has("batch")&&currentCall!=null)currentCall.cancel();persist(active,false);}return result;}}
 JSONArray comparisons()throws Exception{JSONArray records=store.list("comparisons"),out=new JSONArray();for(int i=records.length()-1;i>=Math.max(0,records.length()-20);i--)out.put(publicJob(records.getJSONObject(i),false));return out;}
 JSONObject comparison(String id,boolean full)throws Exception{FxRuntime.uuid(id);synchronized(lock){JSONObject r=active!=null&&comparison&&id.equals(active.optString("id"))?active:store.read("comparisons/"+id+".json",null);if(r==null)throw new FxRuntime.ApiError(404,"not_found","对照不存在");return publicJob(r,full);}}
 JSONObject startComparison(JSONObject request)throws Exception{synchronized(lock){if(busy())throw new FxRuntime.ApiError(409,"generation_busy","已有生成任务");JSONObject plan=FxStorage.cloneJson(request.getJSONObject("plan")),config=request.getJSONObject("config");String id=UUID.randomUUID().toString(),mode=plan.optString("mode");int rounds=plan.optInt("rounds"),variants=mode.equals("AB")?2:mode.equals("ABC")?3:0;JSONArray jobs=plan.getJSONArray("jobs"),payloads=new JSONArray();if(!config.optBoolean("enabled")||variants==0||rounds<1||rounds>20||jobs.length()!=rounds*variants)throw new FxRuntime.ApiError(400,"invalid_comparison","对照计划无效");boolean opus=plan.optBoolean("noAnlas");policy(opus);for(int i=0;i<jobs.length();i++){JSONObject job=jobs.getJSONObject(i),payload=job.getJSONObject("payload");validate(payload,opus);if(params(payload).optInt("n_samples")!=1)throw new FxRuntime.ApiError(400,"invalid_count","对照每个方案必须为 1 张");job.put("index",i);job.put("status","queued");payloads.put(payload);}plan.put("id",id);plan.put("kind","comparison");plan.put("status","queued");plan.put("phase","queued");plan.put("createdAt",FxRuntime.now());plan.put("payloads",payloads);persist(plan,true);active=plan;comparison=true;dispatch(plan,true);return publicJob(plan,false);}}
 JSONObject stopComparison(String id)throws Exception{synchronized(lock){JSONObject result=comparison(id,false);if(active!=null&&id.equals(active.optString("id"))){active.put("stopRequested",true);active.put("status","stopping");persist(active,true);}return result;}}
 void dispatch(JSONObject record,boolean compare)throws Exception{try{startService();executor.execute(()->execute(record,compare));}catch(Exception e){record.put("status",compare?"failed":"error");record.put("error",object("code","background_unavailable","message","后台任务无法启动；本次尚未提交，请回到应用再操作。","billingUnknown",false));persist(record,compare);active=null;comparison=false;throw new FxRuntime.ApiError(503,"background_unavailable","后台任务无法启动；本次尚未提交，请回到应用再操作。");}}
 void startService()throws Exception{MainActivity.requestTaskNotifications();FxGenerationService.begin(runtime.context);}
 void haltFromSystem(){synchronized(lock){if(active!=null)try{active.put("stopRequested",true);active.put("status","stopping");if(currentCall!=null)currentCall.cancel();persist(active,comparison);}catch(Exception ignored){}}}
 void execute(JSONObject record,boolean compare){
  try{JSONArray payloads=record.getJSONArray("payloads"),items=compare?record.getJSONArray("jobs"):record.has("batch")?record.getJSONObject("batch").getJSONArray("items"):new JSONArray().put(object("index",0,"status","queued"));
   synchronized(lock){record.put("status",record.optBoolean("stopRequested")?"stopping":"running");persist(record,compare);}
   for(int i=0;i<payloads.length();i++){
    JSONObject item=items.getJSONObject(i),payload=payloads.getJSONObject(i);synchronized(lock){if(record.optBoolean("stopRequested")){item.put("status","not_submitted");continue;}item.put("status","running");record.put("receivedBytes",0);record.put("phase","preparing");record.remove("preview");record.remove("requestId");persist(record,compare);}
    try{policy(compare?record.optBoolean("noAnlas"):record.has("batch"));JSONObject result=generate(payload,record,compare,item);synchronized(lock){item.put("result",result);item.put("status","success");if(!compare&&!record.has("batch"))record.put("result",result);}}
    catch(Exception e){synchronized(lock){JSONObject error=errorInfo(e);item.put("status",error.optBoolean("billingUnknown")?"unknown":"error");item.put("error",error);record.put("error",error);record.put("stopRequested",true);record.put("status",compare?"failed":"error");}}
    synchronized(lock){record.remove("preview");persist(record,compare);}
   }
   synchronized(lock){if(!Arrays.asList("error","failed").contains(record.optString("status")))record.put("status",record.optBoolean("stopRequested")?"stopped":compare?"complete":"success");record.put("phase",record.optBoolean("stopRequested")?"unknown":"complete");}
  }catch(Exception e){synchronized(lock){try{record.put("status",compare?"failed":"error");record.put("error",object("code","local_error","message","本地任务未能完成，请先核对历史，不会自动重试。","billingUnknown",true));}catch(Exception ignored){}}}
  finally{synchronized(lock){try{record.put("finishedAt",FxRuntime.now());record.remove("preview");persist(record,compare);}catch(Exception ignored){}currentCall=null;runtime.context.stopService(new Intent(runtime.context,FxGenerationService.class));if(active==record)active=null;comparison=false;}}
 }
 void progress(JSONObject job,boolean compare,String phase,long bytes,String requestId)throws Exception{synchronized(lock){job.put("phase",phase);job.put("receivedBytes",bytes);job.put("updatedAt",FxRuntime.now());if(requestId!=null)job.put("requestId",requestId);persist(job,compare);}}
 JSONObject errorInfo(Exception e)throws Exception { boolean unknown=!(e instanceof FxRuntime.ApiError&&(((FxRuntime.ApiError)e).status<500||((FxRuntime.ApiError)e).code.equals("gateway_connect_error")));return object("code",e instanceof FxRuntime.ApiError?((FxRuntime.ApiError)e).code:"generation_error","message",e.getMessage()==null?"请求未完成":e.getMessage(),"billingUnknown",unknown); }
 JSONObject generate(JSONObject payload,JSONObject job,boolean compare,JSONObject item)throws Exception{
  String id=System.currentTimeMillis()+"-"+UUID.randomUUID().toString().substring(0,8),token=store.token();long start=System.currentTimeMillis();JSONObject nativeRequest=payload.getJSONObject("novelai"),body=nativeRequest.getJSONObject("body"),p=body.optJSONObject("parameters");JSONObject entry=object("id",id,"createdAt",FxRuntime.now(),"status","success","model",body.optString("model",payload.optString("model")),"prompt",body.optString("input",payload.optString("prompt")),"endpoint",nativeRequest.optString("endpoint"),"action",body.optString("action","generate"),"images",new JSONArray(),"requestUrl","/api/results/"+id+"-request.json");
  if(compare)entry.put("comparison",object("groupId",job.optString("id"),"variant",item.optString("variant"),"round",item.optInt("round"),"seed",item.optLong("seed")));else if(job.has("batch"))entry.put("batch",object("id",job.optString("id"),"index",item.optInt("index"),"count",job.getJSONObject("batch").optInt("count")));
  store.write("results/"+id+"-request.json",new JSONObject(payload.toString().replace(token,"[redacted]")));
  FxHttp.SubmissionTrace trace=new FxHttp.SubmissionTrace();
  try{
   Call prepared=runtime.http.provider(payload,"/v1/images/generations","POST");currentCall=runtime.http.client.newBuilder().eventListener(trace).build().newCall(prepared.request());progress(job,compare,"connecting",0,null);
   try(Response response=currentCall.execute()){
    String requestId=response.header("x-request-id"),type=response.header("Content-Type","application/octet-stream");entry.put("requestId",requestId);entry.put("aggregationRequestId",response.header("x-oneapi-request-id"));progress(job,compare,"waiting_result",0,requestId);
    if(!response.isSuccessful())throw runtime.http.error(response.code(),FxStorage.bounded(response.body().byteStream(),2*1024*1024));
    List<byte[]> images=new ArrayList<>();int expected=p==null?1:p.optInt("n_samples",1);
    if(type.contains("text/event-stream")){
     BufferedReader reader=new BufferedReader(new InputStreamReader(response.body().byteStream(),StandardCharsets.UTF_8));String line;StringBuilder frame=new StringBuilder();long received=0;Map<Integer,byte[]> finals=new TreeMap<>();
     while((line=reader.readLine())!=null){received+=line.length();if(received>64*1024*1024||frame.length()>48*1024*1024)throw new IOException("图像流超过大小限制");if(line.isEmpty()){consumeFrame(frame.toString(),finals,job);frame.setLength(0);progress(job,compare,"receiving",received,requestId);}else frame.append(line).append('\n');}if(frame.length()>0)consumeFrame(frame.toString(),finals,job);images.addAll(finals.values());
    }else{
     ByteArrayOutputStream received=new ByteArrayOutputStream();byte[] chunk=new byte[32768];int n;long last=0;InputStream input=response.body().byteStream();while((n=input.read(chunk))!=-1){if(received.size()+n>64*1024*1024)throw new IOException("图片响应超过大小限制");received.write(chunk,0,n);if(System.currentTimeMillis()-last>800){progress(job,compare,"receiving",received.size(),requestId);last=System.currentTimeMillis();}}byte[] bytes=received.toByteArray();progress(job,compare,"decoding",bytes.length,requestId);
     String rawName=id+"-raw."+(bytes.length>2&&bytes[0]=='P'&&bytes[1]=='K'?"zip":type.contains("json")?"json":"bin");Files.write(store.file("results/"+rawName).toPath(),bytes);entry.put("rawUrl","/api/results/"+rawName);
     if(bytes.length>2&&bytes[0]=='P'&&bytes[1]=='K'){long total=0;try(ZipInputStream zip=new ZipInputStream(new ByteArrayInputStream(bytes))){ZipEntry z;while((z=zip.getNextEntry())!=null){if(z.isDirectory()||!z.getName().matches("(?i).*\\.(png|jpe?g|webp|gif)$"))continue;byte[] image=FxStorage.bounded(zip,32*1024*1024);total+=image.length;if(total>32*1024*1024||images.size()>=8)throw new IOException("解压图片超过大小限制");images.add(image);}}}
     else if(type.startsWith("image/"))images.add(bytes);
     else {JSONObject json=new JSONObject(new String(bytes,StandardCharsets.UTF_8));collect(json,images);JSONArray data=json.optJSONArray("data");if(data!=null)for(int k=0;k<data.length();k++){JSONObject value=data.optJSONObject(k);if(value==null||!value.has("url"))continue;HttpUrl uri=HttpUrl.get(value.getString("url")),base=HttpUrl.get(store.config().getString("baseURL"));if(!uri.username().isEmpty()||!uri.password().isEmpty()||!uri.scheme().equals(base.scheme())||!uri.host().equals(base.host())||uri.port()!=base.port()||!uri.encodedPath().startsWith("/v1/images/files/"))throw new IOException("图片链接不属于已配置的服务地址");Call call=runtime.http.client.newCall(new Request.Builder().url(uri.toString()).get().build());try(Response image=call.execute()){if(!image.isSuccessful())throw new IOException("图片下载失败");images.add(FxStorage.bounded(image.body().byteStream(),32*1024*1024));}}}
    }
    if(images.size()!=expected)throw new IOException("仅收到 "+images.size()+"/"+expected+" 张最终图片；不会自动重试。");
    progress(job,compare,"saving",job.optLong("receivedBytes"),requestId);
    for(int i=0;i<images.size();i++){byte[] bytes=images.get(i);String mime=imageType(bytes),extension=mime.equals("image/png")?"png":mime.equals("image/jpeg")?"jpg":mime.equals("image/webp")?"webp":"gif";JSONObject recipe=(JSONObject)clean(body,token);if(expected>1&&recipe.optJSONObject("parameters")!=null)recipe.getJSONObject("parameters").remove("seed");bytes=metadata(bytes,recipe);String name=id+"-"+(i+1)+"."+extension;Files.write(store.file("results/"+name).toPath(),bytes);JSONObject im=object("name",name,"url","/api/results/"+name,"savedToLibrary",false,"outputName","Lucifer-FX-"+name);android.graphics.BitmapFactory.Options dimensions=new android.graphics.BitmapFactory.Options();dimensions.inJustDecodeBounds=true;android.graphics.BitmapFactory.decodeByteArray(bytes,0,bytes.length,dimensions);if(dimensions.outWidth>0&&dimensions.outHeight>0){im.put("width",dimensions.outWidth);im.put("height",dimensions.outHeight);}if(p!=null&&expected==1)im.put("seed",p.optLong("seed"));try{if(store.config().optBoolean("autoSaveOutput",true))im.put("outputPath",store.saveTo(store.config().getString("outputDirectory"),"Lucifer-FX-"+name,mime,bytes));}catch(Exception error){JSONArray warnings=entry.optJSONArray("warnings");if(warnings==null){warnings=new JSONArray();entry.put("warnings",warnings);}warnings.put("外部目录写入失败，图片已保存在应用数据，可继续查看或导出。");}entry.getJSONArray("images").put(im);}
   }
  }catch(Exception error){Exception classified=!trace.submitted&&!(error instanceof FxRuntime.ApiError)?new FxRuntime.ApiError(502,"gateway_connect_error","连接服务失败，请求尚未发送；检查网络或接口地址后可主动重试。"):error;entry.put("status","error");entry.put("error",errorInfo(classified));throw classified;}
  finally{entry.put("durationMs",System.currentTimeMillis()-start);if("success".equals(entry.optString("status"))&&entry.getJSONArray("images").length()>0)entry.put("generationFingerprint",FxCompat.fingerprint(payload));store.write("history/"+id+".json",entry);runtime.recordUsage(entry,payload);currentCall=null;}
  return entry;
 }
 void consumeFrame(String frame,Map<Integer,byte[]> finals,JSONObject job)throws Exception{String event="",data="";for(String line:frame.split("\n")){if(line.startsWith("event:"))event=line.substring(6).trim();if(line.startsWith("data:"))data+=line.substring(5).trim();}if(data.isEmpty()||data.equals("[DONE]"))return;JSONObject value=new JSONObject(data);String type=value.optString("type",event);if(type.equals("error")||value.has("error"))throw new IOException("上游图像流返回错误");List<byte[]> images=new ArrayList<>();collect(value,images);if(type.equals("final")){int index=value.optInt("samp_ix",0);for(int i=0;i<images.size();i++)finals.put(index+i,images.get(i));}else if(value.has("image")&&value.optString("image").length()<4*1024*1024){synchronized(lock){job.put("preview","data:image/jpeg;base64,"+value.optString("image"));job.put("streamEvents",job.optInt("streamEvents")+1);}}}
 static void collect(Object value,List<byte[]> out)throws Exception{if(value instanceof JSONObject){JSONObject o=(JSONObject)value;for(String key:new String[]{"b64_json","image"})if(o.opt(key) instanceof String){String s=o.getString(key);if(s.startsWith("data:"))s=s.substring(s.indexOf(',')+1);try{byte[] bytes=Base64.decode(s,Base64.DEFAULT);imageType(bytes);out.add(bytes);}catch(Exception ignored){}}for(String key:new String[]{"data","images","output"})if(o.has(key))collect(o.get(key),out);}else if(value instanceof JSONArray){JSONArray a=(JSONArray)value;for(int i=0;i<a.length();i++)collect(a.get(i),out);}}
 static String imageType(byte[] b)throws IOException{if(b.length>8&&b[0]==(byte)137&&b[1]=='P')return "image/png";if(b.length>2&&b[0]==(byte)255&&b[1]==(byte)216)return "image/jpeg";if(b.length>12&&new String(b,0,4,StandardCharsets.US_ASCII).equals("RIFF"))return "image/webp";if(b.length>6&&new String(b,0,3,StandardCharsets.US_ASCII).equals("GIF"))return "image/gif";if(b.length>16&&new String(b,4,4,StandardCharsets.US_ASCII).equals("ftyp")&&Arrays.asList("avif","avis").contains(new String(b,8,4,StandardCharsets.US_ASCII)))return "image/avif";throw new IOException("图片格式无效");}
 static Object clean(Object value,String token)throws Exception{if(value instanceof JSONObject){JSONObject result=new JSONObject(),source=(JSONObject)value;Iterator<String> keys=source.keys();while(keys.hasNext()){String key=keys.next();if(key.matches("(?i)^(source|mask|image|images|reference_image.*|director_reference_images|controlnet_condition|encoded|encoding|encodings|dataURL|b64_json|authorization|api[_-]?key|access[_-]?token|refresh[_-]?token|password|secret|cookie|headers)$"))continue;result.put(key,clean(source.get(key),token));}return result;}if(value instanceof JSONArray){JSONArray out=new JSONArray(),a=(JSONArray)value;for(int i=0;i<a.length();i++)out.put(clean(a.get(i),token));return out;}if(value instanceof String)return ((String)value).replace(token,"[redacted]").replaceAll("(?i)Bearer\\s+[A-Za-z0-9._~+/=-]+","Bearer [redacted]");return value;}
 static byte[] metadata(byte[] b,JSONObject recipe)throws Exception{if(!imageType(b).equals("image/png"))return b;ByteArrayOutputStream out=new ByteArrayOutputStream();out.write(b,0,8);int at=8;while(at+12<=b.length){int len=ByteBuffer.wrap(b,at,4).getInt();if(len<0||at+len+12>b.length)throw new IOException("PNG 数据不完整");String type=new String(b,at+4,4,StandardCharsets.US_ASCII);if(type.equals("IEND")){byte[] json=recipe.toString().getBytes(StandardCharsets.UTF_8),prefix="novelai_studio\0\0\0\0\0".getBytes(StandardCharsets.US_ASCII);if(json.length>2*1024*1024)throw new IOException("参数元数据过大");ByteArrayOutputStream payload=new ByteArrayOutputStream();payload.write(prefix);payload.write(json);byte[] data=payload.toByteArray(),name="iTXt".getBytes(StandardCharsets.US_ASCII);out.write(ByteBuffer.allocate(4).putInt(data.length).array());out.write(name);out.write(data);CRC32 crc=new CRC32();crc.update(name);crc.update(data);out.write(ByteBuffer.allocate(4).putInt((int)crc.getValue()).array());}out.write(b,at,len+12);at+=len+12;}return out.toByteArray();}
 static byte[] privateSharingImage(byte[] bytes)throws Exception{
 android.graphics.BitmapFactory.Options options=new android.graphics.BitmapFactory.Options();options.inJustDecodeBounds=true;android.graphics.BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(options.outWidth<1||options.outHeight<1||(long)options.outWidth*options.outHeight>32000000)throw new IOException("图片超过安全导出尺寸");
 android.graphics.Bitmap bitmap=android.graphics.BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(bitmap==null)throw new IOException("图片无法读取");android.graphics.Bitmap clean=bitmap.copy(android.graphics.Bitmap.Config.ARGB_8888,true);bitmap.recycle();try{int[] row=new int[clean.getWidth()];for(int y=0;y<clean.getHeight();y++){clean.getPixels(row,0,row.length,0,y,row.length,1);for(int x=0;x<row.length;x++){int a=row[x]>>>24;if(a>0)a|=1;row[x]=(a<<24)|(row[x]&0x00fefefe);}clean.setPixels(row,0,row.length,0,y,row.length,1);}ByteArrayOutputStream out=new ByteArrayOutputStream();if(!clean.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out))throw new IOException("PNG 导出失败");return out.toByteArray();}finally{clean.recycle();}
 }
 static byte[] stripMetadata(byte[] b)throws Exception{String mime=imageType(b);if(mime.equals("image/png")){ByteArrayOutputStream out=new ByteArrayOutputStream();out.write(b,0,8);int at=8;while(at+12<=b.length){int len=ByteBuffer.wrap(b,at,4).getInt();if(len<0||at+len+12>b.length)throw new IOException("PNG 数据不完整");String type=new String(b,at+4,4,StandardCharsets.US_ASCII);if(!Arrays.asList("tEXt","zTXt","iTXt","eXIf").contains(type))out.write(b,at,len+12);at+=len+12;}return out.toByteArray();}if(mime.equals("image/jpeg")){ByteArrayOutputStream out=new ByteArrayOutputStream();out.write(b,0,2);int at=2;while(at+4<=b.length){int marker=b[at+1]&255;if(marker==218||marker==217){out.write(b,at,b.length-at);break;}int len=((b[at+2]&255)<<8)|(b[at+3]&255);if(len<2||at+len+2>b.length)throw new IOException("JPEG 数据不完整");if(marker!=225&&marker!=237&&marker!=254)out.write(b,at,len+2);at+=len+2;}return out.toByteArray();}if(mime.equals("image/webp")){ByteArrayOutputStream out=new ByteArrayOutputStream();out.write(b,0,12);int at=12;while(at+8<=b.length){String type=new String(b,at,4,StandardCharsets.US_ASCII);int len=ByteBuffer.wrap(b,at+4,4).order(ByteOrder.LITTLE_ENDIAN).getInt(),size=8+len+(len&1);if(len<0||at+size>b.length)throw new IOException("WebP 数据不完整");if(!type.equals("EXIF")&&!type.equals("XMP ")){byte[] chunk=Arrays.copyOfRange(b,at,at+size);if(type.equals("VP8X"))chunk[8]&=~12;out.write(chunk);}at+=size;}byte[] result=out.toByteArray();ByteBuffer.wrap(result,4,4).order(ByteOrder.LITTLE_ENDIAN).putInt(result.length-8);return result;}throw new IOException("此图片格式暂不支持去参数导出");}
}
