package app.luciferfx.share;
import okhttp3.*;import org.json.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.TimeUnit;
final class FxHttp {
 static final MediaType JSON=MediaType.get("application/json; charset=utf-8");
 final OkHttpClient client=new OkHttpClient.Builder().retryOnConnectionFailure(false).followRedirects(false).followSslRedirects(false).protocols(Collections.singletonList(Protocol.HTTP_1_1)).connectTimeout(30,TimeUnit.SECONDS).readTimeout(0,TimeUnit.SECONDS).callTimeout(600,TimeUnit.SECONDS).build();
 static final class SubmissionTrace extends okhttp3.EventListener { volatile boolean submitted; @Override public void requestHeadersStart(Call call){submitted=true;} }
 final FxStorage store;FxHttp(FxStorage store){this.store=store;}
 static String join(String base,String route){return base.replaceAll("/+$","")+"/"+route.replaceAll("^/+","");}
 Call provider(JSONObject payload,String route,String method)throws Exception{
  JSONObject cfg=store.config();String provider=cfg.optString("provider"),base=cfg.optString("baseURL");if(base.isEmpty())throw new FxRuntime.ApiError(409,"not_configured","请配置 API 地址");JSONObject wire=payload;
  if(route.equals("/v1/images/generations")&&!provider.equals("openai")){JSONObject nativeRequest=payload.getJSONObject("novelai");route=nativeRequest.getString("endpoint");wire=nativeRequest.getJSONObject("body");}
  if(!Arrays.asList("/v1/images/generations","/v1/models","/user/subscription","/ai/generate-image","/ai/generate-image-stream","/ai/upscale","/ai/augment-image","/ai/encode-vibe").contains(route))throw new FxRuntime.ApiError(400,"unsupported_route","未开放此上游操作");
  if(provider.equals("openai"))base=base.replaceAll("/v1$","");Request.Builder request=new Request.Builder().url(join(base,route)).header("Authorization","Bearer "+store.token()).header("Accept","*/*");if(method.equals("GET"))request.get();else request.method(method,RequestBody.create(wire.toString(),JSON));return client.newCall(request.build());
 }
 JSONObject readOnly(String route)throws Exception{Call call=provider(null,route,"GET");call.timeout().timeout(10,TimeUnit.SECONDS);try(Response r=call.execute()){byte[] bytes=FxStorage.bounded(r.body().byteStream(),4*1024*1024);if(!r.isSuccessful())throw error(r.code(),bytes);return new JSONObject(new String(bytes,java.nio.charset.StandardCharsets.UTF_8));}}
 FxRuntime.ApiError error(int code,byte[] body)throws Exception{return new FxRuntime.ApiError(code>=400&&code<=599?code:502,"upstream_"+code,"接口返回 HTTP "+code+"；请核对连接、余额或服务状态。未自动重试。");}
 byte[] publicGet(String url,boolean image)throws Exception{URI u=new URI(url);if(!"https".equals(u.getScheme())||u.getUserInfo()!=null||u.getPort()!=-1||!Arrays.asList("danbooru.donmai.us","cdn.donmai.us").contains(u.getHost()))throw new FxRuntime.ApiError(400,"invalid_image_url","不支持的图库地址");if(image&&!u.getPath().matches("/(?:original|sample|preview|360x360|720x720|180x180|data)/.*")&&!u.getPath().matches("/[^?]+\\.(?:jpg|jpeg|png|webp|gif|avif)"))throw new FxRuntime.ApiError(400,"invalid_image_path","图片地址无效");Request q=new Request.Builder().url(url).header("User-Agent","LuciferNovelAIFX-Share/1.0 (anonymous reference browser)").header("Referer","https://danbooru.donmai.us/").header("Accept",image?"image/*":"application/json").get().build();Call call=client.newCall(q);call.timeout().timeout(image?20:10,TimeUnit.SECONDS);try(Response r=call.execute()){if(!r.isSuccessful())throw new FxRuntime.ApiError(r.code()==429?429:502,"danbooru_unavailable","Danbooru 返回 HTTP "+r.code()+"，请稍后重试或在原站查看。");if(image&&!r.header("Content-Type","").startsWith("image/"))throw new IOException("上游没有返回图片");return FxStorage.bounded(r.body().byteStream(),image?32*1024*1024:4*1024*1024);}}
}
