package app.luciferfx.share;

import org.json.*;
import java.io.*;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import static app.luciferfx.share.FxStorage.object;

/** Native gallery reads legacy history in place; image indices never change. */
final class FxLibrary {
 final FxRuntime r; final FxStorage s; final Map<String,JSONObject> previews=new LinkedHashMap<>();String lastError="";
 FxLibrary(FxRuntime runtime){r=runtime;s=r.store;}
 JSONObject annotations()throws Exception{return s.read("generated-library/annotations.json",object("format","lucifer-generated-library-annotations","version",1,"items",new JSONObject()));}
 static void key(String k)throws Exception{if(!k.matches("\\d+-[a-f0-9]{8}:\\d{1,2}"))throw new FxRuntime.ApiError(400,"invalid_image","图片索引无效");}
 JSONObject annotation(JSONObject patch)throws Exception{JSONObject out=new JSONObject();if(patch.has("favorite")){if(!(patch.get("favorite") instanceof Boolean))throw new FxRuntime.ApiError(400,"invalid_annotation","收藏状态无效");out.put("favorite",patch.getBoolean("favorite"));}if(patch.has("tags")){JSONArray tags=patch.getJSONArray("tags"),clean=new JSONArray();Set<String> seen=new HashSet<>();if(tags.length()>24)throw new FxRuntime.ApiError(400,"invalid_annotation","最多 24 个标签");for(int i=0;i<tags.length();i++){if(!(tags.get(i) instanceof String)||tags.getString(i).length()>40)throw new FxRuntime.ApiError(400,"invalid_annotation","标签不能超过 40 字");String tag=tags.getString(i).trim();if(!tag.isEmpty()&&seen.add(tag))clean.put(tag);}out.put("tags",clean);}return out;}
 JSONObject importAnnotations(JSONObject bundle)throws Exception {if(!"lucifer-generated-library-annotations".equals(bundle.optString("format"))||bundle.optInt("version")!=1)throw new FxRuntime.ApiError(400,"invalid_annotation","注释备份格式无效");JSONObject incoming=bundle.getJSONObject("items"),validated=new JSONObject();if(incoming.length()>100000)throw new FxRuntime.ApiError(400,"invalid_annotation","注释数量过多");Iterator<String> keys=incoming.keys();while(keys.hasNext()){String k=keys.next();key(k);validated.put(k,annotation(incoming.getJSONObject(k)));}JSONObject all=annotations();keys=validated.keys();while(keys.hasNext()){String k=keys.next();all.getJSONObject("items").put(k,validated.get(k));}s.write("generated-library/annotations.json",all);return object("imported",validated.length());}
 JSONObject row(JSONObject e,int i,JSONObject annotations)throws Exception{
  JSONObject image=e.getJSONArray("images").getJSONObject(i);String id=e.getString("id"),k=id+":"+i,name=image.optString("name");JSONObject a=annotations.optJSONObject(k);if(a==null)a=new JSONObject();JSONObject payload=s.read("results/"+id+"-request.json",null),metadata=payload==null?new JSONObject():payload.optJSONObject("novelai");metadata=metadata==null?new JSONObject():metadata.optJSONObject("body");if(metadata==null)metadata=new JSONObject();JSONObject p=metadata.optJSONObject("parameters");Object seed=image.opt("seed");if(seed==null&&p!=null)seed=p.opt("seed");
  return object("key",k,"result_id",id,"image_index",i,"created_at",e.optString("createdAt"),"model",e.optString("model"),"mode",e.optString("action","generate"),"seed",seed,"prompt",e.optString("prompt"),"final_prompt",metadata.optString("input",e.optString("prompt")),"filename",name,"url",image.optString("url"),"request_url",e.optString("requestUrl"),"metadata",FxGeneration.clean(metadata,"\u0000"),"hasFile",name.matches("[a-zA-Z0-9_.-]+")&&s.file("results/"+name).isFile(),"favorite",a.optBoolean("favorite"),"tags",a.optJSONArray("tags")==null?new JSONArray():a.getJSONArray("tags"));
 }
 JSONArray rows(Map<String,String> q)throws Exception{
  JSONArray history=r.history(),out=new JSONArray();JSONObject annotations=annotations().getJSONObject("items");String text=FxRuntime.query(q,"q","").toLowerCase(Locale.ROOT),group=FxRuntime.query(q,"groupBy","date"),value=FxRuntime.query(q,"groupValue","");
  for(int n=0;n<history.length();n++){JSONObject e=history.getJSONObject(n);JSONArray images=e.optJSONArray("images");if(images==null)continue;for(int i=0;i<images.length();i++){JSONObject image=images.optJSONObject(i);if(image==null||!image.isNull("deletedAt"))continue;JSONObject item=row(e,i,annotations);String date=item.optString("created_at");date=date.length()>=10?date.substring(0,10):"";
   if(!text.isEmpty()&&!(item.optString("prompt")+item.optString("final_prompt")+item.optString("filename")+item.getJSONArray("tags")).toLowerCase(Locale.ROOT).contains(text))continue;
   boolean match=true;for(String f:new String[]{"seed","model","mode"})if(!FxRuntime.query(q,f,"").isEmpty()&&!q.get(f).equals(String.valueOf(item.opt(f))))match=false;if(!match)continue;
   if(("1".equals(q.get("favorite"))||"true".equals(q.get("favorite")))&&!item.optBoolean("favorite"))continue;
   if(!FxRuntime.query(q,"from","").isEmpty()&&date.compareTo(q.get("from"))<0||!FxRuntime.query(q,"to","").isEmpty()&&date.compareTo(q.get("to"))>0)continue;
   if(!value.isEmpty()&&!(group.equals("date")?date.equals(value):group.equals("model")?item.optString("model").equals(value):contains(item.getJSONArray("tags"),value)))continue;out.put(item);
  }}return out;
 }
 static boolean contains(JSONArray a,String value){for(int i=0;i<a.length();i++)if(value.equals(a.optString(i)))return true;return false;}
 JSONObject status()throws Exception {JSONArray history=r.history();int indexed=0,missing=0;for(int n=0;n<history.length();n++){JSONArray images=history.getJSONObject(n).optJSONArray("images");if(images==null)continue;for(int i=0;i<images.length();i++){JSONObject image=images.optJSONObject(i);if(image==null||!image.isNull("deletedAt"))continue;indexed++;String name=image.optString("name");if(!name.matches("[a-zA-Z0-9_.-]+")||!s.file("results/"+name).isFile())missing++;}}return object("running",false,"paused",false,"indexed",indexed,"scanned",indexed,"total",indexed,"missing",missing,"lastError",lastError);}
 JSONObject settings(JSONObject body)throws Exception {if(body!=null){Object raw=body.opt("maxImages");if(!(raw instanceof Number)||((Number)raw).doubleValue()!=Math.floor(((Number)raw).doubleValue())||body.optInt("maxImages")<0||body.optInt("maxImages")>1000000)throw new FxRuntime.ApiError(400,"invalid_limit","请输入 0–1000000 的整数");s.write("library-cleanup/settings.json",object("maxImages",body.getInt("maxImages")));}JSONObject cfg=s.read("library-cleanup/settings.json",object("maxImages",0));return cfg.put("lastError",lastError).put("retentionDays",7);}
 static String digest(File file)throws Exception{return FxGeneration.hash(java.util.Base64.getEncoder().encodeToString(Files.readAllBytes(file.toPath())));}
 JSONObject plan(JSONArray keys)throws Exception{
  if(keys.length()>10000)throw new FxRuntime.ApiError(400,"selection_limit","单次最多 10000 张");JSONArray selected=new JSONArray(),protectedKeys=new JSONArray(),snapshots=new JSONArray(),files=new JSONArray();Set<String> seen=new HashSet<>(),names=new TreeSet<>();JSONObject annotations=annotations().getJSONObject("items");
  for(int n=0;n<keys.length();n++){String k=keys.getString(n);key(k);if(!seen.add(k))continue;String[] parts=k.split(":");JSONObject e=r.historyEntry(parts[0]);int i=Integer.parseInt(parts[1]);JSONObject im=e.getJSONArray("images").optJSONObject(i);if(im==null||!im.isNull("deletedAt"))continue;JSONObject a=annotations.optJSONObject(k);
   // SAF exports belong to the user's chosen provider; never silently delete external documents.
   if(a!=null&&a.optBoolean("favorite")||im.optBoolean("savedToLibrary")||!im.optString("savedPath").isEmpty()||!im.optString("savedName").isEmpty()||im.optString("outputPath").startsWith("content://")){protectedKeys.put(k);continue;}
   String name=im.optString("name");if(!name.matches(parts[0]+"-"+(i+1)+"\\.(png|jpg|jpeg|webp|gif)"))throw new FxRuntime.ApiError(409,"library_cleanup","图片归属无法确认");
   names.add("results/"+name);String output=im.optString("outputPath");if(!output.isEmpty()){File expected=s.file("output/Lucifer-FX-"+name);if(!output.equals(expected.toURI().toString())){protectedKeys.put(k);continue;}names.add("output/Lucifer-FX-"+name);}
   selected.put(k);snapshots.put(object("key",k,"image",FxStorage.cloneJson(im)));
  }
  // Exclude any file referenced by images outside this selection, including saved copies.
  JSONArray history=r.history();for(int n=0;n<history.length();n++){JSONObject e=history.getJSONObject(n);JSONArray images=e.optJSONArray("images");if(images==null)continue;for(int i=0;i<images.length();i++){JSONObject im=images.optJSONObject(i);if(im==null||contains(selected,e.optString("id")+":"+i))continue;names.remove("results/"+im.optString("name"));for(String field:new String[]{"outputPath","savedPath"}){String uri=im.optString(field);if(uri.startsWith("file:")){File f=new File(java.net.URI.create(uri));if(f.getCanonicalPath().startsWith(s.root.getCanonicalPath()+File.separator))names.remove(s.root.toPath().relativize(f.toPath()).toString().replace('\\','/'));}}}}
  // Shared request/raw responses move only when this batch owns every original image.
  // A partial result (including another recoverable trash batch) retains shared files.
  for(int n=0;n<history.length();n++){JSONObject e=history.getJSONObject(n);JSONArray images=e.optJSONArray("images");if(images==null||images.length()==0)continue;boolean all=true;for(int i=0;i<images.length();i++)if(!contains(selected,e.optString("id")+":"+i))all=false;if(all)for(String suffix:new String[]{"-request.json","-raw.zip","-raw.json","-raw.bin"})names.add("results/"+e.getString("id")+suffix);}
  for(String relative:names){File f=s.file(relative);if(f.isFile()){if(Files.isSymbolicLink(f.toPath()))throw new FxRuntime.ApiError(409,"library_cleanup","不清理链接文件");files.put(object("source",relative,"bytes",f.length(),"sha256",digest(f)));}}
  JSONObject plan=object("keys",selected,"protected",protectedKeys,"images",snapshots,"files",files);plan.put("signature",FxGeneration.hash(FxCompat.stable(plan).toString()));return plan;
 }
 JSONObject view(JSONObject plan)throws Exception{JSONArray files=plan.getJSONArray("files");long bytes=0;for(int i=0;i<files.length();i++)bytes+=files.getJSONObject(i).optLong("bytes");return object("count",plan.getJSONArray("keys").length(),"protectedCount",plan.getJSONArray("protected").length(),"bytes",bytes,"files",files.length());}
 JSONObject preview(JSONArray keys)throws Exception{JSONObject plan=plan(keys);String token=UUID.randomUUID().toString();previews.put(token,object("keys",keys,"signature",plan.getString("signature"),"until",System.currentTimeMillis()+600000));while(previews.size()>20)previews.remove(previews.keySet().iterator().next());return view(plan).put("token",token);}
 JSONObject move(JSONObject plan)throws Exception{
  String id=UUID.randomUUID().toString();JSONObject record=FxStorage.cloneJson(plan).put("id",id).put("createdAt",FxRuntime.now()).put("expiresAt",Instant.now().plusSeconds(7*86400).toString()).put("status","moving");JSONArray files=record.getJSONArray("files");for(int i=0;i<files.length();i++)files.getJSONObject(i).put("target","library-cleanup/trash/"+id+"/"+files.getJSONObject(i).getString("source"));s.write("library-cleanup/records/"+id+".json",record);
  try{for(int i=0;i<files.length();i++){JSONObject f=files.getJSONObject(i);File target=s.file(f.getString("target"));target.getParentFile().mkdirs();Files.move(s.file(f.getString("source")).toPath(),target.toPath());}JSONArray images=record.getJSONArray("images");for(int i=0;i<images.length();i++){String[] k=images.getJSONObject(i).getString("key").split(":");JSONObject e=r.historyEntry(k[0]);e.getJSONArray("images").getJSONObject(Integer.parseInt(k[1])).put("deletedAt",record.getString("createdAt"));s.write("history/"+k[0]+".json",e);}record.put("status","trashed");s.write("library-cleanup/records/"+id+".json",record);return view(plan).put("id",id);}catch(Exception e){record.put("status","interrupted");s.write("library-cleanup/records/"+id+".json",record);throw e;}
 }
 JSONArray records()throws Exception{return s.list("library-cleanup/records");}
 File checked(JSONObject record,JSONObject f)throws Exception{String source=f.getString("source"),target=f.getString("target"),id=record.getString("id");FxRuntime.uuid(id);if(!source.matches("(results|output)/[a-zA-Z0-9_.-]+")||!target.equals("library-cleanup/trash/"+id+"/"+source))throw new FxRuntime.ApiError(409,"library_cleanup","回收记录路径无效");File file=s.file(target);if(file.exists()&&(Files.isSymbolicLink(file.toPath())||!digest(file).equals(f.optString("sha256"))))throw new FxRuntime.ApiError(409,"library_cleanup","回收文件已变化");return file;}
 JSONObject restore(String id)throws Exception {FxRuntime.uuid(id);JSONObject record=s.read("library-cleanup/records/"+id+".json",null);if(record==null||!Arrays.asList("trashed","interrupted","moving").contains(record.optString("status")))throw new FxRuntime.ApiError(409,"library_cleanup","没有可恢复记录");JSONArray files=record.getJSONArray("files");for(int i=0;i<files.length();i++){JSONObject f=files.getJSONObject(i);File target=checked(record,f),source=s.file(f.getString("source"));if(source.exists()&&(target.exists()||!digest(source).equals(f.optString("sha256")))||!source.exists()&&!target.exists())throw new FxRuntime.ApiError(409,"library_cleanup","原位置已变化，未覆盖");}for(int i=0;i<files.length();i++){JSONObject f=files.getJSONObject(i);File target=checked(record,f);if(target.exists())Files.move(target.toPath(),s.file(f.getString("source")).toPath());}JSONArray images=record.getJSONArray("images");for(int i=0;i<images.length();i++){JSONObject old=images.getJSONObject(i);String[] k=old.getString("key").split(":");JSONObject e=r.historyEntry(k[0]);JSONObject current=e.getJSONArray("images").getJSONObject(Integer.parseInt(k[1]));if(record.getString("createdAt").equals(current.optString("deletedAt")))e.getJSONArray("images").put(Integer.parseInt(k[1]),old.getJSONObject("image"));s.write("history/"+k[0]+".json",e);}record.put("status","restored");s.write("library-cleanup/records/"+id+".json",record);return object("restored",images.length());}
 JSONObject purge(boolean expired)throws Exception {int count=0;JSONArray records=records();for(int i=0;i<records.length();i++){JSONObject record=records.getJSONObject(i);if(!"trashed".equals(record.optString("status"))||expired&&Instant.parse(record.getString("expiresAt")).isAfter(Instant.now()))continue;JSONArray files=record.getJSONArray("files");for(int j=0;j<files.length();j++)checked(record,files.getJSONObject(j));for(int j=0;j<files.length();j++)Files.deleteIfExists(checked(record,files.getJSONObject(j)).toPath());record.put("status","purged");s.write("library-cleanup/records/"+record.getString("id")+".json",record);count+=record.getJSONArray("keys").length();}return object("purged",count);}
 void schedule(){Executors.newSingleThreadScheduledExecutor().scheduleWithFixedDelay(()->{synchronized(r.generation.lock){synchronized(this){try{if(r.generation.busy())return;purge(true);int max=settings(null).optInt("maxImages");if(max<=0)return;JSONArray all=rows(Collections.emptyMap()),keys=new JSONArray();int excess=all.length()-max;for(int i=all.length()-1;i>=0&&keys.length()<Math.min(excess,10000);i--){JSONArray one=new JSONArray().put(all.getJSONObject(i).getString("key"));if(plan(one).getJSONArray("keys").length()>0)keys.put(one.get(0));}if(keys.length()>0)move(plan(keys));}catch(Exception e){lastError="自动清理未完成，请检查回收站。";}}}},60,60,TimeUnit.SECONDS);}
 JSONObject route(String method,String path,Map<String,String> q,JSONObject body)throws Exception {synchronized(r.generation.lock){synchronized(this){
  if(!method.equals("GET")&&r.generation.busy())throw new FxRuntime.ApiError(409,"generation_busy","请等待任务完成后整理图库");String op=path.substring("/api/generated-library".length());
  if(op.equals("/annotations"))return method.equals("GET")?annotations():importAnnotations(body);
  if(op.equals("/annotation")){String k=body.getString("id")+":"+body.getInt("index");key(k);JSONObject e=r.historyEntry(body.getString("id"));if(e.getJSONArray("images").optJSONObject(body.getInt("index"))==null)throw new FxRuntime.ApiError(404,"not_found","图片不存在");JSONObject all=annotations(),a=all.getJSONObject("items").optJSONObject(k);if(a==null)a=object("favorite",false,"tags",new JSONArray());JSONObject patch=annotation(body);Iterator<String> fields=patch.keys();while(fields.hasNext()){String f=fields.next();a.put(f,patch.get(f));}all.getJSONObject("items").put(k,a);s.write("generated-library/annotations.json",all);return a;}
  if(op.equals("/cleanup/settings"))return settings(method.equals("POST")?body:null);
  if(op.equals("/cleanup/preview"))return preview(body.getJSONArray("keys"));
  if(op.equals("/cleanup/execute")){JSONObject previous=previews.remove(body.optString("token"));if(previous==null||previous.optLong("until")<System.currentTimeMillis())throw new FxRuntime.ApiError(409,"library_cleanup","预览已过期");JSONObject plan=plan(previous.getJSONArray("keys"));if(!plan.getString("signature").equals(previous.getString("signature")))throw new FxRuntime.ApiError(409,"library_cleanup","图片或保护状态已变化，请重新预览");return move(plan);}
  if(op.equals("/cleanup/restore"))return restore(body.getString("id"));
  if(op.equals("/cleanup/purge")){if(!Boolean.TRUE.equals(body.opt("confirm")))throw new FxRuntime.ApiError(400,"confirmation_required","请确认清空");return purge(false);}
  if(op.equals("/cleanup/trash")){JSONArray out=new JSONArray(),records=records();for(int i=0;i<records.length();i++){JSONObject rec=records.getJSONObject(i);if(Arrays.asList("trashed","interrupted","moving").contains(rec.optString("status"))){JSONObject v=view(rec);out.put(object("id",rec.getString("id"),"createdAt",rec.getString("createdAt"),"expiresAt",rec.getString("expiresAt"),"status",rec.getString("status"),"count",v.get("count"),"bytes",v.get("bytes")));}}return object("entries",out);}
  if(op.equals("/status")||op.equals("/rebuild")||op.equals("/pause")||op.equals("/resume"))return status();
  if(op.equals("/item")){JSONObject e=r.historyEntry(q.get("id"));int i=Integer.parseInt(FxRuntime.query(q,"index","0"));return row(e,i,annotations().getJSONObject("items")).put("entry",e);}
  if(op.equals("/select")){Map<String,String> filters=new HashMap<>();body.keys().forEachRemaining(k->filters.put(k,String.valueOf(body.opt(k))));JSONArray all=rows(filters);if(all.length()>10000)throw new FxRuntime.ApiError(400,"selection_limit","单次最多 10000 张");return object("items",all);}
  JSONArray all=rows(q);
  if(op.equals("/groups")){Map<String,Integer> groups=new TreeMap<>();String group=FxRuntime.query(q,"groupBy","date");for(int i=0;i<all.length();i++){JSONObject row=all.getJSONObject(i);JSONArray values=group.equals("tag")?row.getJSONArray("tags"):new JSONArray().put(group.equals("model")?row.optString("model"):row.optString("created_at").substring(0,10));for(int j=0;j<values.length();j++){String v=values.getString(j);groups.put(v,groups.getOrDefault(v,0)+1);}}JSONArray result=new JSONArray();for(Map.Entry<String,Integer> e:groups.entrySet())result.put(object("value",e.getKey(),"count",e.getValue()));return object("groups",result);}
  if(!op.isEmpty())throw new FxRuntime.ApiError(404,"not_found","图库接口不存在");int limit=Math.max(1,Math.min(100,Integer.parseInt(FxRuntime.query(q,"limit","40"))));String cursor=q.get("cursor");JSONArray page=new JSONArray();boolean after=cursor==null,more=false;for(int i=0;i<all.length();i++){JSONObject item=all.getJSONObject(i);if(!after){if(item.getString("key").equals(cursor))after=true;continue;}if(page.length()>=limit){more=true;break;}page.put(item);}return object("items",page,"nextCursor",more?page.getJSONObject(page.length()-1).getString("key"):JSONObject.NULL,"index",object("indexed",all.length(),"running",false));
 }}}
}
