package app.luciferfx.share;
import com.getcapacitor.*;import com.getcapacitor.annotation.CapacitorPlugin;import android.util.Base64;import android.content.Intent;import android.net.Uri;
@CapacitorPlugin(name="FxPlatform")
public class FxPlatformPlugin extends Plugin {
 @PluginMethod public void saveToGallery(PluginCall call){getBridge().execute(()->{Uri uri=null;try{String data=call.getString("data",""),name=call.getString("name","Lucifer-FX.png"),mime=call.getString("mime","image/png");if(data.length()>90*1024*1024||!mime.startsWith("image/")||name.contains("/")||name.contains("\\"))throw new Exception("图片格式或大小无效");android.content.ContentValues values=new android.content.ContentValues();values.put(android.provider.MediaStore.Images.Media.DISPLAY_NAME,name);values.put(android.provider.MediaStore.Images.Media.MIME_TYPE,mime);values.put(android.provider.MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Lucifer FX");values.put(android.provider.MediaStore.Images.Media.IS_PENDING,1);uri=getContext().getContentResolver().insert(android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values);if(uri==null)throw new Exception("无法创建相册图片");try(java.io.OutputStream out=getContext().getContentResolver().openOutputStream(uri,"w")){if(out==null)throw new Exception("相册不可写");out.write(Base64.decode(data,Base64.DEFAULT));}values.clear();values.put(android.provider.MediaStore.Images.Media.IS_PENDING,0);getContext().getContentResolver().update(uri,values,null,null);call.resolve();}catch(Exception e){if(uri!=null)getContext().getContentResolver().delete(uri,null,null);call.reject(e.getMessage());}});}
 @PluginMethod public void copyText(PluginCall call){android.content.ClipboardManager clipboard=(android.content.ClipboardManager)getContext().getSystemService(android.content.Context.CLIPBOARD_SERVICE);clipboard.setPrimaryClip(android.content.ClipData.newPlainText("Lucifer FX Prompt",call.getString("text","")));call.resolve();}
 @PluginMethod public void shareFile(PluginCall call){getBridge().execute(()->{try{String data=call.getString("data",""),name=call.getString("name","Lucifer-FX-share.png"),mime=call.getString("mime","image/png");if(data.length()>90*1024*1024||name.contains("/")||name.contains("\\")||name.equals(".."))throw new Exception("分享文件无效");java.io.File folder=new java.io.File(getContext().getCacheDir(),"exports");folder.mkdirs();java.io.File file=new java.io.File(folder,java.util.UUID.randomUUID()+"-"+name);java.nio.file.Files.write(file.toPath(),Base64.decode(data,Base64.DEFAULT));Uri uri=androidx.core.content.FileProvider.getUriForFile(getContext(),getContext().getPackageName()+".fileprovider",file);Intent intent=new Intent(Intent.ACTION_SEND).setType(mime).putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);getActivity().runOnUiThread(()->{getActivity().startActivity(Intent.createChooser(intent,"分享图片"));call.resolve();});}catch(Exception e){call.reject(e.getMessage());}});}
 @PluginMethod public void saveFile(PluginCall call){getBridge().execute(()->{try{String data=call.getString("data",""),name=call.getString("name","Lucifer-FX-export.bin"),mime=call.getString("mime","application/octet-stream");if(data.length()>90*1024*1024||name.contains("/")||name.contains("\\"))throw new Exception("文件格式或大小无效");MainActivity.export(Base64.decode(data,Base64.DEFAULT),name,mime);call.resolve();}catch(Exception e){call.reject(e.getMessage());}});}
 @PluginMethod public void openExternal(PluginCall call){String value=call.getString("url","");Uri uri=Uri.parse(value);if(!"https".equals(uri.getScheme())){call.reject("仅支持 HTTPS 网页");return;}getActivity().runOnUiThread(()->{try{getActivity().startActivity(new Intent(Intent.ACTION_VIEW,uri));call.resolve();}catch(Exception e){call.reject("无法打开浏览器");}});}
}
