package app.luciferfx.share;

import android.content.Context;import android.net.Uri;
import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.Files;import java.time.*;import java.util.*;import java.util.concurrent.*;
import static app.luciferfx.share.FxStorage.object;

final class FxRuntime {
 static final class ApiError extends Exception{final int status;final String code;ApiError(int status,String code,String message){super(message);this.status=status;this.code=code;}}
 static final class Reply{int status=200;String mime="application/json; charset=utf-8";byte[] bytes;Map<String,String> headers=new HashMap<>();Reply(Object value){bytes=value.toString().getBytes(StandardCharsets.UTF_8);}Reply(byte[] bytes,String mime){this.bytes=bytes;this.mime=mime;}Reply status(int code){status=code;return this;}}
 static volatile FxRuntime instance;static synchronized FxRuntime get(Context c)throws Exception{if(instance==null)instance=new FxRuntime(c);return instance;}
 final String sessionToken=UUID.randomUUID().toString()+UUID.randomUUID().toString();
 final Context context;final FxStorage store;final FxHttp http;final FxGeneration generation;final Semaphore mediaSlots=new Semaphore(4,true);final Object libraryLock=new Object();
 private FxRuntime(Context c)throws Exception{context=c.getApplicationContext();store=new FxStorage(context);http=new FxHttp(store);generation=new FxGeneration(this);seed();if((context.getApplicationInfo().flags&android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0)Files.write(new File(context.getFilesDir(),".fx-debug-session").toPath(),sessionToken.getBytes(StandardCharsets.UTF_8));}
 static String now(){return Instant.now().toString();}
 static void uuid(String id)throws ApiError{if(id==null||!id.matches("[a-f0-9-]{36}"))throw new ApiError(400,"invalid_id","记录 ID 无效");}
 static JSONArray copy(JSONArray a)throws JSONException{return new JSONArray(a.toString());}
 static String query(Map<String,String> q,String k,String def){String v=q.get(k);return v==null?def:v;}
 JSONObject ledger()throws Exception{return store.read("usage/ledger.json",object("version",1,"pricingPolicy","paid","balance",JSONObject.NULL,"balanceAt",JSONObject.NULL,"sessionStartedAt","1970-01-01T00:00:00.000Z","calibrations",new JSONArray(),"adjustments",new JSONArray(),"entries",new JSONArray()));}
 void seed()throws Exception{if(store.read("bootstrap/curated-v1.json",null)!=null)return;if(store.list("library").length()==0){JSONObject bundle=new JSONObject(new String(store.asset("public/curated/library.json"),StandardCharsets.UTF_8));importLibrary(bundle);}store.write("bootstrap/curated-v1.json",object("installed",true,"version",1));}
 JSONArray categories()throws Exception{LinkedHashSet<String> names=new LinkedHashSet<>(Arrays.asList("画风","角色","场景","服装","其他"));JSONArray custom=store.read("library/settings/categories.json",object("names",new JSONArray())).optJSONArray("names");if(custom!=null)for(int i=0;i<custom.length();i++)names.add(custom.getString(i));JSONArray list=store.list("library");for(int i=0;i<list.length();i++){String cat=list.getJSONObject(i).optString("category");if(!cat.isEmpty())names.add(cat);}return new JSONArray(names);}
 void validateCard(JSONObject input)throws Exception{String source=input.optString("sourceUrl");if(!source.isEmpty()&&!source.matches("(?i)^https?://.*"))throw new ApiError(400,"invalid_source","来源链接需要 HTTP(S) 地址");if(!Arrays.asList("draft","preset","snippet","style","starter","character","negative","parameters","favorite").contains(input.optString("kind"))||input.optString("title").trim().isEmpty()||input.optString("title").trim().length()>120)throw new ApiError(400,"invalid_card","预设类型或名称无效");String cover=input.optString("cover");if(!cover.isEmpty()&&(!cover.matches("(?s)^data:image/(png|jpeg|webp);base64,.*")||cover.length()>3*1024*1024))throw new ApiError(400,"invalid_cover","封面格式或大小无效");}
 JSONObject putCard(JSONObject input)throws Exception{synchronized(libraryLock){validateCard(input);String kind=input.optString("kind"),title=input.optString("title").trim();if(!Arrays.asList("draft","preset","snippet","style","starter","character","negative","parameters","favorite").contains(kind)||title.isEmpty()||title.length()>120)throw new ApiError(400,"invalid_card","预设类型或名称无效");String id=input.optString("id",UUID.randomUUID().toString());uuid(id);JSONObject old=store.read("library/"+id+".json",null);if(old!=null&&input.optInt("revision")!=old.optInt("revision"))throw new ApiError(409,"revision_conflict","记录已更新，请重新打开");String cover=input.optString("cover");if(!cover.isEmpty()&&(!cover.matches("(?s)^data:image/(png|jpeg|webp);base64,.*")||cover.length()>3*1024*1024))throw new ApiError(400,"invalid_cover","封面格式或大小无效");JSONObject item=object("version",1,"id",id,"kind",kind,"title",title,"category",input.optString("category","其他"),"notes",input.optString("notes"),"text",input.optString("text"),"sourceUrl",input.optString("sourceUrl"),"cover",cover,"payload",input.opt("payload"),"createdAt",old==null?now():old.optString("createdAt"),"updatedAt",now(),"revision",old==null?1:old.optInt("revision")+1);store.write("library/"+id+".json",item);return item;}}
 JSONArray cards(Map<String,String> q,boolean full)throws Exception{List<JSONObject> rows=new ArrayList<>();JSONArray list=store.list("library");String search=query(q,"q","").toLowerCase(Locale.ROOT),kind=query(q,"kind","");for(int i=0;i<list.length();i++){JSONObject e=list.getJSONObject(i);if(!e.isNull("deletedAt")||(!kind.isEmpty()&&!kind.equals(e.optString("kind"))))continue;if("1".equals(q.get("today"))&&!Instant.parse(e.getString("createdAt")).atZone(ZoneId.systemDefault()).toLocalDate().equals(LocalDate.now()))continue;if(!search.isEmpty()&&!(e.optString("title")+e.optString("category")+e.optString("notes")+e.optString("text")).toLowerCase(Locale.ROOT).contains(search))continue;JSONObject row=FxStorage.cloneJson(e);if(!full)row.remove("payload");rows.add(row);}rows.sort((a,b)->b.optString("updatedAt").compareTo(a.optString("updatedAt")));return new JSONArray(rows);}
 JSONObject backupLibrary()throws Exception{JSONObject bundle=exportLibrary();JSONArray entries=bundle.getJSONArray("entries"),out=new JSONArray();for(int i=0;i<entries.length();i++)if(!"draft".equals(entries.getJSONObject(i).optString("kind")))out.put(entries.get(i));bundle.put("entries",out);return bundle;}
 JSONObject exportLibrary()throws Exception{return object("format","lucifer-library","version",1,"categories",categories(),"entries",cards(Collections.emptyMap(),true));}
 JSONArray importLibrary(JSONObject bundle)throws Exception{if(!"lucifer-library".equals(bundle.optString("format"))||bundle.optInt("version")!=1)throw new ApiError(400,"invalid_library","预设库格式无效");JSONArray entries=bundle.getJSONArray("entries");if(entries.length()>1000)throw new ApiError(400,"too_many_cards","预设数量过多");for(int i=0;i<entries.length();i++)validateCard(entries.getJSONObject(i));JSONArray categoryList=bundle.optJSONArray("categories");if(categoryList!=null){if(categoryList.length()>100)throw new ApiError(400,"invalid_category","分类过多");for(int i=0;i<categoryList.length();i++)if(!(categoryList.get(i) instanceof String)||categoryList.getString(i).trim().isEmpty()||categoryList.getString(i).length()>40)throw new ApiError(400,"invalid_category","分类无效");}JSONArray out=new JSONArray();for(int i=0;i<entries.length();i++){JSONObject e=FxStorage.cloneJson(entries.getJSONObject(i));e.remove("id");e.remove("revision");out.put(putCard(e));}if(categoryList!=null){LinkedHashSet<String> merged=new LinkedHashSet<>();JSONArray old=categories();for(int i=0;i<old.length();i++)merged.add(old.getString(i));for(int i=0;i<categoryList.length();i++)merged.add(categoryList.getString(i));store.write("library/settings/categories.json",object("names",new JSONArray(merged)));}return out;}
 JSONArray history()throws Exception{JSONArray a=store.list("history");List<JSONObject> list=new ArrayList<>();for(int i=0;i<a.length();i++)list.add(a.getJSONObject(i));list.sort((x,y)->y.optString("createdAt").compareTo(x.optString("createdAt")));return new JSONArray(list);}
 JSONObject historyEntry(String id)throws Exception{if(id==null||!id.matches("\\d+-[a-f0-9]{8}"))throw new ApiError(400,"invalid_result","图片记录无效");JSONObject entry=store.read("history/"+id+".json",null);if(entry==null)throw new ApiError(404,"not_found","图片记录不存在");return entry;}
 static String mime(String filename){String f=filename.toLowerCase(Locale.ROOT);if(f.endsWith(".png"))return "image/png";if(f.endsWith(".webp"))return "image/webp";if(f.endsWith(".gif"))return "image/gif";if(f.endsWith(".avif"))return "image/avif";if(f.endsWith(".jpg")||f.endsWith(".jpeg"))return "image/jpeg";if(f.endsWith(".js")||f.endsWith(".mjs"))return "text/javascript; charset=utf-8";if(f.endsWith(".css"))return "text/css; charset=utf-8";if(f.endsWith(".html"))return "text/html; charset=utf-8";if(f.endsWith(".json"))return "application/json; charset=utf-8";if(f.endsWith(".woff2"))return "font/woff2";if(f.endsWith(".ttf"))return "font/ttf";if(f.endsWith(".svg"))return "image/svg+xml";return "application/octet-stream";}
 JSONObject saveResult(String id,int index)throws Exception{synchronized(store.lock){JSONObject entry=historyEntry(id);JSONArray images=entry.getJSONArray("images");if(index<0||index>=images.length())throw new ApiError(400,"invalid_image","图片序号无效");JSONObject image=images.getJSONObject(index);if(image.optBoolean("savedToLibrary"))return object("image",image,"entry",entry);String name=image.getString("name");byte[] bytes=Files.readAllBytes(store.file("results/"+name).toPath());String uri=store.saveTo(store.config().getString("saveDirectory"),"Lucifer-FX-"+name,mime(name),bytes);image.put("savedToLibrary",true);image.put("savedPath",uri);image.put("savedName","Lucifer-FX-"+name);store.write("history/"+id+".json",entry);return object("image",image,"entry",entry);}}
 String priceKey(JSONObject payload)throws Exception{JSONObject nativeBody=payload.optJSONObject("novelai"),b=nativeBody==null?null:nativeBody.optJSONObject("body"),p=b==null?null:b.optJSONObject("parameters");if(p==null)p=new JSONObject();JSONObject key=object("endpoint",nativeBody==null?"/ai/generate-image":nativeBody.optString("endpoint","/ai/generate-image").replace("-stream",""),"model",b==null?payload.optString("model"):b.optString("model"),"action",b==null?"generate":b.optString("action","generate"));for(String field:new String[]{"width","height","steps"})if(p.has(field))key.put(field,p.get(field));key.put("n_samples",1);for(String field:new String[]{"strength","noise","sm","sm_dyn"})if(p.has(field))key.put(field,p.get(field));key.put("upscale",p.has("upscale")&&!Boolean.FALSE.equals(p.opt("upscale"))?p.get("upscale"):JSONObject.NULL);key.put("image_format",p.optString("image_format","png"));key.put("referenceCount",p.optJSONArray("director_reference_images")==null?0:p.getJSONArray("director_reference_images").length());return key.toString();}
 JSONObject quote(JSONObject payload)throws Exception {
  JSONObject nativeRequest=payload==null?null:payload.optJSONObject("novelai"),body=nativeRequest==null?null:nativeRequest.optJSONObject("body"),p=body==null?null:body.optJSONObject("parameters");
  if(p==null)p=new JSONObject();String endpoint=nativeRequest==null?"":nativeRequest.optString("endpoint"),model=body==null?"":body.optString("model"),action=body==null?"generate":body.optString("action","generate");int count=p.optInt("n_samples",1);double width=p.optDouble("width"),height=p.optDouble("height"),steps=p.optDouble("steps"),pixels=width*height;
  boolean supported=Arrays.asList("nai-diffusion-5-full","nai-diffusion-5-full-inpainting").contains(model)&&Arrays.asList("/ai/generate-image","/ai/generate-image-stream").contains(endpoint)&&Arrays.asList("generate","img2img","infill").contains(action)&&!p.optBoolean("upscale")&&!p.optBoolean("sm")&&!p.optBoolean("sm_dyn")&&!p.optBoolean("characterRef")&&p.optString("reference_image").isEmpty()&&(p.optJSONArray("reference_image_multiple")==null||p.getJSONArray("reference_image_multiple").length()==0)&&(p.optJSONArray("director_reference_images")==null||p.getJSONArray("director_reference_images").length()==0);
  boolean valid=Double.isFinite(width)&&Double.isFinite(height)&&Double.isFinite(steps)&&width>0&&height>0&&steps>0&&count>=1&&count<=8,qualifies=supported&&valid&&pixels<=1048576&&steps<=28;
  double strength=!p.optString("mask").isEmpty()?p.optDouble("inpaintImg2ImgStrength",1):action.equals("img2img")||!p.optString("image").isEmpty()?p.optDouble("strength"):1;
  double officialPaid=supported&&valid&&Double.isFinite(strength)&&strength>=0&&strength<=1?Math.max(Math.ceil(Math.ceil(2.951823174884865e-6*pixels+5.753298233447344e-7*pixels*steps)*1.5*strength),2):Double.NaN,paid=officialPaid;
  JSONObject d=ledger();boolean calibrated=false;JSONArray calibration=d.getJSONArray("calibrations");String key=priceKey(payload==null?new JSONObject():payload);for(int i=0;i<calibration.length();i++)if(key.equals(calibration.getJSONObject(i).optString("key"))){paid=calibration.getJSONObject(i).getDouble("amount");calibrated=true;}
  if(!Double.isFinite(paid))return object("known",false,"amount",JSONObject.NULL,"perImage",JSONObject.NULL,"source","unverified","label","暂无法估算");
  boolean free=qualifies&&"opus".equals(d.optString("pricingPolicy"));int credit=free?1:0;return object("known",true,"amount",paid*(count-credit),"perImage",free?0:paid,"paidPerImage",paid,"officialPaidPerImage",Double.isFinite(officialPaid)?officialPaid:JSONObject.NULL,"paidFallback",paid*count,"freeImages",credit,"chargedImages",count-credit,"source",free?"official_opus_conditional":calibrated?"manual_calibration":"official_v5_paid_estimate","conditional",free,"policy",d.optString("pricingPolicy"),"label",free?"Opus 条件预估":calibrated?"手动标定预估":"V5 付费规则预估");
 }
 void recordUsage(JSONObject entry,JSONObject payload)throws Exception{synchronized(store.lock){JSONObject d=ledger();JSONArray entries=d.getJSONArray("entries");for(int i=0;i<entries.length();i++)if(entries.getJSONObject(i).optString("id").equals(entry.optString("id")))return;JSONObject q=quote(payload);Object percent=q.optBoolean("conditional")?q.optDouble("officialPaidPerImage")/26*100/1730:JSONObject.NULL;entries.put(object("id",entry.getString("id"),"createdAt",entry.getString("createdAt"),"status",entry.optString("status"),"estimate",q.opt("amount"),"actual",JSONObject.NULL,"source",q.optString("source"),"conditional",q.optBoolean("conditional"),"opusPercent",percent,"billingUnknown",entry.optJSONObject("error")!=null&&entry.getJSONObject("error").optBoolean("billingUnknown")));store.write("usage/ledger.json",d);}}
 JSONObject getLedger()throws Exception{JSONObject d=FxStorage.cloneJson(ledger());JSONArray entries=d.getJSONArray("entries"),recent=new JSONArray();double total=0,after=0;int unknown=0;String session=d.optString("sessionStartedAt"),balanceAt=d.optString("balanceAt");for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);double value=e.isNull("actual")?"success".equals(e.optString("status"))?e.optDouble("estimate",0):0:e.optDouble("actual",0);if(!Double.isFinite(value))value=0;if(e.optString("createdAt").compareTo(session)>=0){total+=value;if(e.isNull("actual")&&(e.isNull("estimate")||!"success".equals(e.optString("status"))))unknown++;}if(balanceAt.isEmpty()||e.optString("createdAt").compareTo(balanceAt)>=0)after+=value;}for(int i=entries.length()-1;i>=Math.max(0,entries.length()-200);i--)recent.put(entries.get(i));d.put("entries",recent);d.put("sessionTotal",total);d.put("sessionUnknown",unknown);d.put("estimatedBalance",d.isNull("balance")?JSONObject.NULL:d.optDouble("balance")-after);d.put("liveBalanceAvailable",false);return d;}
 JSONObject updateLedger(JSONObject body)throws Exception{synchronized(store.lock){JSONObject d=ledger();String action=body.optString("action");if(action.equals("pricingPolicy")){String v=body.optString("value");if(!Arrays.asList("opus","paid").contains(v))throw new ApiError(400,"invalid_policy","计数规则无效");d.put("pricingPolicy",v);}else if(action.equals("session")){if(!body.optBoolean("confirmReset"))throw new ApiError(400,"reset_confirmation_required","请确认后再重置累计。");d.put("sessionStartedAt",now());}else if(action.equals("actual")){double amount=body.getDouble("amount");if(!Double.isFinite(amount)||amount<0)throw new ApiError(400,"invalid_amount","金额无效");JSONArray entries=d.getJSONArray("entries");boolean found=false;for(int i=0;i<entries.length();i++)if(entries.getJSONObject(i).optString("id").equals(body.optString("id"))){entries.getJSONObject(i).put("actual",amount).put("source","manual_actual");found=true;}if(!found)throw new ApiError(400,"invalid_entry","消费记录不存在");}else if(action.equals("balance")||action.equals("credit")){double amount=body.getDouble("amount");if(!Double.isFinite(amount)||amount<0||(action.equals("credit")&&d.isNull("balance")))throw new ApiError(400,"invalid_amount","请先设置余额，再记录增加的 Anlas。");d.put("balance",action.equals("credit")?d.optDouble("balance",0)+amount:amount);if(action.equals("balance"))d.put("balanceAt",now());d.getJSONArray("adjustments").put(object("id",UUID.randomUUID().toString(),"at",now(),"kind",action,"amount",amount,"note",body.optString("note")));}else if(action.equals("calibrate")){double amount=body.getDouble("amount");if(!Double.isFinite(amount)||amount<0||amount>1000000)throw new ApiError(400,"invalid_amount","报价无效");String key=priceKey(body.getJSONObject("payload"));JSONArray entries=d.getJSONArray("calibrations"),updated=new JSONArray();for(int i=0;i<entries.length();i++)if(!key.equals(entries.getJSONObject(i).optString("key")))updated.put(entries.get(i));updated.put(object("key",key,"amount",amount,"updatedAt",now(),"note",body.optString("note")));d.put("calibrations",updated);d.getJSONArray("adjustments").put(object("id",UUID.randomUUID().toString(),"at",now(),"kind","quote","amount",amount,"key",key,"note",body.optString("note")));}else throw new ApiError(400,"invalid_action","账本操作无效");store.write("usage/ledger.json",d);return getLedger();}}
 JSONObject usage(String zone)throws Exception{JSONObject account=null;String error=null;JSONObject cfg=store.config();if("official".equals(cfg.optString("provider"))&&cfg.has("secret"))try{JSONObject r=http.readOnly("/user/subscription");account=object("active",r.opt("active"),"tier",r.opt("tier"),"usage",r.opt("usage"),"trainingStepsLeft",r.opt("trainingStepsLeft"),"checkedAt",now());}catch(Exception e){error=e.getMessage();}ZoneId timezone=ZoneId.of(zone);String today=LocalDate.now(timezone).toString();double used=0;int known=0,unknown=0,uncertain=0;HashSet<String> seen=new HashSet<>();JSONArray entries=ledger().getJSONArray("entries");for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);if(!seen.add(e.optString("id"))||!Instant.parse(e.getString("createdAt")).atZone(timezone).toLocalDate().toString().equals(today))continue;if("success".equals(e.optString("status"))&&!e.isNull("opusPercent")){used+=e.optDouble("opusPercent");known++;}else unknown++;if(e.optBoolean("billingUnknown")||!"success".equals(e.optString("status")))uncertain++;}JSONObject status=account==null?null:account.optJSONObject("usage");double seconds=status==null?0:status.optDouble("timeUntilNextPercent",0),daily=seconds>0?86400/seconds:0;return object("account",account,"error",error,"liveAvailable",account!=null,"summary",object("date",today,"timeZone",zone,"estimatedPercent",used,"knownRequests",known,"unknownRequests",unknown,"uncertainRequests",uncertain,"dailyRecoveryPercent",daily>0?daily:JSONObject.NULL,"dailyRecoveryRatio",daily>0?used/daily*100:JSONObject.NULL,"accountWide",false,"referenceVersion","official-faq-1730-reference-v1"));}
 Reply api(String method,String p,Map<String,String> q,JSONObject body)throws Exception{
  if(p.equals("/api/status"))return new Reply(object("app","Lucifer NovelAI FX Share","version","1.1.1-share","platform","android","shareEdition",true,"keyConfigured",store.config().has("secret"),"generationJobs",true,"opusBatch",true,"generationBusy",generation.busy(),"activeGeneration",generation.activeJob(),"activeComparison",generation.activeComparison(),"outputDirectory",store.config().optString("outputDirectory"),"saveDirectory",store.config().optString("saveDirectory"),"gateway",store.config().optString("baseURL"),"remoteTagsEnabled",false));
  if(p.equals("/api/settings")){if(method.equals("GET"))return new Reply(store.publicConfig());if(generation.busy()&&(body.has("key")||body.has("clearKey")||body.has("provider")||body.has("baseURL")||body.has("outputDirectory")||body.has("saveDirectory")))throw new ApiError(409,"generation_busy","任务执行期间不能更换连接或目录");return new Reply(store.saveConfig(body));}
  if(p.equals("/api/settings/directory")&&method.equals("POST"))return new Reply(object("path",MainActivity.pickDirectory()));
  if(p.equals("/api/connection/check")&&method.equals("POST")){String kind=store.config().optString("provider");JSONObject result=http.readOnly(kind.equals("openai")?"/v1/models":"/user/subscription");if(kind.equals("official"))updateLedger(object("action","pricingPolicy","value",result.optBoolean("active")&&result.optInt("tier")>=3&&!(result.optJSONObject("usage")!=null&&result.getJSONObject("usage").optBoolean("isNegative"))?"opus":"paid"));return new Reply(object("ok",true,"message","只读连接检查通过；未提交生图。"));}
  if(p.equals("/api/models")){if(!"openai".equals(store.config().optString("provider"))||!store.config().has("secret"))return new Reply(object("data",new JSONArray().put(object("id","nai-diffusion-5-full"))));return new Reply(http.readOnly("/v1/models"));}
  if(p.equals("/api/history"))return new Reply(object("entries",history()));
  if((p.equals("/api/native")||p.equals("/api/request"))&&method.equals("POST")){JSONObject payload;if(p.equals("/api/native")){String route=body.optString("route");if("GET".equals(body.optString("method"))){return new Reply(object("json",http.readOnly(route)));}payload=object("novelai",object("endpoint",route,"body",body.getJSONObject("body")));}else payload=body.getJSONObject("payload");JSONObject accepted=generation.start(object("clientRequestId",UUID.randomUUID().toString(),"payload",payload));String id=accepted.getString("id");for(int i=0;i<2500;i++){JSONObject job=generation.get(id);if(!FxGeneration.live(job.optString("status"))){if(job.has("result"))return new Reply(job.getJSONObject("result"));throw new ApiError(502,"generation_failed",job.optJSONObject("error")==null?"任务未完成，请检查历史，不会自动重试。":job.getJSONObject("error").optString("message"));}Thread.sleep(250);}throw new ApiError(504,"job_wait_timeout","任务仍由后台保存，请检查历史，不要重复提交。");}
  if(p.equals("/api/generation-jobs")&&method.equals("POST"))return new Reply(generation.start(body)).status(202);
  if(p.startsWith("/api/generation-jobs/")){String id=p.split("/")[3];return new Reply(p.endsWith("/stop")&&method.equals("POST")?generation.stop(id):generation.get(id));}
  if(p.equals("/api/comparisons"))return new Reply(method.equals("POST")?generation.startComparison(body):object("entries",generation.comparisons(),"active",generation.activeComparison()));
  if(p.startsWith("/api/comparisons/")){String id=p.split("/")[3];if(p.endsWith("/stop")){if(!method.equals("POST"))throw new ApiError(405,"method_not_allowed","停止任务需要 POST");return new Reply(generation.stopComparison(id));}if(!method.equals("GET"))throw new ApiError(405,"method_not_allowed","不支持此方法");return new Reply(generation.comparison(id,"1".equals(q.get("full"))));}
  if(p.equals("/api/save-result")&&method.equals("POST"))return new Reply(saveResult(body.getString("id"),body.getInt("index")));
  if(p.equals("/api/share-image")){JSONObject e=historyEntry(q.get("id")),im=e.getJSONArray("images").getJSONObject(Integer.parseInt(query(q,"index","0")));String name=im.getString("name");byte[] data=Files.readAllBytes(store.file("results/"+name).toPath());if(!"keep".equals(q.get("metadata")))data=FxGeneration.stripMetadata(data);Reply r=new Reply(data,mime(name));r.headers.put("Content-Disposition","attachment; filename=Lucifer-FX-share-"+name);return r;}
  if(p.startsWith("/api/results/")){String name=p.substring(13);if(!name.matches("[a-zA-Z0-9_.-]+"))throw new ApiError(400,"invalid_file","文件名无效");File f=store.file("results/"+name);if(!f.isFile())throw new ApiError(404,"not_found","文件不存在");return new Reply(Files.readAllBytes(f.toPath()),mime(name));}
  if(p.equals("/api/agent/setup"))return new Reply(object("available",false,"message","MCP stdio 配置用于 Windows 分享版。请在运行 Agent 的电脑打开分享版，点击机器人按钮复制该电脑的配置；手机继续使用自己的独立设置。"));
  if(p.startsWith("/api/atlas/"))return FxAtlas.route(this,method,p,q,body);
  if(p.equals("/api/anlas"))return new Reply(method.equals("POST")?updateLedger(body):getLedger());
  if(p.equals("/api/anlas/quote")){JSONArray payloads=body.optJSONArray("payloads");if(payloads==null)return new Reply(quote(body.optJSONObject("payload")));JSONArray quotes=new JSONArray();double total=0;boolean known=true;for(int i=0;i<payloads.length();i++){JSONObject quote=quote(payloads.getJSONObject(i));quotes.put(quote);known&=quote.optBoolean("known");total+=quote.optDouble("amount",0);}return new Reply(object("quotes",quotes,"total",known?total:JSONObject.NULL));}
  if(p.equals("/api/opus"))return new Reply(usage(query(q,"timeZone","UTC")));
  if(p.equals("/api/library"))return new Reply(method.equals("POST")?putCard(body):object("entries",cards(q,false)));
  if(p.equals("/api/library/categories")){if(method.equals("POST")){String name=body.optString("name").trim();if(name.isEmpty()||name.length()>40)throw new ApiError(400,"invalid_category","分类无效");JSONObject data=store.read("library/settings/categories.json",object("names",new JSONArray()));data.getJSONArray("names").put(name);store.write("library/settings/categories.json",data);}return new Reply(object("categories",categories()));}
  if(p.equals("/api/library/export"))return new Reply(exportLibrary());if(p.equals("/api/library/import")&&method.equals("POST"))return new Reply(object("entries",importLibrary(body)));
  if(p.startsWith("/api/library/")){String id=p.split("/")[3];uuid(id);JSONObject item=store.read("library/"+id+".json",null);if(item==null)throw new ApiError(404,"not_found","记录不存在");if(p.endsWith("/restore")&&!method.equals("POST"))throw new ApiError(405,"method_not_allowed","恢复记录需要 POST");if(method.equals("DELETE")||p.endsWith("/restore")){item.put("deletedAt",p.endsWith("/restore")?JSONObject.NULL:now());item.put("revision",item.optInt("revision")+1);store.write("library/"+id+".json",item);}return new Reply(item);}
  if(p.equals("/api/backup")){if(method.equals("GET")){JSONObject cfg=store.publicConfig();return new Reply(object("format","lucifer-fx-share-backup","version",1,"settings",object("provider",cfg.optString("provider"),"baseURL",cfg.optString("baseURL"),"beginner",cfg.optBoolean("beginner")),"library",backupLibrary(),"createdAt",now()));}if(!"lucifer-fx-share-backup".equals(body.optString("format"))||body.optInt("version")!=1)throw new ApiError(400,"invalid_backup","备份格式无效");if(generation.busy())throw new ApiError(409,"generation_busy","请等待任务结束后再导入备份");if(body.has("settings")){JSONObject cfg=body.getJSONObject("settings");store.saveConfig(object("provider",cfg.optString("provider","official"),"baseURL",cfg.optString("baseURL"),"beginner",cfg.optBoolean("beginner",true)),true);}JSONArray items=importLibrary(body.getJSONObject("library"));if(body.has("settings")){JSONObject cfg=body.getJSONObject("settings");store.saveConfig(object("provider",cfg.optString("provider","official"),"baseURL",cfg.optString("baseURL"),"beginner",cfg.optBoolean("beginner",true)));}return new Reply(object("imported",items.length(),"message","素材已合并；密钥未导入。"));}
  if(p.equals("/api/danbooru/posts"))return new Reply(FxGallery.posts(http,q));
  if(p.equals("/api/danbooru/image")){if(!mediaSlots.tryAcquire(25,TimeUnit.SECONDS))throw new ApiError(429,"image_busy","图库繁忙，请稍后重试");try{String url=q.get("url");byte[] data=http.publicGet(url,true);return new Reply(data,FxGeneration.imageType(data));}finally{mediaSlots.release();}}
  if(p.equals("/api/tags"))return new Reply(object("tags",new JSONArray(),"disabled",true));
  throw new ApiError(404,"not_found","接口不存在");
 }
}
