package app.luciferfx.share;
import fi.iki.elonen.NanoHTTPD;import org.json.*;import java.io.*;import java.util.*;import static app.luciferfx.share.FxStorage.object;
final class FxServer extends NanoHTTPD {
 final FxRuntime runtime;FxServer(FxRuntime r){super("127.0.0.1",8796);runtime=r;}
 @Override public Response serve(IHTTPSession session){try{
  String host=session.getHeaders().getOrDefault("host","");if(!host.matches("(?:127\\.0\\.0\\.1|localhost):8796"))return json(403,object("error",object("code","invalid_host","message","仅允许本机访问")));
  String origin=session.getHeaders().get("origin");if(origin!=null&&!origin.matches("http://(?:127\\.0\\.0\\.1|localhost):8796"))return json(403,object("error",object("code","invalid_origin","message","拒绝跨站点访问")));
  boolean trusted=(session.getUri().equals("/")&&runtime.sessionToken.equals(session.getParms().get("fx_bootstrap")))||runtime.sessionToken.equals(session.getHeaders().get("x-fx-session"))||Arrays.asList(session.getHeaders().getOrDefault("cookie","").split(";\\s*")).contains("FxSession="+runtime.sessionToken);
  if(!trusted)return json(403,object("error",object("code","local_session_required","message","请从 Lucifer FX 应用打开工作台")));
  String method=session.getMethod().name(),p=session.getUri();if(method.equals("OPTIONS")){Response r=newFixedLengthResponse(Response.Status.NO_CONTENT,"text/plain","");r.addHeader("Access-Control-Allow-Methods","GET,POST,PATCH,DELETE,OPTIONS");r.addHeader("Access-Control-Allow-Headers","Content-Type");return r;}
  JSONObject body=new JSONObject();if(Arrays.asList("POST","PUT","PATCH","DELETE").contains(method)){long length=Long.parseLong(session.getHeaders().getOrDefault("content-length","0"));if(length>64*1024*1024)return json(413,object("error",object("message","请求超过 64 MiB")));String data;if(method.equals("PATCH")){ByteArrayOutputStream bytes=new ByteArrayOutputStream();byte[] buffer=new byte[8192];long remaining=length;while(remaining>0){int count=session.getInputStream().read(buffer,0,(int)Math.min(buffer.length,remaining));if(count<0)throw new IOException("请求未完整传输");bytes.write(buffer,0,count);remaining-=count;}data=new String(bytes.toByteArray(),java.nio.charset.StandardCharsets.UTF_8);}else{Map<String,String> files=new HashMap<>();session.parseBody(files);data=files.getOrDefault("postData","");}if(!data.isEmpty())body=new JSONObject(data);}
  FxRuntime.Reply reply;
  if(p.startsWith("/api/"))reply=runtime.api(method,p,session.getParms(),body);
  else{if(!method.equals("GET")&&!method.equals("HEAD"))return json(405,object("error",object("message","不支持此方法")));if(p.contains("..")||p.contains("\\")||p.indexOf('\0')>=0)return json(400,object("error",object("message","路径无效")));String file=p.equals("/")?"index.html":p.substring(1);try{reply=new FxRuntime.Reply(runtime.store.asset("public/"+file),FxRuntime.mime(file));}catch(FileNotFoundException error){return json(404,object("error",object("message","资源不存在")));}}
  Response response=newFixedLengthResponse(Response.Status.lookup(reply.status),reply.mime,new ByteArrayInputStream(reply.bytes),reply.bytes.length);response.addHeader("X-Content-Type-Options","nosniff");response.addHeader("Referrer-Policy","no-referrer");response.addHeader("Content-Security-Policy","default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; worker-src 'self' blob:; frame-src 'self' https://novelai.quicktagcloud.com");if(p.equals("/"))response.addHeader("Set-Cookie","FxSession="+runtime.sessionToken+"; Path=/; HttpOnly; SameSite=Strict");response.addHeader("Cache-Control",p.startsWith("/api/")||p.equals("/")?"no-store":"public, max-age=3600");for(Map.Entry<String,String> h:reply.headers.entrySet())response.addHeader(h.getKey(),h.getValue());return response;
 }catch(Exception error){try{int status=error instanceof FxRuntime.ApiError?((FxRuntime.ApiError)error).status:500;String code=error instanceof FxRuntime.ApiError?((FxRuntime.ApiError)error).code:"local_error",message=error.getMessage()==null?"本地操作未完成":error.getMessage();return json(status,object("error",object("code",code,"message",message)));}catch(Exception ignored){return newFixedLengthResponse(Response.Status.INTERNAL_ERROR,"application/json","{\"error\":{\"message\":\"Local operation failed\"}}");}}}
 static Response json(int status,JSONObject value){return newFixedLengthResponse(Response.Status.lookup(status),"application/json; charset=utf-8",value.toString());}
}
