package app.luciferfx.share;
import com.getcapacitor.BridgeActivity;import android.os.*;import android.content.*;import android.net.Uri;import android.app.AlertDialog;import android.webkit.URLUtil;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import java.util.concurrent.*;import java.io.*;
public class MainActivity extends BridgeActivity {
 static volatile MainActivity current;static FxServer server;static CompletableFuture<String> directory;static CompletableFuture<Uri> destination;
 final ActivityResultLauncher<Intent> treePicker=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->{CompletableFuture<String> f=directory;directory=null;if(f==null)return;try{if(r.getResultCode()==RESULT_OK&&r.getData()!=null){Uri uri=r.getData().getData();getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);f.complete(uri.toString());}else f.complete("");}catch(Exception e){f.completeExceptionally(e);}});
 final ActivityResultLauncher<Intent> filePicker=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->{CompletableFuture<Uri> f=destination;destination=null;if(f!=null)f.complete(r.getResultCode()==RESULT_OK&&r.getData()!=null?r.getData().getData():null);});
 @Override public void onCreate(Bundle state){current=this;registerPlugin(FxPlatformPlugin.class);try{FxRuntime runtime=FxRuntime.get(this);this.config=new com.getcapacitor.CapConfig.Builder(this).setServerUrl("http://127.0.0.1:8796/?fx_bootstrap="+runtime.sessionToken).setAllowNavigation(new String[]{"127.0.0.1"}).setAllowMixedContent(false).setWebContentsDebuggingEnabled((getApplicationInfo().flags&android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0).setLoggingEnabled((getApplicationInfo().flags&android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0).create();if(server==null){server=new FxServer(runtime);server.start(600000,false);}}catch(Exception e){super.onCreate(state);new AlertDialog.Builder(this).setTitle("启动失败").setMessage("应用数据或本机端口无法打开，请重新启动应用。已有图片不会删除。").setPositiveButton("关闭",(d,w)->finish()).show();return;}super.onCreate(state);getBridge().getWebView().setDownloadListener((url,userAgent,disposition,mime,length)->new Thread(()->{try{if(!url.startsWith("http://127.0.0.1:8796/"))throw new IOException("请使用应用内下载按钮");java.net.URLConnection connection=new java.net.URL(url).openConnection();connection.setRequestProperty("X-FX-Session",FxRuntime.get(this).sessionToken);byte[] bytes;try(InputStream input=connection.getInputStream()){bytes=FxStorage.bounded(input,64*1024*1024);}export(bytes,URLUtil.guessFileName(url,disposition,mime),mime==null?"application/octet-stream":mime);}catch(Exception e){showError(e.getMessage());}}).start());}
 static String pickDirectory()throws Exception{MainActivity a=current;if(a==null)throw new IOException("请回到应用选择目录");synchronized(MainActivity.class){if(directory!=null)throw new IOException("另一个目录选择窗口仍然打开");directory=new CompletableFuture<>();}CompletableFuture<String> wait=directory;a.runOnUiThread(()->a.treePicker.launch(new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)));return wait.get();}
 static void export(byte[] bytes,String name,String mime)throws Exception{MainActivity a=current;if(a==null)throw new IOException("请回到应用保存文件");synchronized(MainActivity.class){if(destination!=null)throw new IOException("另一个保存窗口仍然打开");destination=new CompletableFuture<>();}CompletableFuture<Uri> wait=destination;a.runOnUiThread(()->a.filePicker.launch(new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(mime).putExtra(Intent.EXTRA_TITLE,name)));Uri uri=wait.get();if(uri==null)throw new IOException("已取消保存，未写入文件。");try(OutputStream out=a.getContentResolver().openOutputStream(uri,"w")){if(out==null)throw new IOException("无法写入所选文件");out.write(bytes);}}
 static void requestTaskNotifications(){MainActivity a=current;if(a!=null&&Build.VERSION.SDK_INT>=33&&a.checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)a.runOnUiThread(()->a.requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},31001));}
 static void showError(String message){MainActivity a=current;if(a!=null)a.runOnUiThread(()->new AlertDialog.Builder(a).setTitle("操作未完成").setMessage(message).setPositiveButton("知道了",null).show());}
 @Override public void onDestroy(){if(current==this){current=null;CompletableFuture<String> d=directory;directory=null;if(d!=null)d.completeExceptionally(new IOException("目录选择已结束"));CompletableFuture<Uri> f=destination;destination=null;if(f!=null)f.complete(null);}super.onDestroy();}
}
